.TH i-haklab 1 "Dec 2023" "" "General Commands Manual"
.nh
.ad l
.
.SH NAME
.
i-haklab \- In charge of the i-haklab laboratory
.
.SH SYNOPSIS
.
.B i-haklab
.RI [ OPTION ]...\&
.RI [ ARG ]
.
.SH OPTIONS
.
.SS General options:
.
.TP
.BR -h ", " --help
Display help and exit
.
.TP
.BR -v ", " --version
Display version and exit
.
.SS Configutacion:
.
.TP
.B --name-user
Change username (default i-haklab)
.
.TP
.B --A
aaaaaa
.
.PP
Note: probando.
.
.SS dpkg:
.
.TP
.B --f
C
.
.SH SEE ALSO
.
https://victorh028.github.io/i-Haklab/
.
