#!/data/data/com.termux/files/usr/bin/bash
#This script will install and run a termux 2048 game
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

if [ -L ~/storage/external-1 ]; then
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-haklab
fi
while [ ! $(id -u) -ne 0 ]; do
        printf "$R[W]:-> You need to be a common user$W\n"
        exit
done
until [ -d $iHAKLAB ]; do
        printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
        while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
                continue
        done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
        git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else
        printf "$G\n[!]-> Have a nice hacking day!!\n\n"
        exit
fi
done
if [ ! -e $PREFIX/bin/2048 ]; then
	if [ ! -d $iHAKLAB/games/game2048 ]; then
		mkdir -p $iHAKLAB/games/game2048
	fi
	wget https://raw.githubusercontent.com/mevdschee/2048.c/master/2048.c -O $iHAKLAB/games/game2048/2048.c
	gcc -o $PREFIX/bin/2048 $iHAKLAB/games/game2048/2048.c
	rm -rf $iHAKLAB/games/game2048
fi
clear;2048
#		@Ivam3
