#!/data/data/com.termux/files/usr/bin/bash
#This script will install and run a termux mathomatic game
#
if [ ! -e $PREFIX/bin/mathomatic ]; then
	apt install mathomatic -y
fi
clear
mathomatic
#		@Ivam3
