#!/data/data/com.termux/files/usr/bin/bash
#This script will install and run a termux snake game
#
if [ ! -e $PREFIX/bin/snakegame ]; then
	curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/snakegame -o $PREFIX/bin/snakegame
fi
snakegame
#		@Ivam3
