#!/data/data/com.termux/files/usr/bin/bash
#This script will install i-Haklab v.1.0 2019 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3. Please do not use in military or secret service organizations, or for illegal purposes.
IFS=$'\n\t'
trap ctrl_c 2
PARTITION=$(echo "$PWD" | grep -o sdext2)
function ctrl_c() {
	echo
	printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
while [ "$USER" = "root" ]; do
	printf "$R\n[W]:-> You need to be a common user to install i-Haklab$W\n"
	exit
done
until [ -e /data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab/setup ] || [ -e /data/data/com.termux/files/home/i-Haklab/setup ]; do
	printf "$R\n[W]:-> i-Haklab directory must to be in home directory$W\n"
	exit
done
apt update && apt upgrade
apt install -y fish root-repo util-linux coreutils vim python python2 ruby perl clang curl wget make openssl fish openssl-tool php zip unzip tar w3m neofetch dirmngr weechat irssi tor htop bison megatools findutils git apr apr-util openssh libtool pkg-config termux-tools ncurses-utils ncurses postgresql termux-elf-cleaner libcaca cmatrix fortune figlet man termux-api hydra megatools axel fortune apksigner -y
python -m pip install --upgrade pip
python2 -m pip install --upgrade pip
python -m pip install trufflehog
#if [ -d /data/data/com.termux/files/home/storage ]; then
#	rm -rf /data/data/com.termux/files/home/storage
#fi
if [ -e $PREFIX/libexec/colors ]; then
        rm $PREFIX/libexec/colors
fi
#termux-setup-storage
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/colors -o $PREFIX/libexec/colors
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/var/alias -o $PREFIX/var/alias
source $PREFIX/libexec/colors
echo $(clear)
        printf "$C"
                echo "            -{> i-Haklab <} "
                echo "   -{ SO > Android - Only for Termux } "
                echo "             -{ Coded by } "
                printf "$G"
                echo "      =============================="
                echo "      .___.                 ______,"
                echo "      |   |__ ______   ___  \_____ \ "
                echo "      |   \ \/ /\__ \ /   \   _(__ <,"
                echo "      |   |\   / __ \| Y Y \ /      \ "
                echo "      |___| \_/ (____|__|_| /______ /"
                echo "                     \/    \/      \/ "
                echo "      ====== By ___ Cinderella ======"
        printf "$C\n"
                echo "          [---] Join me on [---]"
                echo "[-] www.youtube.com/c/ivam3bycinderella [-]"
                echo "      [-] t.me/Ivam3byCinderella [-]"
                echo "            [-] t.me/ivam3 [-]"
        printf "$G\n"
                echo "        [---] SPECIAL THANKS [---]"
        	echo "                    TO "
		echo "       [-] MY MASTER CINDERELLA [-]"
	printf "$W"
        	echo "             People don't die"
        	echo "    If they still live in the hearts"
        	echo "           of their loved ones"
        	echo "       We love her ... We miss her"
        	echo "                   *RIP*"
        printf "$R\n"
                echo "          [---] DISCLAIMER [---]"
        printf "$W"
                echo "   If the law is violated with it's use"
                echo "     This would be the responsibility"
                echo "        of the user who handled it"
        printf "$R"
                echo "       [-] Use At Your Own Risk [-]"
        printf "$W\n"
        printf "$C         Press$G ENTER$C to continue"
        printf "$W\n"
        read enter
CHECKROOT=$(bash /data/data/com.termux/files/home/i-Haklab/.set/to-install/check-root)
USR=$(whoami)
	if [ $CHECKROOT = "root" ]; then
	command -v sudo > /dev/null || bash /data/data/com.termux/files/home/i-Haklab/.set/to-install/instasudo
        if [ -e /data/data/com.termux/files/home/.suroot/.bashrc ]; then
                if [ ! -O /data/data/com.termux/files/home/.suroot/.bashrc ]; then
                                sudo chown $USR:$USR /data/data/com.termux/files/home/.suroot/.bashrc
                fi
        fi
        echo "PS1=\"\[\e[33m\][!] \[\e[31m\]Type\[\e[32m\] exit\[\e[31m\] to log out\[\e[32m\] ➤ \[\e[m\]\"" > /data/data/com.termux/files/home/.suroot/.bashrc
        echo "export TERM=xterm-256color" >> /data/data/com.termux/files/home/.suroot/.bashrc
        echo "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" >> /data/data/com.termux/files/home/.suroot/.bashrc
        echo "export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/xbin:/system/bin" >> /data/data/com.termux/files/home/.suroot/.bashrc
        echo "HOME=/data/data/com.termux/files/home/storage/external-1/roothome" >> /data/data/com.termux/files/home/.suroot/.bashrc
	echo "fish" >> /data/data/com.termux/files/home/.suroot/.bashrc
        echo "#          i-Haklab by @Ivam3" >> /data/data/com.termux/files/home/.suroot/.bashrc
        echo "alias server-php=\"sudo php -S LOCALHOST:80 -t $PREFIX/var/service/php/\"" >> $PREFIX/var/alias
else
        sed -i "3a alias server-php=\"php -S LOCALHOST:4546 -t $PREFIX/var/service/php/\"" $PREFIX/var/alias
fi
if [ -L /data/data/com.termux/files/home/storage/external-1 ] && [ -z $PARTITION ]; then
        until [ -d /data/data/com.termux/files/home/storage/external-1/roothome ]; do
                printf "$R\n[W]-> O-ops!!$W roothome directory cannot be created\n"
                mkdir -p /data/data/com.termux/files/home/storage/external-1/roothome
        done
        until [ -O /data/data/com.termux/files/home/storage/external-1/roothome ]; do
                printf "$R\n[W]-> O-ops!!$W Your are not owner of roothome directory\n"
                sudo chown $USR:$USR /data/data/com.termux/files/home/storage/external-1/roothome
        done
        cp -r /data/data/com.termux/files/home/i-Haklab /data/data/com.termux/files/home/storage/external-1/roothome/
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
elif [ ! -z $PARTITION ] || [ -d /data/data/com.termux ]; then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
else
        printf "$R\n[W]-> STORAGE ACCESS DENIED$W\n"
	exit
fi

SRCH=$(ls $iHAKLAB/.set/to-install/ | grep -iv .zip | grep -iv metasploit | grep -iv embed+java | grep -iv instasudo | grep -iv checkroot | grep -iv i-haklab_login | grep -iv login | grep -iv functions | grep -iv QG)

for TOOL in $SRCH ; do
        printf "$Y\n[!]->$G Installing $TOOL"
        bash $iHAKLAB/.set/to-install/$TOOL
	printf "\n\n"
done
bash $iHAKLAB/.set/to-install/metasploit
bash $iHAKLAB/.set/to-install/embed+java
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/i-Haklab -o $PREFIX/bin/i-Haklab
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/lock -o $PREFIX/bin/lock
chmod +x $PREFIX/bin/i-Haklab
pkg install fish -y
curl -L http://get.oh-my.fish | fish
echo "alias postgresql=\"pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql\"" >> $PREFIX/etc/fish/config.fish
sed "27d" ~/.config/fish/fish_variables > $PREFIX/tmp/fish_variables
rm ~/.config/fish/fish_variables 
mv $PREFIX/tmp/fish_variables ~/.config/fish/
sed -i "18a set iHAKLAB $iHAKLAB" $PREFIX/etc/fish/config.fish
echo "source $PREFIX/var/alias" >> $PREFIX/etc/fish/config.fish
bash $iHAKLAB/.set/to-install/functions
bash $iHAKLAB/.set/to-install/i-Haklab_login
#for del in bin functions login-files sqliv var ; do
#	rm -rf $iHAKLAB/.set/$del
#done
if [ -e ~/ivam3-Haklab ]; then
	rm ~/ivam3-Haklab
fi
if [ -d /data/data/com.termux/files/home/i-Haklab ] && [ -d /data/data/com.termux/files/home/storage/external-1/roothome/i-haklab ]; then
	rm -rf /data/data/com.termux/files/home/i-Haklab
fi
bash $iHAKLAB/.set/libexec/review

printf "$Y\n\n[!]->$G i-Haklab installed !!!$Y |$W Please restart Termux and enjoy it!!\n\n"

#		@Ivam3
