#!/data/data/com.termux/files/usr/bin/bash
#This script use @abhacker repositories
#:to downgrade ruby version
#::and reinstall metasploit
#:::credits to @abhacker
trap ctrl_c 2

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'
iHDB="https://github.com/ivam3/i-Haklab/raw/master/.set"
JAVADB="https://raw.githubusercontent.com/ivam3/java/master"
REPO_DIR=$"$PREFIX/etc/apt/sources.list.d/abhacker.repo.list"
PACKAGE=$"/data/data/com.termux/files/usr/share/gnupg"
APT_DIR="/data/data/com.termux/files/usr/etc/apt"
SOURCES_LIST="${APT_DIR}/sources.list.d"
PREFIX="/data/data/com.termux/files/usr"
PUB_DIR=$"$PREFIX/etc/apt/trusted.gpg"
ARCH=`dpkg --print-architecture`
TMPDIR="${PREFIX}/tmp"
SHLL=$(echo $SHELL |awk -F "/" '{print $8}')

if [ $SHLL = fish ]; then
	INITFILE="$PREFIX/etc/fish/config.fish"
else
	INITFILE="$PREFIX/etc/bash.bashrc"
fi

ctrl_c(){ printf "$R\n\n\t[w] Need a help? [w]$B\n      Telegram : t.me/Ivam3_Bot$W\n";exit;}

#:::: DROPPING LAST VERSIONS ::::#
printf "$B\n(_➤) Uninstalling ruby and metasploit [${ARCH}]\n"
for del in ~/metasploit-framework ${PREFIX}/opt/metasploit-framework ${PREFIX}/lib/ruby;do
	if [ -d "$del" ];then
		rm -rf $del
	fi
done
command -v ruby >/dev/null |pkg remove ruby -y >/dev/null 2>&1

if [ ! -e "${SOURCES_LIST}" ]; then
    mkdir -p "${SOURCES_LIST}"
fi

if [ ! -e "${TMPDIR}" ]; then
    mkdir -p "${TMPDIR}"
fi

if [ ! -d "$PACKAGE" ];then
    printf "$G\n[+]─➤ Installing dependencies$W\n"
    yes|pkg update && pkg install gnupg >/dev/null 2>&1
fi

#:::: DOWNLOADING SIGNED KEY ::::#
grep -q "abhackerofficial@gmail.com" $PUB_DIR &> /dev/null
printf "$G\n(_➤) Adding Public GPG Key [${ARCH}]\n"
curl -fsSL https://abhackerofficial.github.io/abhacker.repo/abhacker.repo.key | apt-key add &> /dev/null &

if [ ! -f "$PREFIX/etc/raw_keys" ];then
	mkdir -p ${PREFIX}/etc/raw_keys
fi

if [ ! -f "$PREFIX/etc/raw_keys/abhacker.repo.key" ];then
	curl -fsSL https://github.com/abhackerofficial/abhacker.repo/raw/master/abhacker.repo.key | cat &> ${PREFIX}/etc/raw_keys/abhacker.repo.key &
fi

get1=`curl -fsSL https://github.com/abhackerofficial/abhacker.repo/raw/master/abhacker.repo.key | awk NR==3 &`
get2=`cat $PREFIX/etc/raw_keys/abhacker.repo.key | awk NR==3`

if [[ ${get1} != ${get2} ]];then
	printf "$G\n(_➤) Adding Public GPG Key [${ARCH}]\n"
	curl -fsSL https://github.com/abhackerofficial/abhacker.repo/raw/master/abhacker.repo.key | cat &> ${PREFIX}/etc/raw_keys/abhacker.repo.key &
	curl -fsSL https://github.com/abhackerofficial/abhacker.repo/raw/master/abhacker.repo.key | apt-key add &> /dev/null
else
	printf "$Y\n(_➤) Public GPG Key Already exists [${ARCH}]\n"
fi

aarch64_architecture() {
	printf "# abhacker's repository\ndeb [arch=all,aarch64] https://abhackerofficial.github.io/abhacker.repo/ abhacker main" > "${SOURCES_LIST}/abhacker.repo.list"
	}
arm_architecture() {
	printf "# abhacker's repository\ndeb [arch=all,arm] https://abhackerofficial.github.io/abhacker.repo/ abhacker main" > "${SOURCES_LIST}/abhacker.repo.list"
	}
i686_architecture() {
	printf "# abhacker's repository\ndeb [arch=all,i686] https://abhackerofficial.github.io/abhacker.repo/ abhacker main" > "${SOURCES_LIST}/abhacker.repo.list"
	}
x86_64_architecture() {
	printf "# abhacker's repository\ndeb [arch=all,x86_64] https://abhackerofficial.github.io/abhacker.repo/ abhacker main" > "${SOURCES_LIST}/abhacker.repo.list"
	}

#:::: ABHACKERS's REPOSITORY::::#
if [ -f "$REPO_DIR" ];then
	printf "$Y\n(_➤) ABHacker's Repository Already exists [${ARCH}]\n"
	sleep 1
else
	printf "$G\n(_➤) Adding ABHacker's Repository [${ARCH}]\n"
	sleep 1
	case "$ARCH" in
		aarch64)
			aarch64_architecture
			;;
		arm)
			arm_architecture
			;;
		armhf)
			arm_architecture
			;;
		i686)
			i686_architecture
			;;
		x86_64)
			x86_64_architecture
			;;
	esac
fi

printf "$G\n(_➤) Updating Termux [${ARCH}]\n$W"
apt-get update >/dev/null 2>&1
printf "$G\n(_➤) Install package : apt install <pkg>$W"

if [[ ${1} == "--install" || ${1} == "-i" ]];then
 if [[ ${#2} -gt "0" ]];then
  apt install "${2}"
  if [[ ${3} == "--run" || ${3} == "-r" ]];then
   if [[ ${#3} -gt "0" ]];then
   ${4} $5 $6 $7 $8 $9
  fi
 fi
fi

elif [[ ${1} == "--update" || ${1} == "-u" ]];then
  if [[ ${#2} -gt "0" ]];then
 apt upgrade "${2}"
  fi

elif [[ ${1} == "--list" || ${1} == "-l" ]];then
list() {
 apt list | grep -a "abhacker" | head -n -0
}
 printf "`list`\n" | cut -d ":" -f 2

elif [[ ${1} == "--show" || ${1} == "-s" ]];then
  if [[ ${#2} -gt "0" ]];then
  apt search ${2}
  fi

elif [[ ${1} == "--remove" || ${1} == "-r" ]];then
  if [[ ${#2} -gt "0" ]];then
apt autoremove ${2}
  fi
fi

printf "$G\r\n(_➤) Installing ...$W "
! command -v i-Haklab >/dev/null || gem install lolcat >/dev/null 2>&1
printf "lolcat\r"
sleep 1
printf "$G\r(_➤) Installing ...$W "
if ! cat ${INITFILE} | grep -oE "postgresql" --silent;then
	sed -i "4a alias postgresql=\"pg_ctl -D ${PREFIX}/var/lib/postgresql\"" $INITFILE
fi
printf "postgresql\r\n"
sleep 1

if [ -d ${PREFIX}/opt/metasploit-framework ] && [ -x $PREFIX/bin/msfconsole ];then
	wget $JAVADB/.embed/apk.rb -O ${PREFIX}/opt/metasploit-framework/lib/msf/core/payload/apk.rb -q
	printf "\n\n$C ::::::::: METASPLOIT INSTALLED :::::::::$W\n"
	printf " The data base can be active with command\n\t$G   > postgresql start <$W\n"
	printf "      Now you can run it with command$G\n\t$G   >    msfconsole    <\n"
	printf "\n$R :::::::::::::: ADVERSMENT ::::::::::::::$W\n"
	printf "        If msfconsole didn't run\n         execute the file RuGiR\n       (Ruby Gem issues Resolved)\n    to try to fix it with another steps\n\t$G   > IbyC-fixer RuGiR <$W\n\n"
else
	ctrl_c
fi

#                           i-Haklab by @Ivam3
