# ShellPhish v1.7
## Author: github.com/thelinuxchoice
## IG: instagram.com/thelinuxchoice
### Don't copy this code without give me the credits, nerd! 
### This script uses some webpages generated by SocialFish Tool (https://github.com/UndeadSec/SocialFish)
### Instagram webpage generated by An0nUD4Y (@its_udy) (https://github.com/An0nUD4Y)

Phishing Tool for Instagram, Facebook, Twitter, Snapchat, Github, Yahoo, Protonmail, Google, Spotify, Netflix, Linkedin, Wordpress, Origin, Steam, Microsoft, InstaFollowers, Pinterest +1 customizable

### Features:
### Port Forwarding using Ngrok or Serveo

## Legal disclaimer:

Usage of Shellphish for attacking targets without prior mutual consent is illegal. It's the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program 

![shellp](https://user-images.githubusercontent.com/34893261/43082609-d6273f58-8e6a-11e8-97f3-df56e03ad83d.png)

### Usage:
```
git clone https://github.com/thelinuxchoice/shellphish
cd shellphish
bash shellphish.sh
```

### Donate!
Support the authors:

<noscript><a href="https://liberapay.com/thelinuxchoice/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a></noscript>
