#!/data/data/com.termux/files/usr/bin/bash
#Created on sept/2019
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C REVIEW i-HAKLAB INSTALLATION. . . .$i"
        printf "\n\n"
        sleep 1
done
#REVIEW
CNF=$(cat $PREFIX/etc/bash.bashrc | grep -oE "source")
RUN=$(command -v run | grep -o "run")
iHaklab=$(command -v i-Haklab | grep -o "i-Haklab")
SUDO=$(command -v sudo | grep -o "sudo")
FISH=$(command -v fish | grep -o "fish")
LOGIN=$(ls $PREFIX/var/log/login-termux | grep -oE "login")
LBANNER=$(ls $PREFIX/libexec/banner/login-banner | grep -oE "login-banner")
WBANNER=$(ls $PREFIX/libexec/banner/wall-banner | grep -oE "wall")

for i in Ivam3 Cinderella Quiz ; do
	if [ -e $PREFIX/libexec/termux/.$i ]; then
		STATUS="Ok"
	else
		STATUS="Fail"
	fi
	sleep 1
	printf "$Y[!]:-> $i ....$W $STATUS\n"
done

for c in $CNF $iHaklab $RUN $SUDO $FISH $LOGIN $LBANNER $WBANNER ; do
	if [ ! -z $c ]; then
		STATUS="OK"
	else
		STATUS="Fail"
	fi
	sleep 1
	printf "$Y[!]:-> $c ....$W $STATUS\n"
done


#		@IVAM3
