#!/data/data/com.termux/files/usr/bin/bash
#Created on sept/2019
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

#FILE.LOG

touch $PREFIX/var/log/i-Haklab.log
echo $iHAKLAB >> $PREFIX/var/log/i-Haklab.log
echo "<bash.rc>" >> $PREFIX/var/log/i-Haklab.log
cat $PREFIX/etc/bash.bashrc >> $PREFIX/var/log/i-Haklab.log
echo "<config.fish>" >> $PREFIX/var/log/i-Haklab.log
cat $PREFIX/etc/fish/config.fish >> $PREFIX/var/log/i-Haklab.log
for i in Ivam3 Cinderella Quiz ; do
	ls $PREFIX/libexec/termux/.$i >> $PREFIX/var/log/i-Haklab.log
done
for c in run i-Haklab sudo fish lock  ; do
	command -v $c >> $PREFIX/var/log/i-Haklab.log
done
ls $PREFIX/var/log/login-termux >> $PREFIX/var/log/i-Haklab.log
ls $PREFIX/libexec/banner/login-banner >> $PREFIX/var/log/i-Haklab.log
ls $PREFIX/libexec/banner/wall-banner >> $PREFIX/var/log/i-Haklab.log
ls $HOME/.config/fish/functions/ >> $PREFIX/var/log/i-Haklab.log

#		@IVAM3
