#!/data/data/com.termux/files/usr/bin/bash
#
#i-Haklab v.1.0 2019 by Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. Please do not use in military or secret service organizations, or for illegal purposes
#
#Created on Jan/2019
####################

IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;chmod 711 *;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done
OLDver=$(cat $iHAKLAB/.set/libexec/banner/i-Haklab | grep -o v.*.*.9 | awk '{print $1}')
NEWver=$(cat $iHAKLAB/README.md | grep -o v.*.*.9 | awk '{print $1}')

if [ -d $iHAKLAB ]; then
#	rm -rf $iHAKLAB
#	git clone https://github.com/ivam3/i-Haklab.git $iHAKLAB
	chmod 711 -R $iHAKLAB
#Lock
	if [ ! -e $PREFIX/bin/lock ]; then
		curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/lock -o $PREFIX/bin/lock
		printf "$Y\n\n[!]-> Command lock upgraded$W\n"
	fi
#run
	if [ -e $iHAKLAB/.set/bin/run ]; then
		curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/run -o $PREFIX/bin/run
		chmod 711 $PREFIX/bin/run
		printf "$Y\n\n[!]-> Command run upgraded$W\n"
	fi
#Functions
	TARGET=$(ls $iHAKLAB/.set/to-install/functions)
	for i in ${TARGET[*]}; do
                if [ ! -e $i ]; then
		exec $iHAKLAB/.set/to-install/functions
		printf "$Y\n\n[!]-> Function $i added$W\n"
		fi
	done
	if [ -e $iHAKLAB/.set/bin/i-Haklab ]; then
		curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/i-Haklab -o $PREFIX/bin/i-Haklab
		printf "$Y\n\n[!]-> Command i-Haklab upgraded$W\n"
	fi
#searchsploit
	for tool in exploitdb cloudbunny aquatone kerbrute GetNPUsers ; do
		if [ ! -d $iHAKLAB/../$tool ]; then
			printf "$Y\n[!]-> $tool tool was added to i-Haklab$W |$Y Install it running$G\n\t]>$W i-Haklab install $tool\n"
		fi
		sleep 1
	done
else
	printf "$R\n[w]-> Not such i-Haklab directory$W\n$iHAKLAB\n$W"
	exit
fi
#			@Ivam3
