#!/data/data/com.termux/files/usr/bin/bash
#
#i-Haklab v.1.0 2019 by Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. Please do not use in military or secret service organizations, or for illegal purposes
#
#Created on Jan/2019
####################


IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;chmod 711 *;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done
Install() {
	echo $(clear)
	for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
		printf "$(clear) $C UPGRADING i-HAKLAB. . . .$i"
		printf "\n\n"
		sleep 1
	done
}
Chao-chao() {
	printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
}

OLDver=$(cat $iHAKLAB/.set/libexec/banner/i-Haklab | grep -o v.*.*.9 | awk '{print $1}')
NEWver=$(cat $iHAKLAB/README.md | grep -o v.*.*.9 | awk '{print $1}')

rm -rf $iHAKLAB
git clone https://github.com/ivam3/i-Haklab.git $iHAKLAB
chmod 711 -R $iHAKLAB

if [ "$NEWver" = "$OLDver" ]; then
#
#	if [ ]; then
#		bash $iHAKLAB/.set/to-install/
#		printf "$Y[!]->$W John The Ripper tool was added!!\n"
#	fi

#Lock
	if [ ! -e $PREFIX/bin/lock ]; then
		curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/lock -o $PREFIX/bin/lock
	fi
#run
	if [ ! -e $PREFIX/bin/run ]; then
		curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/run -o $PREFIX/bin/run
		chmod 711 $PREFIX/bin/run
	fi
#Functions
	if [ ! -e $HOME/.config/fish/functions/unset.fish ]; then
		exec $iHAKLAB/.set/to-install/functions
	fi
#Alias
#	if [ ! $(cat $PREFIX/etc/fish/config.fish | grep -oE alias) ]; then
#		echo "source $PREFIX/var/alias" >> $PREFIX/etc/fish/config.fish
#		printf "$Y[!]->$W command server and postgresql was added!!\n"
#	fi
#i-Haklab command
	#UP=$(cat $PREFIX/bin/i-Haklab | grep -m 1 -oE "shodan")
	if [ -e $iHAKLAB/.set/bin/i-Haklab ]; then
		cat $iHAKLAB/.set/bin/i-Haklab > $PREFIX/bin/i-Haklab
	else
		printf "$R[w]-> ERROR :$W Join to https://t.me/Ivam3by_Cinderella"
		exit
	fi
#searchsploit
	if [ ! -d $iHAKLAB/../exploitdb ]; then
		printf "$Y[!]-> Exploitdb tool was added to i-Haklab$W |$Y Install it running$G\n\t]>$W i-Haklab install exploitdb\n"
	fi
#else
	printf "$Y[!]->$W i-Haklab is already the newest version ($NEWver).\n"
#        Install
fi
#			@Ivam3
