#!/data/data/com.termux/files/usr/bin/bash
if [[ $(id -u) -eq 0 ]]
then
  echo -en "\e[31m(_➤)\e[0m You need to be a common user"
  exit 1
else
  [[ -d ${HOME}/.local/bin ]] && {
		echo "Deleting old executable files ..."
	  for link in $(ls ${HOME}/.local/bin/)
	  do
		  [[ -L ${HOME}/.local/bin/$link ]] && {
			  rm -f ${HOME}/.local/bin/$link;
		  }
	  done
  }
	echo "Deleting old version ..."
  [[ -d ${HOME}/.local/share/i-Haklab ]] && rm -rf ${HOME}/.local/share/i-Haklab
  [[ -e ${PREFIX}/etc/bashito ]] && rm -rf ${PREFIX}/etc/bashito
  [[ -e ${PREFIX}/etc/motd ]] && rm -rf ${PREFIX}/etc/motd
  [[ -e ${PREFIX}/etc/motd.dpkg-old ]] && rm -rf ${PREFIX}/etc/motd.dpkg-old
  [[ -d ${PREFIX}/etc/apt/sources.list.d ]] || mkdir -p ${PREFIX}/etc/apt/sources.list.d
	[[ -d ${PRERIX}/.local/share/tools ]] && {
		rm -rf ${HOME}/.local/share/tools;
	} || {
		[[ -d ${HOME}/storage/external-1/tools ]] && {
			rm -rf ${HOME}/storage/external-1/tools;
		}
	}
	[[ -e $HOME/.local/etc/i-Haklab/.Ivam3byCinderella ]] && {
		echo "Keeping previous password ..."
		[[ "Ivam3byCinderella" = $(cat $HOME/.local/etc/i-Haklab/.Ivam3byCinderella|openssl enc -aes-256-cbc -md sha512 -a -d -pbkdf2 -iter 100000 -salt -pass pass:Secret@123#) ]] || {
			cp ${HOME}/.local/etc/i-Haklab/.Ivam3byCinderella ${HOME}/.local/etc/i-Haklab/.IbyC;
		}
	}
	[[ -e ${HOME}/.local/libexec/i-Haklab.login ]] && {
		echo "Keeping previous setting ..."
		cp ${HOME}/.local/libexec/i-Haklab.login ${HOME}/.local/libexec/i-Haklab.login.backup;
	}
  echo "Setting Ivam3 repositories at Advance Package Tool(APT)."
  wget --tries=20 --quiet "https://raw.githubusercontent.com/ivam3/termux-packages/gh-pages/ivam3-termux-packages.list" -O ${PREFIX}/etc/apt/sources.list.d/ivam3-termux-packages.list
  echo "Setting Yisus7u7 repositories at Advance Package Tool(APT)."
  wget --tries=20 --quiet "https://raw.githubusercontent.com/Yisus7u7/termux-desktop-xfce/gh-pages/termux-desktop-xfce.list" -O ${PREFIX}/etc/apt/sources.list.d/termux-desktop-xfce.list
fi
####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
