#!/data/data/com.termux/files/usr/bin/bash
#
# Despues que el paquete esta en el sistema 
#
# TMUX
# -e existe el archivo 
[[ -e ${HOME}/.tmux/.tmux.conf]] && { ln -s -f  ${HOME}/.tmux/.tmux.conf;}

# ZSH (Default shell)
chsh -s zsh


