<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'RelativePath' => $vendorDir . '/grandt/relativepath/RelativePath.php',
    'com\\grandt\\BinString' => $vendorDir . '/grandt/binstring/BinString.php',
    'com\\grandt\\BinStringStatic' => $vendorDir . '/grandt/binstring/BinStringStatic.php',
);
