#!/data/data/com.termux/files/usr/bin/bash
#coded by Ivam3 on june 27 2018.
#
#banner
        echo "#-----THANKS TO MY MASTER CINDERELLA-----#"
	echo "#                                        #"
	echo "#             People don't die           #"
        echo "#    If they still live in the hearts    #"
        echo "#           of their loved ones          #"
        echo "#       We love her ... We miss her      #"
        echo "#                                        #"
        echo "#-------------------RIP------------------#"
        echo

