#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO UNINSTALL AMASS. . . .$i"
        printf "\n\n"
        sleep 1
done
#UNINSTALLATION
for i in github.com/knq github.com/mailru github.com/rakyll github.com/yl2chen github.com/mailru github.com/andybalholm github.com/mattn github.com/gobwas github.com/fatih github.com/PuerkitoBio github.com/VividCortex github.com/beorn7 github.com/cespare github.com/temoto net github.com/dennwc github.com/tylertreat github.com/miekg github.com/boltdb github.com/go-sql-driver github.com/hidal-go go.uber.org github.com/chromedp github.com/yuin github.com/cenkalti github.com/geziyor github.com/google github.com/dghubble github.com/jmoiron golang.org github.com/dghubble github.com/gogo github.com/cloudflare google.golang.org github.com/cjoudrey layeh.com github.com/matttproud github.com/golang github.com/go-kit github.com/prometheus github.com/cayleygraph github.com/geziyor github.com/OWASP; do
	if [ $GOPATH/$i ]
	then
		rm -rf $GOPATH/$i
	fi
done
if [ $GOPATH/bin/amass ]
then
	rm $GOPATH/bin/amass
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#                                               @Ivam3
