#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
apktool=$(find $PREFIX/bin -name "apktool")
function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO UNINSTALL EMBED+JAVA. . . .$i"
        printf "\n\n"
        sleep 1
done
#UNINSTALLATION
if [ -d $HOME/java ]; then
	rm -rf $HOME/java
fi

for i in signapk zzipalign apktool java EMBED glib jdk8 bin; do
	if [ -L $i ] || [ -e $i ]; then
		rm -rf $PREFIX/bin/$i > /dev/null >2&1
	fi
	if [ -d $i ]; then
		rm -rf $PREFIX/share/$i > /dev/null >2&1
	fi
done
yes |pkg remove apksigner aapt && apt auoremove
if [ -e $PREFIX/var/spool/apktool.jar ]; then
	rm -rf $PREFIX/var/spool/apktool.jar > /dev/null >2&1
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot
$W"
#                                               @Ivam3
