#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
version="4.17.32"
function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done
echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO UNINSTALL METASPLOIT FRAMEWORK. . . .$i"
        printf "\n\n"
        sleep 1
done
#UNINSTALLATION
SOversion=$(termux-info |awk '$1 < 11 {print $1}' |tail -n 1 |awk -F "." '{print $1}')
command -v termux-info > /dev/null 2>&1 || pkg install termux-api termux-tools -y > /dev/null 2>&1
if [ $SOversion => '7' ]; then
	pkg remove metasploit -y > /dev/null >2&1
else
	apt remove ruby postgresql -y > /dev/null >2&1
fi

if [ -d $PREFIX/lib/ruby ]; then
	rm -rf $PREFIX/lib/ruby
fi
if [ -d ~/metasploit-framework ]; then
	rm -rf ~/metasploit-framework
fi
if [ -d $PREFIX/opt/metasploit-framework ]; then
	rm -rf $PREFIX/opt/metasploit-framework
fi
find $HOME -name "*$version.tar.gz" -type f -delete
find $HOME -name "metasploit*" -type d -delete
if [ -e $PREFIX/bin/msfconsole ] || [ -L $PREFIX/bin/msfconsole ]; then
	rm $PREFIX/bin/msfconsole
fi
if [ -e $PREFIX/bin/msfvenom ] || [ -L $PREFIX/bin/msfvenom ]; then
	rm $PREFIX/bin/msfvenom
fi
rm -rf $PREFIX/var/lib/postgresql
rm -rf ~/.msf4
apt autoremove

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot
$W"
#                                               @Ivam3
