#!/data/data/com.termux/files/usr/bin/bash
# This file contain all i-Haklab enviroment variables

# Environment Variables
export DISPLAY=:0
export USER=i-Haklab
export GPG_TTY=$(tty)
export GYP_DEFINES="android_ndk_path=''"

# IMPORTANT: .local/bin FIRST to intercept 'apt', 'npm' and 'pnpm' invisible wrappers
export HOME=/data/data/com.termux/files/home
export PATH="$HOME/.local/bin:/data/data/com.termux/files/usr/bin:$HOME/go/bin"
export GOPATH=$HOME/go
export GOROOT=/data/data/com.termux/files/usr/lib/go
export GOCACHE="$HOME/.cache/go"
export GOMODCACHE="$GOPATH/pkg/mod"
export JAVA_HOME=/data/data/com.termux/files/usr/opt/openjdk
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
export LLVM_BUILD=/data/data/com.termux/files/usr/lib
export LLVM_HOME=/data/data/com.termux/files/usr/lib/cmake/llvm
export CFLAGS=" -Wno-incompatible-function-pointer-types"
export CC=clang
export CXX=clang++
export ANDROID_NDK_HOME=/data/data/com.termux/files/usr
export ANDROID_ALLOW_UNDEFINED_SYMBOLS=On
export TOOLS=$HOME/.local/share
export ANDROID_API_LEVEL=24
export VSCODE_EXTENSIONS_DIR=$HOME/.local/share/code-server/extensions

# Aliases
alias la="ls -a"
alias ll="ls -l"
alias du="du -hP"
alias bat="bat -f --theme 'Visual Studio Dark+'"
alias postgresql="pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql"
