#!/usr/bin/bash
# This file contain all i-Haklab enviroment variables
OP1=${2:-crunch}

export version='v.3.5'
export iHETC=/data/data/com.termux/files/home/.local/etc/i-Haklab
export iHLIBEXEC=/data/data/com.termux/files/home/.local/libexec/i-Haklab
export iHDB="https://raw.githubusercontent.com/ivam3/termux-packages/gh-pages/packages/i-Haklab/home"
export JAVADB="https://raw.githubusercontent.com/ivam3/java/master"
export USER=$(grep -n "set USER" ${HOME}/.local/etc/fish/config.fish|awk -F " " '{print $3}')
[[ -e $PREFIX/var/log/i-Haklab.log ]] || touch $PREFIX/var/log/i-Haklab.log
export LOGFILE=$PREFIX/var/log/i-Haklab.log
export TOOLS=$HOME/.local/share
export ARCH=$(dpkg --print-architecture)
export LOCALHOST=$(ifconfig 2>&1|grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'|grep -v 255|tail -n 1)
export LOOPBACK="127.0.0.1"
export LPORT="3030"
export RPORT="80"
export MSFPATH=$PREFIX/opt/metasploit-framework
export phonescanKEY=""
export R='\e[31m'
export G='\e[32m'
export Goke='\033[92m'
export Glig=='\e[1;32m'
export Y='\e[33m'
export B='\e[34m'
export M='\e[35m'
export C='\e[36m'
export W='\e[0m'
export bold='echo -en "\e[1m"'
export underline='echo -en "\e[4m"'
export dim='echo -en "\e[2m"'
export strickthrough='echo -en "\e[9m"'
export blink='echo -en "\e[5m"'
export reverse='echo -en "\e[7m"'
export hidden='echo -en "\e[8m"'
export black='echo -en "\e[30m"'
export gray='echo -en "\e[37m"'
export darkgray='echo -en "\e[90m"'
export lightred='echo -en "\e[91m"'
export lightgreen='echo -en "\e[92m"'
export lightyellow='echo -en "\e[93m"'
export lightblue='echo -en "\e[94m"'
export lightpurple='echo -en "\e[95m"'
export lightaqua='echo -en "\e[96m"'
export white='echo -en "\e[97m"'
export default='echo -en "\e[39m"'
export BLACK='echo -en "\e[40m"'
export RED='echo -en "\e[41m"'
export GREEN='echo -en "\e[42m"'
export ORANGE='echo -en "\e[43m"'
export BLUE='echo -en "\e[44m"'
export PURPLE='echo -en "\e[45m"'
export AQUA='echo -en "\e[46m"'
export GRAY='echo -en "\e[47m"'
export DARKGRAY='echo -en "\e[100m"'
export LIGHTRED='echo -en "\e[101m"'
export LIGHTGREEN='echo -en "\e[102m"'
export LIGHTYELLOW='echo -en "\e[103m"'
export LIGHTBLUE='echo -en "\e[104m"'
export LIGHTPURPLE='echo -en "\e[105m"'
export LIGHTAQUA='echo -en "\e[106m"'
export WHITE='echo -en "\e[107m"'
export DEFAULT='echo -en "\e[49m"'

