#!/data/data/com.termux/files/usr/bin/bash
# This file contain all i-Haklab enviroment variables
OP1="${2:-crunch}"
if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
        export iHAKLAB=/data/data/com.termux/files/home/i-Haklab
else
        export iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

export TOOL=$(ls $iHAKLAB/.set/to-install/ | grep -iv .zip | grep -iv instasudo | grep -iv QG | grep -iv i-Haklab_login | grep -iv check-root | grep -iv functions | grep -n -iv lock)

export TARGET=(0 1 2 3 29)

export SSH=$(netstat | grep -c "ssh")

export LOCALHOST=$(ifconfig wlan0 | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v 255)

export CHECKROOT=$(bash $iHAKLAB/.set/to-install/check-root)

export README_TOOL=$(ls $iHAKLAB/.set/libexec/Readme/ | grep $2)
