#!/data/data/com.termux/files/usr/bin/bash
## This file export the variables for i-Haklab in termux.
# you can add more as you can
#
set LOCALHOST 'ifconfig wlan0 | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v 255'
#			@Ivam3
