#!/usr/bin/bash
# This file contain all i-Haklab enviroment variables
OP1=${2:-crunch}

export iHAKLAB=/data/data/com.termux/files/home/.local/share/i-Haklab

[[ -e $HOME/.local/var/log/i-Haklab.log ]] || touch $HOME/.local/var/log/i-Haklab.log
export LOGFILE=$HOME/.local/var/log/i-Haklab.log

microSD=$(df|tail -n 2|awk -F " " '{print $6}'|grep -iv "emulated"|head -n 1)
if [ -d $microSD/Android/data/com.termux/files ] && [ -w $microSD/Android/data/com.termux/files ]; then
	if [ ! -d $microSD/Android/data/com.termux/files/tools ];then
		mkdir $microSD/Android/data/com.termux/files/tools
	fi
	export TOOLS=$microSD/Android/data/com.termux/files/tools
elif [ -d /data/data/com.termux/files/home/.local/share/tools ];then
	export TOOLS=/data/data/com.termux/files/home/.local/share/tools
else
	mkdir -p /data/data/com.termux/files/home/.local/share/tools
	export TOOLS=/data/data/com.termux/files/home/.local/share/tools
fi

export version='v.3.0'
export R='\033[1;31m'
export G='\033[1;32m'
export Goke='\033[92m'
export Glig=='\e[1;32m'
export Y='\033[1;33m'
export B='\033[1;34m'
export M='\033[1;35m'
export C='\033[1;36m'
export W='\033[0m'
export bold=`echo -en "\e[1m"`
export underline=`echo -en "\e[4m"`
export dim=`echo -en "\e[2m"`
export strickthrough=`echo -en "\e[9m"`
export blink=`echo -en "\e[5m"`
export reverse=`echo -en "\e[7m"`
export hidden=`echo -en "\e[8m"`
export normal=`echo -en "\e[0m"`
export black=`echo -en "\e[30m"`
export red=`echo -en "\e[31m"`
export green=`echo -en "\e[32m"`
export orange=`echo -en "\e[33m"`
export blue=`echo -en "\e[34m"`
export purple=`echo -en "\e[35m"`
export aqua=`echo -en "\e[36m"`
export gray=`echo -en "\e[37m"`
export darkgray=`echo -en "\e[90m"`
export lightred=`echo -en "\e[91m"`
export lightgreen=`echo -en "\e[92m"`
export lightyellow=`echo -en "\e[93m"`
export lightblue=`echo -en "\e[94m"`
export lightpurple=`echo -en "\e[95m"`
export lightaqua=`echo -en "\e[96m"`
export white=`echo -en "\e[97m"`
export default=`echo -en "\e[39m"`
export BLACK=`echo -en "\e[40m"`
export RED=`echo -en "\e[41m"`
export GREEN=`echo -en "\e[42m"`
export ORANGE=`echo -en "\e[43m"`
export BLUE=`echo -en "\e[44m"`
export PURPLE=`echo -en "\e[45m"`
export AQUA=`echo -en "\e[46m"`
export GRAY=`echo -en "\e[47m"`
export DARKGRAY=`echo -en "\e[100m"`
export LIGHTRED=`echo -en "\e[101m"`
export LIGHTGREEN=`echo -en "\e[102m"`
export LIGHTYELLOW=`echo -en "\e[103m"`
export LIGHTBLUE=`echo -en "\e[104m"`
export LIGHTPURPLE=`echo -en "\e[105m"`
export LIGHTAQUA=`echo -en "\e[106m"`
export WHITE=`echo -en "\e[107m"`
export DEFAULT=`echo -en "\e[49m"`
export ARCH=$(dpkg --print-architecture)
export iHDB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set"
export JAVADB="https://raw.githubusercontent.com/ivam3/java/master"
export LOCALHOST=$(ifconfig 2>&1|grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'|grep -v 255|tail -n 1)
export LPORT="4546"
export MSFPATH=$PREFIX/opt/metasploit-framework
export README_TOOL=$(ls $iHAKLAB/.set/libexec/Tools/Readme/ | grep $OP1 2>/dev/null)
export RPORT="80"
export SSH=$(netstat | grep -c "ssh")
export TARGET=(0 1 2 3 29)
export UNAME=$(uname -m)
export phonescanKEY=""
