#!/data/data/com.termux/files/usr/bin/bash
#CREADED ON Dec/2018 BY @IVAM3
#UPGRADED ON 2022/Mar/31
trap ctrl_c 2
ctrl_c(){ printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}
StdErr(){ printf "$R(_➤)$W missing argument, type fixer -h for help\n";exit;}

#:: VARIABLES ::#
IFS=$'\n\t'
iHDB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home"
[[ -d $HOME/.local/bin ]] && binPATH="$HOME/.local/bin" || binPATH="$PREFIX/bin"
G=`echo -en "\e[32m"`
R='\e[31m'
Y='\e[33m'
B='\e[34m'
M='\e[35m'
C='\e[36m'
W='\e[0m'

#:: BANNERS ::#
Chao-chao(){ printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n";}

running(){
	[[ $1 = "time" ]] && {
		sleep $2 &
		n=$(echo $!);
  }
  [[ $1 = "ps" ]] && {
		n=$2;
  }
  pid=$n
  spinner=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )
  while [ "$(ps a|awk '{print $1}'|grep $pid)" ]
	do
		for i in "${spinner[@]}"
		do
			tput civis
			printf  "$G\r(➤_) Running\t$i\b\b\b\b\b\b\b\b";
    done
  done
  tput cnorm
  printf "\t$W[$G¡DONE!$W]\n";
}

Banner(){
	if [[ ! -e $PREFIX/bin/lolcat ]]
	then
		yes|apt install ruby >/dev/null 2>/dev/null
    gem install lolcat >/dev/null 2>/dev/null
  fi
	printf " ___ _            ____     __ _\n|_ _| |__  _   _ / ___|   / _(_)_  _____ _ __\n | || '_ \| | | | |   ___| |_| \ \/ / _ \ '__|\n | || |_) | |_| | |__|___|  _| |>  <  __/ |\n|___|_.__/ \__, |\____|  |_| |_/_/\_\___|_|\n for Termux|___/by @Ivam3byCinderella\n\n"
}

usage() {
	printf "$B\n(USAGE)─➤$G IbyC-fixer <[apt|nrauf|localtunnel|metasploit|downgradeRepo|RuGiR]> <option>$W\n\napt\t\t\t\tSearch and fix some errores on APT/PKG with dpkg\nnrauf         dir/to/app\tTo remapping unicode filenames to ascii when produced by apktool\nlocaltunnel\t\t\tfix error 'Unsupported platform: android'\nmetasploit\t\t\tAlternative metasploit installation\ndowngradeRepo repo=version\tDowngrade apt|pkg reporitory tospecific version\nRuGiR\t\t\t\tFix ruby gems issues\nPyMiR\t\t\t\tFix python module issues\nngrok\t\t\t\tInstall ngrok-server from Abhacker repositories\n\nExamples:\n\tIbyC-fixer RuGiR\n\tIbyC-fixer downgradeRepo ruby=2.7.2\n\tIbyC-fixer nrauf \$HOME/original\n\nFor more help join to$B https://t.me/Ivam3_Bot$W\n\n"
	exit
}

clear;Banner|lolcat
[[ $# -eq 0 ]] && StdErr || arg=($@)
case ${arg[0]} in
	nrauf)
		[[ -z ${arg[1]} ]] && StdErr
		bash <(curl -fsSL "$iHDB/.local/libexec/nrauf") ${arg[2]}
		;;

	apt)
		file=$(mktemp)
		yes|apt update > $file
		yes|apt upgrade >> $file
		apt clean && apt autoremove
		[[ $(grep -oE "E: Sub-process" $file) ]] && dpkg --configure -a
		[[ $(grep -oE "E: Failed to fetch" $file) ]] || [[ $(grep -oE "E: Unmet" $file) ]] || [[ $(grep -oE "Broken pipe" $file) ]] && apt --fix-broken install
		[[ $(grep -oE "E: Unable to fetch" $file) ]] && apt update --fix-missing
		[[ $(grep -oE "is not signed" $file) ]] || [[ $(grep -oE "NO_PUBKEY" $file) ]] && echo "deb https://packages-cf.termux.org/apt/termux-main/ stable main" > $PREFIX/etc/apt/sources.list;rm -rf $PREFIX/etc/apt/sources.list.d/*;dpkg --configure -a
		rm $file
		;;
	localtunnel)
		[[ $(command -v wget) ]] >/dev/null || {
			echo -en "$G(➤_)$W Installing dependencies ...\n"
			yes|apt install wget >/dev/null 2>/dev/null &
			ps=$(echo $!);
			running ps $ps
		}
		echo -en "$G(➤_)$W Fixing ...\n"
		wget --tries=20 --quiet $iHDB/.local/etc/localtunnel/openurl.js -O ${PREFIX}/lib/node_modules/localtunnel/node_modules/openurl/openurl.js &
		ps=$(echo $!)
		running ps $ps
		;;

	metasploit)
		[[ -d $PREFIX/var/lib/postgresql ]] && rm -rf $PREFIX/var/lib/postgresql
		bash <(curl -fsSL "http://git.io/abhacker-repo") --install ruby=2.7.2 -r apt install metasploit -y
		yes|apt autoremove
		;;
	PyMiR) bash <(curl -fsSL "${iHDB}/.local/libexec/PyMiR") ${@:2};;
	RuGiR) bash <(curl -fsSL "${iHDB}/.local/libexec/RuGiR") ${@:2};;
	downgradeRepo)
		[[ -z ${arg[1]} ]] && StdErr
		bash <(curl -fsSL "http://git.io/abhacker-repo") --install ${@:2}
		;;
	ngrok)
		printf "$G(_➤)$W Installing Ngrok from Abhacker repositories ...\n"
		bash <(curl -fsSL "http://git.io/abhacker-repo") --install ngrok-server
		printf "$G(_➤)$W Installing official Ngrok executable...\n"
		[[ $(command -v ngrok) ]] && rm -rf $(command -v ngrok)
		arch1=$(uname -a|grep -o 'arm'|head -n1)
    arch2=$(uname -a|grep -o 'Android'|head -n1)
    [[ $arch1 = 'arm' ]] || [[ $arch2 = 'Android' ]] && arch=arm || arch=386
    wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-$arch.zip -O $TMPDIR/ngrok-stable-linux-$arch.zip
    if [[ -e $TMPDIR/ngrok-stable-linux-$arch.zip ]]; then
			[[ -d $HOME/.ngrok2 ]] || mkdir -p $HOME/.ngrok2
      unzip -q $TMPDIR/ngrok-stable-linux-$arch.zip -d $HOME/.ngrok2/
      rm -rf $TMPDIR/ngrok-stable-linux-$arch.zip
      printf "#!/bin/bash\n#THIS SCRIPT EXECUTE NGROK TO AVOID 'bad address' ERROR\nexec termux-chroot $HOME/.ngrok2/ngrok \${@:1}\n#     i-Haklab by Ivam3" > $binPATH/ngrok.io
      chmod +x $HOME/.ngrok2/ngrok $binPATH/ngrok.io
			echo -en $Y"WARNING:$W Now you have 2 ngrok executables 'ngrok' and 'ngrok.io'\n"
			echo -en "$G[DONE!!]$W\n"
		else
			StdErr
		fi
		;;
	-h|--help) usage;;
	*) StdErr;;
esac

#                                               @Ivam3
