#!/bin/bash
#This file is part of i-Haklab command

if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
else
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

source $iHAKLAB/.set/libexec/colors
source $iHAKLAB/.set/var/variables
source $iHAKLAB/.set/functions/functions


if [ $SSH = "1" ]; then
	killall -2 ssh > /dev/null 2>&1
fi

if [ ! -d $HOME/localtunnel-server ]; then
	printf "$R\n[w]-> ERROR :$W Localtunnel-server is not installed\n"
else
	if [ $1 -gt 1000 ]; then
		LPORT=$1
        else
                LPORT=4546
                printf "$R\n[w]-> ERROR :$W Invalid port"
                sleep 1
                printf "$Y\n[!] using default$W : $LPORT\n"
        fi
	chk-tunnel
        $(which lt) -h "http://$TUNNEL" -p $LPORT --print-requests
fi
