#!/usr/bin/bash
#This file is part of i-Haklab command
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions

if [ $SSH = "1" ]; then
	killall -2 ssh > /dev/null 2>&1
fi
[[ $(command -v lt) ]] || { printf >&2 "$R\n(_➤) ERROR :$W Localtunnel-server is not installed\n";exit;}
default(){ config;$(command -v lt) -h "http://$TUNNEL" -p $LPORT --print-requests;}
subdomain(){ config;$(command -v lt) -h "http://$TUNNEL" -p $LPORT -s $SUBDOMAIN --print-requests;}
config(){ printf "$Y\n(_>)_USAGE─➤$W i-Haklab forwarding <port/domain>$G\n(_>)_PORT─➤$W $LPORT$G\n(_>)_DOMAIN─➤$W $SUBDOMAIN$G\n(_➤)$W ";}
chk-tunnel
if [ "$2" -eq "$2" ] 2>/dev/null && [ $3 ]
then
	LPORT="${2:-${LPORT}}"
	SUBDOMAIN=$3
	subdomain
elif [ $2 -a "$3" -eq "$3" ] 2>/dev/null
then
	LPORT="${3:-${LPORT}}"
	SUBDOMAIN=$2
	subdomain
elif [[ $2 != ?(-)+([:digit:]) ]] 2>/dev/null
then
	SUBDOMAIN=$2
	subdomain
else
	LPORT="${2:-${LPORT}}"
	SUBDOMAIN=none
	default
fi
