#!/usr/bin/bash
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
PS3="$G(_>)_number:─➤ "
TMP_PATH=$PREFIX/bin
chck-game() { command -v $GAME >/dev/null || pkg install $GAME -y;}
printf "$Y(_➤)$W choose a game from the list below"
select GAME in $(apt list|grep gam|grep -iv game-repo|awk -F "/" '{print $1}') Exit;do
	chck-game
	if [ $REPLAY != $REPLAY ];then
		printf "$R(_➤)$W type a number\n"
	elif [[ $GAME = Exit ]];then
		exit
	elif [[ $GAME = cavez-of-phear ]];then
		exec $TMP_PATH/phear
	elif [[ $GAME = open-adventure ]];then
		exec $TMP_PATH/advent
	elif [[ $GAME = pacman4console ]]; then
		exec $TMP_PATH/pacman
	elif [[ $GANE = tty-solitaire ]]; then
		exec $TMP_PATH/ttysolitaire
	elif [[ $GAME = vitetris ]]; then
		exec $TMP_PATH/tetris
	else
		exec $TMP_PATH/$GAME ${@:1}
	fi
done
