#!/data/data/com.termux/files/usr/bin/bash
#Created on July/2021
IFS=$'\n\t'
trap ctrl_c 2
zzz=$(sleep 0.5)
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
toInstall="$1"
ctrl_c(){ printf "\n$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n";}
Err() { printf "$R\n(_➤)$W Installation failed";ctrl_c;exit;}
PS(){ printf "$G(_➤)$W Installing python modules.\n ╰─────➤$W (it could take a while)...\n";}
PIPup() {
	for PYv in python python2;do
		yes|apt install $PYv >/dev/null 2>>$LOGFILE
		$PYv -m pip --no-color --quiet --no-cache-dir install --upgrade pip 2>>$LOGFILE
	done
}
PYmodules(){
	python$PYv -m pip --no-color --quiet --no-cache-dir install -r $TMPDIR/requirements.txt 2>>$LOGFILE
}
goEnv() {
	yes|apt install golang
	[[ -d ~/go/pkg/mod/github.com ]] || mkdir -p $HOME/go/pkg/mod/github.com
	[[ -d $PREFIX/lib/go/src ]] || mkdir -p $PREFIX/lib/go/src

	if ! $(grep -oE "GOPATH" $INITFILE);then
		sed -i "21a set GOPATH $HOME/go" $INITFILE
	fi
	if ! $(grep -oE "GOROOT" $INITFILE); then
		sed -i "22a set GOROOT $PREFIX/lib/go" $INITFILE
	fi
}
SearchTool(){
	if [[ -d $TOOLS/$toInstall ]] || [[ -e $PREFIX/bin/$toInstall ]] || [[ -e $HOME/.local/bin/$toInstall ]] || [[ -d $PREFIX/opt/$toInstall ]] || [[ -e ~/go/bin/$toInstall ]] || [[ ! -z $login ]];then
		printf "$R(_➤)$W $1 it's already installed\n";exit
	else
		running 3
		yes|apt autoremove
		APTupdate
	fi
}

if [[ $SHELL = $PREFIX/bin/fish ]];then
	INITFILE="$PREFIX/etc/fish/config.fish"
else
	INITFILE="$PREFIX/etc/bash.bashrc"
fi

case "$toInstall" in
	dex2jar)
		SearchTool
		link="https://github.com/pxb1988/dex2jar/releases/download"
		releases="v2.2-SNAPSHOT-2021-10-31"
		zipFile="dex-tools-2.2-SNAPSHOT-2021-10-31.zip"
		yes|apt install wget unzip openjdk-17
		wget --quiet --tries=20 $iHDB/bin/$toInstall -O $HOME/.local/bin/$toInstall
		wget --quiet --tries=20 $link/$releases/$zipFile -O $TMPDIR/$toInstall.zip
		unzip $TMPDIR/$toInstall.zip -d $TOOLS
		d2jDIR=$(ls $TOOLS|grep dex-tools)
		mv $TOOLS/$d2jDIR $TOOLS/$toInstall
		rm -rf $TMPDIR/$toInstall.zip
		;;
	kalilinux)
		SearchTool
		yes|pkg install wget curl proot tar && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Kali/kali-xfce.sh -O kali-xfce.sh && chmod +x kali-xfce.sh && bash kali-xfce.sh 
		cat <<- CONF > ~/kali-fs/etc/apt/sources.list
		deb [trusted=yes]  http://http.kali.org/kali kali-rolling main contrib non-free
		#deb http://ftp.debian.org/debian buster main
		#deb http://ftp.debian.org/debian buster-updates main
		CONF
		printf "$G(_➤)$W Follow the the next steps$G\t
		(01)─➤$W run $toInstall < ./start-kali.sh >$G\t
		(02)─➤$W update $toInstall < apt-get update && apt-get upgrade >$G\t
		(03)─➤$W start vnc server < vncserver :1 > on this step you have to set a password$G\t
		(04)─➤$W download vnc viewer app from https://bit.ly/2VUguQM$G\t
		(05)─➤$W open the app, touch the plus(+) bottom and set a new connection with address as localhost:1 and name as Kali Linux$G\t
		(06)─➤$W type your password and enjoy it!!\n"
		;;
		#::PYTHON3::#

	binwalk)
		SearchTool
		yes|apt install git
		PIPup
		git clone --quiet https://github.com/ReFirmLabs/$toInstall $TOOLS/$toInstall
		cd $TOOLS/$toInstall
		chmod 750 *
		python setup.py install
		;;

	evilurl)
		SearchTool
		yes|apt install git
		PIPup
		PYv=""
		git clone --quiet https://github.com/UndeadSec/EvilURL $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		printf "python-nmap\npython-whois" > $TMPDIR/requirements.txt
		PYmodules
		rm -rf $TMPDIR/requirements.txt
		;;
	fuzzdb|wfuzz)
		[[ $toInstall = wfuzz ]] && toInstall="fuzzdb"
		SearchTool
		yes|apt install git wget
		PIPup
		PYv=""
		git clone --quiet https://github.com/fuzzdb-project/$toInstall --depth 1 $TOOLS/$toInstall
		wget -q $iHDB/wordlist/$toInstall/big.txt -O $TOOLS/$toInstall/wordlists-user-passwd/big.txt
		wget -q $iHDB/wordlist/$toInstall/common.txt -O $TOOLS/$toInstall/wordlists-misc/common.txt
		chmod +x -R $TOOLS/$toInstall
		printf "wfuzz" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	getnpusers)
		SearchTool
		yes|apt install git wget python rust
		PIPup
		Pyv=""
		wget -q https://raw.githubusercontent.com/SecureAuthCorp/impacket/master/examples/GetNPUsers.py -O $HOME/.local/bin/$toInstall
		printf "urllib3\nrequests\nmock\nidna\nbiopython\nrust\nimpacket" > $TMPDIR/requirements.txt
		PYmodules
		chmod 711 $HOME/.local/bin/$toInstall
		rm -f $TMPDIR/requirements.txt
		yes|apt remove rust;apt autoremove
		;;
	ghost)
		SearchTool
		yes|apt install python openssl git
		git clone --quiet https://github.com/EntySec/ghost $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		;;
	hakku)
		SearchTool
		yes|apt install git python
		git clone --quiet https://github.com/4shadoww/hakkuframework $TOOLS/$toInstall
		chmod 750 $TOOLS/$toInstall/$toInstall
		;;
	hunner)
		SearchTool
		yes|apt install git python
		PIPup
		PYv=""
		git clone --quiet https://github.com/b3-v3r/Hunner $TOOL/$toInstall
		chmod 750 -R $TOOLS/$toInstall
		printf "httplib2" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	infoga)
		SearchTool
		yes|apt install python git
		PIPup
		PYv=""
		git clone --quiet https://github.com/m4ll0k/$toInstall $TOOLS/$toInstall
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	ipgeolocation)
		SearchTool
		yes|apt install git
		PIPup
		PYv=""
		git clone --quiet https://github.com/maldevel/IPGeoLocation $TOOLS/$toInstall
		printf "termcolor\ncolorama" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	osintgram)
		SearchTool
		yes|apt install git
		PIPup
		Pyv=""
		git clone --quiet https://github.com/datalux/Osintgram $TOOLS/$toInstall
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		PS3="(_➤) "
		printf "$Y(_➤)$W $toInstall needs an instagram acccount credentials."
		select way in Set_credentials Skip_this_step;do
			case $way in
				Set_credentials)
					while read -p "(_>)_username─➤ " username && [ -z $username ];do
						continue
					done
					while read -p "(_>)_passwd─➤ " passwd && [ -z $passwd ];do
						continue
					done
					printf "[Credentials]\nusername = $username\npassword = $passwd" > $TOOLS/$toInstall/config/credentials.ini
					;;
				*)
					printf "$Y(_➤)$W Don't forget set your credentials at file: $TOOLS/$toInstall/config/credentials.ini"
					ctrl_c;exit
					;;
			esac
		done
		;;
	phomber)
		SearchTool
		yes|apt install git
		PIPup
		PYv=""
		git clone --quiet https://github.com/s41r4j/phomber $TOOLS/$toInstall
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		PS3="(_➤) "
		printf "$Y(_➤)$W $toInstall needs an API key from opencagedata.com."
		select way in Set_credentials Skip_this_step;do
			case $way in
				Set_credentials)
					while read -p "(_>)_username─➤ " username && [ -z $username ];do
						continue
					done
					while read -p "(_>)_passwd─➤ " passwd && [ -z $passwd ];do
						continue
					done
					printf "[Credentials]\nusername = $username\npassword = $passwd" > $TOOLS/$toInstall/config/credentials.ini;break
					;;
				*)
					printf "$Y(_➤)$W Don't forget set your credentials at file: $TOOLS/$toInstall/config/credentials.ini"
					ctrl_c;break
					;;
			esac
		done
		;;
	NULL-phoneinfoga-NULL)
		SearchTool
		yes|apt install python git wget unstable-repo geckodriver
		PIPup
		PYv=""
		git clone --quiet https://github.com/sundowndev/PhoneInfoga $TOOLS/$toInstall
		wget -q $iHDB/fix-tools/$toInstall.py -O $TOOLS/$toInstall/$toInstall.py
		cp $TOOLS/$toInstall/config.example.py $TOOLS/$toInstall/config.py
		if [ "$(uname -m)" = 'aarch64' ] || [ "$(uname -m)" = 'x86_64' ];then
			bits=64
		else
			bits=32
		fi
		if ! $(command -v geckodriver);then
			wget -q https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux$bits.tar.gz -O $TMPDIR/geckodriver-v0.29.1-linux$bits.tar.gz
			tar -xvzf $TMPDIR/geckodriver-v0.29.1-linux$bits.tar.gz -C $TMPDIR > /dev/null 2>&1
			rm $TMPDIR/geckodriver-v0.29.1-linux$bits.tar.gz
			mv $TMPDIR/geckodriver $HOME/.local/bin/
			chmod +x $HOME/.local/bin/geckodriver
		fi
		printf "phonenumbers\nselenium\nbs4\ngoogle_api\nconfig\nhtml5lib\ngeckodriver-autoinstaller" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	phonesploit)
		SearchTool
		command -v adb > /dev/null 2>&1 || exec i-Haklab install abdfastboot
		yes|apt install git python
		PIPup
		PYv=""
		git clone --quiet https://github.com/aerosol-can/PhoneSploit $TOOLS/$toInstall
		printf "colorama" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	quack)
		SearchTool
		yes|apt install wget python
		PIPup
		PYv=""
		wget -q https://raw.githubusercontent.com/Monkey-hk4/quack/main/quack -O $HOME/.local/bin/quack
		chmod +x $HOME/.local/bin/quack
		printf "install\nsetuptools\nphonenumbers\nrequests\nscapy\nwget\nargparse" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	recon-ng)
		SearchTool
		yes|apt install git python libxml2 libxml2-static libxml2-utils libxslt libxslt-static
		PIPup
		PYv=""
		git clone --quiet https://github.com/lanmaster53/$toInstall $TOOLS/$toInstall
		chmod 750 -R $TOOLS/$toInstall
		printf "PYyaml\nshodan\ndicttoxml\ndnspython\njsonrpclib\nlxml\nmechanize\nslowaes\nXlsxWriter\nolefile\nPyPDF2\nflask\nunicodecsv" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	routersploit)
		SearchTool
		apt install git python
		PIPup
		PYv=""
		git clone --quiet https://github.com/threat9/$toInstall $TOOLS/$toInstall
		chmod 750 -R $TOOLS/$toInstall
		printf "future\nrequests\npysnmp\npycrypto\ncryptography\nparamiko\nbcrypt\npynacl" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;

	seeker)
		SearchTool
		[[ -e $HOME/.local/bin/ngrok.io ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;}
		yes|apt install git python
		PIPup
		PYv=""
		git clone --quiet https://github.com/thewhiteh4t/$toInstall $TOOLS/$toInstall
		mkdir -p $TOOLS/$toInstall/Ngrok
		cp ~/.ngrok2/ngrok $TOOLS/$toInstall/Ngrok/
		chmod 750 -R $TOOLS/$toInstall/*
		printf "requests\npackaging" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	shellsploit)
		SearchTool
		yes|apt install git python
		PIPup
		PYv=""
		git clone --quiet https://github.com/vasco2016/$toInstall-framework $TOOLS/$toInstall
		chmod 711 -R $TOOLS/$toInstall
		printf "capstone\nreadline\npefile\ncolorama\npylzma" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	sherlock)
		SearchTool
		yes|apt install git python
		PIPup
		PY=""
		git clone --quiet https://github.com/$toInstall-project/$toInstall $TOOL/$toInstall
		chmod 750 -R $TOOLS/$toInstall
		printf "beautifulsoup\nbs\ncertifi\ncolorama\nlxml\nPySocks\nrequests\nrequests-futures\nsoupsieve\nstem\ntorrequest" >> $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	sublist3r)
		SearchTool
		yes|apt install python git
		PIPup
		PYv=""
		git clone --quiet https://github.com/aboul3la/Sublist3r $TOO
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;

	NULL-theharvester-NULL)
		SearchTool
		yes|apt install git python libxml2 libxml2-static libxml2-utils libxslt libxslt-static rust
		PIPup
		PYv=""
		git clone --quiet https://github.com/laramies/theHarvester $TOOLS/$toInstall
		cat $TOOLS/$toInstall/requirements/dev.txt > $TMPDIR/requirements.txt
		sed -i 's|/etc/theHarvester|/data/data/com.termux/files/usr/etc/theHarvester|g' setup.py
		python setup.py install
		PYmodules
		rm -f $TMPDIR/requirements.txt
		yes|apt remove rust && apt autoremove
		;;
	trape)
		SearchTool
		yes|apt install git python
		PIPup
		Pyv=""
		git clone --quiet https://github.com/jofpin/$toinstall $TOOLS/$toInstall
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -rf $TMPDIR/requirements.txt
		;;
	vulnx)
		SearchTool
		yes|apt install git python
		PIPup
		PYv=""
		git clone --quiet https://github.com/anouarbensaad/$toInstall $TOOLS/$toInstall
		rm $TOOLS/$toInstall/install.sh
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -rf $TMPDIR/requirements.txt
		;;
	#::PYTHON2::#
	a2sv)
	  SearchTool
		yes|apt install git python2 openssl
		PIPup
		Pyv="2"
		git clone --quiet https://github.com/hahwul/$toInstall $TOOLS/$toInstall
		chmod +x $TOOLS/$toInstall/*
		printf "argparse\nnetaddr" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	adminpanel)
		SearchTool
		yes|apt install git python2
		git clone --quiet https://github.com/Techzindia/admin_penal $TOOLS/$toInstall
		chmod 750 $TOOLS/$toInstall/admin_panel_finder.py
		mv $TOOLS/$toInstall/admin_panel_finder.py $TOOLS/$toInstall/$toInstall.py
		;;
	androbugs)
		SearchTool
		yes|apt install git python2
		git clone --quiet https://github.com/AndroBugs/AndroBugs_Framework $TOOLS/$toInstall
		;;
	blackbox)
		SearchTool
		yes|apt install wget python2
		PIPup
		PYv="2"
		wget --tries=20 --quiet $iHDB/bin/blackbox -O $HOME/.local/bin/blackbox
		chmod +x $HOME/.local/bin/blackbox
		printf "requests\npasslib\npexpect" > $TMPDIR/requirements.txt
		PYmodules
		rm -rf $TMPDIR/requirements.txt
		;;
	d-tect)
		SearchTool
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/shawarkhanethicalhacker/D-TECT-1 $TOOLS/$toInstall
		chmod +x -R $TOOLS/$1/*
		printf "colorama\nbeautifulsoup" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	cc-genpro)
		SearchTool
		yes|apt install git python2 neofetch
		git clone --quiet https://github.com/HackeRStrategy/cc-genpro1.2 $TOOLS/$toInstall
		chmod 750 $TOOLS/$toInstall/*
		;;
	cloudbunny)
		SearchTool
		yes|apt install python2 git
		PIPup
		PYv="2"
		git clone --quiet https://github.com/Warflop/CloudBunny $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		printf "certificates" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	credmap)
		SearchTool
		yes|apt install python2 git
		PIPup
		PYv="2"
		git clone --quiet https://github.com/lightos/$toInstall $TOOLS/$toInstall
		chmod 750 $TOOLS/$toInstall/$toInstall.py
		printf "urllib2" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	cryptovenom)
		SearchTool
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/lockedbyte/$toInstall $TOOLS/$toInstall
		cp $TOOLS/$toInstall/aux/$toInstall.py $TOOLS/$toInstall
		chmod 711 -R $TOOLS/$toInstall
		printf "base58\nscrypt\npyblake2\npycrypto\ncrypto\nbcrypt\nrc2\ntwofish\ngeesefly\nskein pycipher\nnumpy\nCrypto\npasslib\nbase91\nmom\ngmpy2\nmore_itertools\nargon2_cffi" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	fbi)
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/xHak9x/$toInstall $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		printf "requests" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	hasher)
		SearchTool
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/CiKu370/$toInstall $TOOLS/$toInstall
		printf "progressbar\npasslib" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	kerbrute)
		SearchTool
		yes|apt install git python2 rust
		PIPup
		PYv="2"
		git clone --quiet https://github.com/TarlogicSecurity/kerbrute $TOOLS/$toInstall
		chmod 750 -R $TOOLS/$toInstall
		printf "impacket" > $TMPDIR/requirements.txt
		PYmodules
		yes|apt remove rust;apt autoremove
		rm -f $TMPDIR/requirements.txt
		;;
	pybelt)
		SearchTool
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/Ekultek/Pybelt $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		sed 's|beautifulsoup4==4.5.3|beautifulsoup4==4.7.1|g' -i requirements.txt
		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	recondog)
		SearchTool
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/s0md3v/ReconDog $TOOLS/$toInstall
		chmod 750 -R $TOOLS/$toInstall
		printf "requests\ntld" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	sqliv)
		SearchTool
		yes|apt install python2 wget unzip libxml2 libxml2-static libxml2-utils libxslt libxslt-static
		PIPup
		PYv="2"
		wget -q $iHDB/to-install/$toInstall.zip
		unzip -q $toInstall.zip -d $TOOLS
		rm $toInstall.zip
		chmod 750 -R $TOOLS/$toInstall
		printf "terminaltables\ntermcolor\nnyawc" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		;;
	websploit)
		SearchTool
		yes|apt install git python2
		PIPup
		PYv="2"
		git clone --quiet https://github.com/The404Hacking/$toInstall $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		printf "numpy\n" > $TMPDIR/requirements.txt
		PYmodules
		rm -rf $TMPDIR/requirements.txt
		;;#::BASH::#

	exploitdb)
		SearchTool
		yes|apt install git wget
		git clone --quiet https://github.com/offensive-security/$toInstall $TOOLS/$toInstall
		chmod +x $TOOLS/$toInstall/*
		wget -q $iHDB/fix-tools/searchsploit -O ~/.searchsploit_rc
		;;
	lockphish)
		SearchTool
		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;}
		yes|apt install git wget
		git clone --quiet https://github.com/JasonJerry/$toInstall $TMPDIR/$toInstall
		cp -r $TMPDIR/$toInstall $TOOLS/$toInstall
		if [[ ! -d $TOOLS/$toInstall ]]
		then
			rm -rf $TMPDIR/$toInstall 2>/dev/null
			printf >&2 "$R\n(_➤) ERROR :$W lockphish directory missing\n"
			ctrl_c
		fi
		rm -rf $TOOLS/$toInstall/$toInstall.sh $TMPDIR/$toInstall
		wget -q $iHDB/fix-tools/$toInstall -O $TOOLS/$toInstall/$toInstall
		chmod 711 $TOOLS/$toInstall/*
		;;

	nexphisher)
		SearchTool
		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;exit;}
		yes|apt install git
		git clone --quiet https://github.com/htr-tech/$toInstall $TOOLS/$toInstall
		chmod +x $TOOLS/$toInstall/*
		cd $TOOLS/$toInstall
		bash tmux_setup
		mkdir $TOOLS/$toInstall/.htr
		ln -s ${HOME}/.local/bin/ngrok.io $TOOLS/$toInstall/.htr/ngrok 2>$LOGFILE
		wget -q $iHDB/fix-tools/$toInstall -O $TOOLS/$toInstall/$toInstall
		;;
	saycheese|sayhello)
		SearchTool
		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;}
		yes|apt install wget unzip openssh
		wget -q $iHDB/to-install/$toInstall.zip -O $TMPDIR/$toInstall.zip
		unzip -q $TMPDIR/$toInstall.zip -d $TOOLS
		rm -rf $TMPDIR/$toInstall.zip
		wget -q $iHDB/fix-tools/$toInstall -O $TOOLS/$toInstall/$toInstall
		chmod +x $TOOLS/$toInstall/*
		;;
	userrecon)
		SearchTool
		yes|apt install git
		git clone --quiet https://github.com/issamelferkh/userrecon $TOOLS/$toInstall
		mv $TOOLS/$toInstall/$toInstall.sh $TOOLS/$toInstall/$toInstall
		chmod 750 $TOOLS/$toInstall/$toInstall
		;;
	wbruter)
		SearchTool
		yes|apt install git
		git clone --quiet https://github.com/wuseman/WBRUTER $TOOLS/$toInstall
		chmod +750 -R $TOOLS/$toInstall
		;;

	#::BIN::#
	adbfastboot)
		for BIN in adb adb.bin fastboot fastboot-armeabi;do
			wget -q $iHDB/bin/$BIN -O $HOME/.local/bin/$BIN
			chmod +x $HOME/.local/bin/$BIN
		done
		if [[ ! -d $HOME/adbfiles ]];then
			mkdir $HOME/adbfiles
		fi
		;;
	burpsuite)
		SearchTool
		printf "$G\n(_➤) Installing $toInstall (It could take a while)...\n";sleep 5
		yes|apt install openjdk-17 wget
#		wget -q --tries=20 https://github.com/termux/termux-packages/suites/4742204683/artifacts/131051875 -O $TMPDIR/termux-packages-aarch64.zip
#		unzip $TMPDIR/termux-packages-aarch64.zip -d $TMPDIR
#		tar xvf $TMPDIR/debs-aarch64-1e2023f351d547b82494edfb0f5baac0fd490370.tar -O debs/openjdk-17_17.0-17_aarch64.deb > $TMPDIR/openjdk-17_17.0-17_aarch64.deb
#		dpkg -i $TMPDIR/openjdk-17_17.0-17_aarch64.deb
#		rm -rf $TMPDIR/*
		if [[ ! -e $PREFIX/opt/openjdk/lib/libgif.so.7 ]]
		then
			ln -s $PRERIX/lib/libgif.so.7.2.0 $PREFIX/opt/openjdk/lib/libgif.so.7
		fi
		wget -q --tries=20 https://portswigger.net/burp/releases/download -O $TOOLS/$toInstall.jar
		cat <<- CONF $HOME/.local/bin/$toInstall
#!/usr/bin/bash
#This file execute a burp suite on Termux:Wayland interface
#You should install it before to run this scripta
[[ \$(uname -m) = "aarch64" ]] || { printf >&2 "\$R(_➤)\$W Incompatible architecture";exit;}
[[ -e $TOOLS/burpsuite.jar ]] || { printf >&2 "\$R(_➤)\$W Burpsuite is not installed...\$R aborting.\$W";exit;}
[[ \$(file \$TMPDIR/*|grep -o "socket") >/dev/null ]] || { printf >&2 "\$R(_➤)\$W Termux:Wayland server isn't running...\$R aborting.\$W";exit;}
export DISPLAY=:0
umask 000
exec \$(command -v java) --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -jar $TOOLS/burpsuite.jar
CONF
    chmod 755 $HOME/.local/bin/$toInstall
		;;
	code-server)
		[[ $(uname -m) = "aarch64" ]] || { printf >&2 "$R(_➤)$W Incompatible architecture";exit;}
		SearchTool
		yes|apt install build-essential python git nodejs-lts yarn
		yarn config set ignore-engines true
		yarn global add $toInstall --ignore-engines
		printf "$G(_>)_Set_a_login_password$W "
		while read -p ":─➤ " passwd && [ -z $passwd ];do
			continue
		done
		[[ -d ~/.config/code-server ]] || mkdir -p ~/.config/$toInstall
		cat <<- CONF > ~/.config/$toInstall/config.yaml
		bind-addr: 127.0.0.1:8080
		auth: password
		password: $passwd
		cert: false
		CONF
		;;
	desktop-xfce4|xfce4-about)
		[[ $toInstall = desktop-xfce4 ]] && toInstall=xfce4-about
		SearchTool
		for i in vnc icons themes config; do
			[[ -d ~/.$i ]] && rm -rf ~/.$i
		done
		echo "deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras" > $PREFIX/etc/apt/sources.list.d/termux-desktop-xfce.list;apt update >/dev/null 2>/dev/null
		for pkg in x11-repo termux-x11 termux-gui-package xwayland xfce4 xfce4-taskmanager xfce4-goodies termux-api cmake-curses-gui git-gui dosbox xfce4-terminal python-tkinter neofetch loqui the-powder-toy galculator xorg-xhost mpv ristretto xfce4-whiskermenu-plugin xfce4-clipman-plugin xarchiver libx11-static tigervnc geany geany-plugins gtk2 gtk3 mtpaint leafpad otter-browser recordmydesktop feh audacious lxqt-themes papirus-icon-theme lxappearance fluent-icon-theme fluent-gtk-theme kvantum zenity dbus-glib dconf $(apt search 'xfce4-' 2>/dev/null|grep '/'|awk -F '/' '{print $1}') breeze-cursor-theme ttf-microsoft-cascadia; do
			ipkg=$(pkg list-installed 2>/dev/null|grep "$pkg"|awk -F "/" '{print $1}') >/dev/null
#			checkpkg=${ipkg%/*}
			if [[ -z $ipkg ]]
			then
				printf "$G(_➤)$W Installing package $pkg...$W\n"
				yes|apt install $pkg 2>$LOGFILE
			else
				printf "$Y(_➤)$W Package $pkg installed successfully.$W\n"
			fi
		done
		[[ -d $HOME/.backup ]] && rm -rf $HOME/.backup
		mkdir -p $HOME/{Desktop,Downloads,Templates,Public,Documents,Pictures,Videos,.backup}
		ln -s $HOME/storage/music $HOME/Music
		[[ -d $HOME/.config ]] && mv $HOME/.config $HOME/.backup
		wget -q https://github.com/Yisus7u7/termux-desktop-xfce/releases/download/desktop-5.0.3/data.tar.xz -O $TMPDIR/data.tar.xz
		tar -xvf data.tar.xz -C $HOME
		rm $TMPDIR/data.tar.xz
		file2restore=$(diff -q $HOME/.backup/.config/ $HOME/.config/|grep -iv "backup"|awk -F ' ' '{print $NF}')
		for f in ${file2restore[*]};do
			cp -r $HOME/.config/$file2restore $HOME/.backup/.config
		done
		rm -rf $HOME/.config
		mv $HOME/.backup/.config $HOME/.config
		rm -rf $HOME/.backup
		exec vncserver;sleep 3
		sed 's|/twm &|xfce4-session &|g' -i ~/.vnc/xstartup
		printf "$Y\nNOW GO TO PLAY STORE AND DOWNLOAD VNC SERVER APP\nOR GO TO GITHUB AND DOWNLOAD TERMUX WAYLAND APP$G\n[$green RUN BY VNC$G ]─➤$W vncserver$G\n      ╰─────────➤$W At first time, you will be prompted for setting up passwords$Y\n\nOPEN VNC APP AND SET NETWORK ADDRESS AS :$W localhost:1$G\n[$green TO STOP IT$G ]─➤$W vncserver -kill :1\n"
		toInstall=Xwayland
		;;
	binchecker|crunch|i-Haklab|IbyC-fixer|converter|lock|pagekite|serverphp|torvpn)
		SearchTool
		yes|apt install curl
		[[ $toInstall = blackbox ]] && {
			yes|apt install python2;
			python2 -m pip install requests;
		}
		curl -Ls $iHDB/bin/$toInstall -o $HOME/.local/bin/$toInstall
		chmod 751 $HOME/.local/bin/$toInstall
		;;
	hydra)
		SearchTool
		yes|apt install git cmake make automake libgcrypt libssh libidn openssl openssl-tool
		git clone --quiet https://github.com/vanhauser-thc/thc-$toInstall $PREFIX/opt/thc-$toInstall
		hpath=$PREFIX/opt/thc-$toInstall
		chmod 750 -R $hpath
		sed -i 's|wait3(NULL, WNOHANG, NULL);|wait4(NULL, WNOHANG, NULL, NULL);|g' $hpath/$toInstall.c
		cd $hpath;make clean && sh configure --prefix=$PREFIX;make;make install
		cd $hpath/$toInstall-gtk;sh make_xhydra.sh
		for i in $toInstall x$toInstall;do
			[[ -e $hpath/$i ]] && chmod +x $hpath/$i;cp $hpath/$i $HOME/.local/bin/ || printf "$R\n   《ERR TO COMPILE $i》\n"
		done
		rm -rf $hpath
		;;
	JohnTheRipper|john)
		[[ $toInstall = JohnTheRipper ]] && toInstall="john"
		SearchTool
		JTRv="1.8.0"
		JTRtar="https://download.openwall.net/pub/projects/john/contrib/android/john-$JTRv-android-1.tar.gz"
		yes|apt install wget
		wget -q $JTRtar -O $TMPDIR/john-$JTRv-android-1.tar.gz
		tar -xvzf $TMPDIR/john-$JTRv-android-1.tar.gz -C $TMPDIR
		rm -rf $TMPDIR/john-$JTRv-android-1.tar.gz
		mkdir -p $PREFIX/opt/john
		JTR="$PREFIX/opt/john"
		mv $TMPDIR/john-$JTRv-android/user/* $JTR
		ln -s $JTR/john.conf $JTR/john.ini
		sleep 2
		case $(uname -m) in
			aarch64)
				mv $TMPDIR/john-$JTRv-android/libs/arm64-v8a/* $JTR
				;;
			arm)
				mv $TMPDIR/john-$JTRv-android/libs/armeabi/* $JTR
				;;
			armhf)
				mv $TMPDIR/john-$JTRv-android/libs/armeabi-v7a/* $JTR
				;;
			i686)
				mv $TMPDIR/john-$JTRv-android/libs/x86/* $JTR
				;;
			x86_64)
				mv $TMPDIR/john-$JTRv-android/libs/x86_64/* $JTR
				;;
		esac
		rm -rf $TMPDIR/john-$JTRv-android
		chmod +x $JTR/*
		printf "#!/usr/bin/bash
#This script find and execute johntheripper tool
R='\\033[1;31m'
W='\\033[0m'
if [ -d \$PREFIX/opt/john ];then
	cd \$PREFIX/opt/john
	./john \$@
else
	printf \"\$R(_➤)\$W JohnTheRipper is not installed\$W\"
fi
#            i-Haklab by @Ivam3" > $HOME/.local/bin/john
		chmod +x $HOME/.local/bin/john
		;;

	localtunnel-server|lt)
		[[ $toInstall = localtunnel-server ]] && toInstall="lt"
		SearchTool
		yes|apt install nodejs git
		git clone --quiet https://github.com/localtunnel/localtunnel $TMPDIR/localtunnel-server
		cd $TMPDIR/localtunnel-server
		npm install
		npm install -g localtunnel
		wget -q --tries=20 ${iHDB}/fix-tools/openurl.js -O $PREFIX/lib/node_modules/localtunnel/node_modules/openurl/openurl.js
		rm -rf $TMPDIR/localtunnel-server
		;;
	ngrok)
		SearchTool
		arch1=$(uname -a|grep -o 'arm'|head -n1)
		arch2=$(uname -a|grep -o 'Android'|head -n1)
		command -v wget >/dev/null || yes|apt install wget
		command -v termux-chroot >/dev/null || yes|apt install proot
		[[ $(command -v ngrok) ]] && mv $(command -v ngrok) $(command -v ngrok).io
		[[ -d ~/.ssh ]] || mkdir ~/.ssh
		[[ -e ~/.ssh/config ]] || touch ~/.ssh/config
		printf "host tunnel.us.ngrok.com\n\tHostkeyAlgorithms +ssh-rsa\n\tPubkeyAcceptedAlgorithms +ssh-rsa\n" >> ~/.ssh/config
		bash <(curl -fsSL "http://git.io/abhacker-repo") --install ngrok-server
		[[ $arch1 = 'arm' ]] || [[ $arch2 = 'Android' ]] && arch=arm || arch=386
		wget -q https://bin.equinox.io/c/4VmDzA7iaHb/$1-stable-linux-$arch.zip -O $TMPDIR/$1-stable-linux-$arch.zip
		if [[ -e $TMPDIR/$1-stable-linux-$arch.zip ]];then
			[[ -d ~/.ngrok2 ]] || mkdir -p ~/.ngrok2
			unzip -q $TMPDIR/$1-stable-linux-$arch.zip -d ~/.ngrok2/
			rm -rf $TMPDIR/$1-stable-linux-$arch.zip
			cat <<- EOF > $HOME/.local/bin/$1.io
#!/usr/bin/bash
#THIS SCRIPT EXECUTE NGROK TO AVOID 'bad address' ERROR

[[ -e $PREFIX/bin/termux-chroot ]] || yes|apt install proot >/dev/null 2>/dev/null
exec termux-chroot $HOME/.ngrok2/ngrok \${@:1}

#     i-Haklab by Ivam3
EOF
			chmod +x $HOME/.local/bin/$1.io $HOME/.ngrok2/$1
			PS3="(_➤) "
			printf "$Y(_➤)$W $toInstall needs an authtoken from $1.com$Y\n"
			select way in Set_authtoken Skip_this_step;do
				case $way in
					Set_authtoken)
						while read -p "(_>)_authtoken─➤ " token && [ -z $token ];do
							continue
						done
						exec $HOME/.local/bin/ngrok.io authtoken $token
						break
						;;
					*)
						printf "$Y(_➤)$W Don't forget set your token running:$Y\n ╰─────➤$W $toInstall authtoken <your-token>";exit
						;;
				esac
			done
		else
			Err
		fi
		;;

	shc|unshc)
		SearchTool
		shcVer="3.8.9"
		yes|apt install wget make
		wget -q http://www.datsi.fi.upm.es/~frosal/sources/shc-$shcVer.tgz -O $TMPDIR/shc-$shcVer.tgz
		tar -xvzf $TMPDIR/shc-$shcVer.tgz -C $TMPDIR
		rm -rf $TMPDIR/shc-$shcVer.tgz
		cd $TMPDIR/shc-$shcVer
		make;make install
		mv $TMPDIR/shc-$shcVer/$toInstall $HOME/.local/bin/
		rm -rf $TMPDIR/shc-$shcVer
		wget -q https://raw.githubusercontent.com/yanncam/UnSHc/master/latest/unshc.sh -O $HOME/.local/bin/unshc
		sed 's|which|command -v|g' -i $HOME/.loczl/bin/unshc
		sed 's|/tmp/XXXXXX|$PREFIX/tmp/XXXXXX|g' -i $HOME/.local/bin/unshc
		chmod +x $HOME/.local/bin/*
		;;
	slowhttptest)
		SearchTool
		yes|apt install git make automake
		git clone --quiet https://github.com/shekyan/$toInstall $TOOLS/$toInstall
		cd $TOOLS/$toInstall
		./configure && make && make install
		cp $TOOLS/$toInstall/src/$1 $HOME/.local/bin
		chmod +x $HOME/.local/bin/$toInstall
		;;
	snow)
		SearchTool
		yes|apt install wget make automake
		wget -q http://http.kali.org/pool/main/s/steg$toInstall/steg$toInstall_20130616.orig.tar.gz -O $TMPDIR/steg$toInstall_20130616.orig.tar.gz
		tar -xvzf $TMPDIR/stegsnow_20130616.orig.tar.gz -C $TMPDIR
		cd $TMPDIR/$toInstall-20130616/
		make
		mv $TMPDIR/$toInstall-20130616/$toInstall $HOME/.local/bin
		rm -rf $TMPDIR/snow-20130616/
		rm -rf $TMPDIR/stegsnow_20130616.orig.tar.gz
		chmod 750 $HOME/.local/bin/$toInstall
		;;

	torvpn)
		SearchTool
		yes|apt install tor torsocks proxychains-ng
		wget -q $iHDB/etc/tor/torrc -O $PREFIX/etc/tor/torrc
		wget -q $iHDB/etc/proxychains.conf -O $PREFIX/etc/proxychains.conf
		for i in myip mypip swip ; do
			wget -q $iHDB/bin/$i -O $HOME/.local/bin/$i
			chmod 750 $HOME/.local/bin/$i
		done
		;;
	twifo-cli|twifo)
		[[ $toInstall = twifo-cli ]] && toInstall="twifo"
		SearchTool
		yes|apt install nodejs
		npm install -global $toInstall-cli
		;;

	#::RUBY::#
	beef)
	  [[ -d $PREFIX/opt/$toInstall ]] || rm $HOME/.local/bin/$toInstall 2>/dev/null
	  SearchTool
		yes|apt install ruby nodejs #dirmngr -y
		if [[ ! -d $PREFIX/opt ]];then
			mkdir -p $PREFIX/opt
		fi
		git clone --quiet https://github.com/$1project/$toInstall $PREFIX/opt/$toInstall
		sed -i "5a gem 'net-smtp', require: false" $PREFIX/opt/$toInstall/Gemfile
		sed "s|database: '/opt/GeoIP/GeoLite2-City.mmdb'|database: '/data/data/com.termux/files/usr/opt/GeoIP/GeoLite2-City.mmdb'|g" -i config.yaml
		sed 's|passwd: "beef"|passwd: "Ivam3byCinderella"|g' -i config.yaml
		sed '155 s|enable: false|enable: true|g' -i config.yaml
		sed "s|ssl_version: 'TLS1'|ssl_version: 'TLS1.2'|g" -i $PREFIX/opt/$toInstall/extensions/metasploit/config.yaml
		cd $PREFIX/opt/$toInstall
		update --system
		gem install bundler
		bundle install
		curl -Ls ${iHDB}/fix-tools/fixbigdecimal|bash
		wget -q $iHDB/bin/$1 -O $HOME/.local/bin/$1
		chmod +x $HOME/.local/bin/$1
		wget -q $iHDB/to-install/GeoLite2-City_20200331.tar.gz -O $PREFIX/opt/$1/GeoLite2-City_20200331.tar.gz
		if [[ -e $PREFIX/opt/$1/GeoLite2-City_20200331.tar.gz ]];then
			gunzip $PREFIX/opt/$1/GeoLite2-City_20200331.tar.gz
			if [[ -e $PREFIX/opt/$1/GeoLite2-City_20200331.tar ]];then
				tar xvf $PREFIX/opt/$1/GeoLite2-City_20200331.tar
				rm -rf $PREFIX/opt/$1/GeoLite2-City_20200331.tar
				if [[ ! -d $PREFIX/opt/GeoIP ]];then
					mkdir -p $PREFIX/opt/GeoIP
				else
					Err
				fi
				if [[ -d $PREFIX/opt/$1/GeoLite2-City_20200331 ]];then
					mv $PREFIX/opt/$1/GeoLite2-City_20200331/* $PREFIX/opt/GeoIP
					rm -rf $PREFIX/opt/$1/GeoLite2-City_20200331
				else
					Err
				fi
			else
				Err
			fi
		else
			Err
		fi
		;;

	cewl)
		SearchTool
		yes|apt install ruby git
		git clone --quiet https://github.com/digininja/CeWL $TOOLS/$toInstall
		cd $TOOLS/$toInstall
		chmod +x -R $TOOLS/$toInstall
		bundle install
		;;
	hatcloud)
		SearchTool
		yes|apt install git ruby
		git clone --quiet https://github.com/HatBashBR/HatCloud $TOOLS/$toInstall
		chmod 750 $TOOLS/$toInstall/$toInstall.rb
		;;
    wpscan)
			SearchTool
	    yes|apt install git ruby
	    git clone --quiet https://github.com/wpscanteam/$toInstall $TOOLS/$toInstall
	    gem install $toInstall -- --use-system-libraries
	    chmod 750 $TOOLS/$toInstall/bin/*
	    curl -Ls ${iHDB}/fix-tools/fixbigdecimal|bash
	    ;;
	#::GO::
	amass)
	  SearchTool
		goEnv
		export GO111MODULE=on
		go get -v github.com/OWASP/Amass/v3/...
		chmod 751 -R ~/go
		goa=$(find ~/go/pkg/mod/github.com -type d -iname "!$toInstall"|head -n 1)
		ln -s $goa/$(ls $goa) $PREFIX/lib/go/src/$toInstall
		cd $gob/$(ls $gob)
		go get && go build && go install
		;;
	aquatone)
		SearchTool
		goEnv
		git clone --quiet https://github.com/michenriksen/$toInstall ~/go/pkg/mod/github.com/$toInstall
		ln -s $HOME/go/pkg/mod/github.com/$toInstall $HOME/$toInstall
		wget -q $iHDB/bin/$toInstall -O $HOME/.local/bin/$toInstall
		gem install --quiet --silent $toInstall
		;;
	gobuster)
		SearchTool
		goEnv
		go install github.com/OJ/$toInstall/v3@latest
		chmod 751 -R ~/go
		gob=$(find ~/go/pkg/mod/github.com -iname $toInstall)
		ln -s $gob/$(ls $gob) $PREFIX/lib/go/src/$toInstall
		cd $gob/$(ls $gob)
		go get && go build && go install
		;;
	gophish)
		SearchTool
		goEnv
		go get github.com/$toInstall/$toInstall
		chmod 751 -R ~/go
		gop1=$(find ~/go/pkg/mod/github.com -type d -iname $toInstall|head -n 1)
		gop2=$(ls $gop1|grep $toInstall)
		mv ~/go/bin/$toInstall $gop1/$gop2/$toInstall
		cat <<- CONF > ~/go/bin/$toInstall
		#!/usr/bin/bash
		cd $gop1/$gop2
		exec $gop1/$gop2/$toInstall
		#           i-Haklab by Ivam3.
		CONF
		chmod +x ~/go/bin/$toInstall
		sed 's|"listen_url": "0.0.0.0:80",|"listen_url": "127.0.0.1:8080",|g' -i $gop1/$gop2/config.json
		chmod 640 $gop1/$gop2/config.json
		;;
	tangalanga)
		SearchTool
		goEnv
		go get github.com/elcuervo/$toInstall
		chmod 751 -R ~/go
		got=$(find ~/go/pkg/mod/github.com -type d -iname "$toInstall*")
		cd $got
		go get
		go build
		go install
		;;
	virustotal)
		SearchTool
		for repo in unstable-repo $toInstall-cli;do
			PKG=$(pkg list-all|grep -o $repo)
			if [[ ! -z "$PKG" ]];then
				yes|pkg install $repo
			elif [[ ! -d $HOME/go/src/github.com/VirusTotal/vt-cli ]]; then
				goEnv
				go get -d github.com/VirusTotal/vt-cli/vt
				cd ~/go/src/github.com/VirusTotal/vt-cli
				make install
				ln -s ~/go/bin/vt $HOME/.local/bin/vt
				exec vt completion bash > $PREFIX/etc/bash_completion.d/vt
			fi
		done
		;;
	#::PERL::#

	acccheck)
		SearchTool
		yes|apt install git perl
		git clone --quiet https://github.com/qashqao/$toInstall $TOOLS/$toInstall
		chmod +x -R $TOOl/$toInstall
		;;
	#:PHP:#
	rhawk)
	  SearchTool
		yes|apt install php
		git clone --quiet https://github.com/Tuhinshubhra/RED_HAWK $TOOLS/$toInstall
		chmod +x $TOOLS/$toInstall/$toInstall.php
		;;
	#::ROOT::#
	dnsenum)
		SearchTool
		if chk-root;then
			apt install curl perl
			curl -Ls https://raw.githubusercontent.com/fwaeytens/$toInstall/master/$toInstall.pl -o $HOME/.local/bin/$toInstall
			termux-fix-shebang $HOME/.local/bin/$toInstall
			chmod +x $HOME/.local/bin/$toInstall
			for repo in WWW::Mechanize Net::IP Net::DNS Net::Netmask XML::Writer String::Random ; do
				cpan -i $repo
			done
			[[ -d $PREFIX/share/$toInstall ]] || mkdir -p $HOME/.local/share/$toInstall
			[[ -d ~/.$toInstall ]] || mkdir -p ~/.$toInstall
			curl https://raw.githubusercontent.com/fwaeytens/$toInstall/master/dns.txt -o $HOME/.local/share/$toInstall/dns.txt
			exec sudo $toInstall
		else
			STDERROOT
		fi
		;;
	nikto)
		SearchTool
		if chk-root;then
			yes|apt install git wget perl
			git clone --quiet https://github.com/sullo/nikto $TOOLS/$toInstall
			chmod 750 -R $TOOLS/$toInstall
			wget -q $iHDB/bin/nikto -O $HOME/.local/bin/$toInstall
			chmod +x $HOME/.local/bin/nikto
		else
			STDERROOT
		fi
		;;
	webhackshl)
		SearchTool
		yes|apt install git curl python tor ruby nmap
		PIPup
		PY=""
		git clone --quiet https://github.com/sechacklabs/$toInstall $TOOLS/$toInstall
		wget -q $iHDB/fix-tools/checker.py -O $TOOLS/$toInstall/modules/checker.py
		printf "fierce" > $TMPDIR/requirements.txt
		PYmodules
		rm -f $TMPDIR/requirements.txt
		for i in sqlmap nikto whatweb wpscan dnsenum;do
			exec i-Haklab install $i
		done
		;;
	xerosploit)
		SearchTool
		TMPPATH=$PREFIX/opt/$toInstall
		if chk-root; then
			yes|apt install git nmap hping3 build-essential python2 ruby git libpcap
			PIPup
			PYv="2"
			git clone --quiet https://github.com/LionSec/$toInstall $TMPPATH
			printf "tabulate\nterminaltables" > $TMPDIR/requirements.txt
			chmod +x -R $TMPPATH/tools
			PYmodules
			rm -f $TMPDIR/requirements.txt
			cd $TMPPATH/tools/bettercap/
			gem build bettercap.*
			gem install xettercap-*
			for del in xettercap-* $TMPPATH/run.sh $TMPPATH/$toInstall.py;do
				rm -rf $del
			done
			wget -q $iHDB/fix-tools/$toInstall.py -O $TMPPATH/$toInstall.py
		fi
		;;
	*)
		printf "$R(_➤)$W Unable to locate $toInstall on i-Haklab\n"
		sleep 0.5
		printf "$G(_➤)$W Trying with Advance Packect Tool (APT)...\n"
		pkg=$(pkg list-all 2>/dev/null|grep "$toInstall"|awk -F "/" '{print $1}') 
		if [[ ! -z $pkg ]] && [[ $pkg = $toInstall ]];then
			yes|apt install $toInstall
		else
			printf "$R(_➤)$W Tool $toInstall doesn't exist\n"
			exit
		fi
		;;
esac
#ENDING SCRIPT
printf "$G\n\n (_>)-> :::::::::::::::::: DONE !! ::::::::::::::::::: <-(<_)$Y\n\tTo run $1 execute :$G run $toInstall$W\nFor more information execute: i-Haklab about $1$Y\n\t   To fix issues going to$B t.me/Ivam3_Bot$W\n\n"
#             i-Haklab by @Ivam3
