#!/usr/bin/bash
#Created on July/2021
IFS=$'\n\t'
trap ctrl_c 2
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions

ctrl_c(){ printf "\n$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n";}
Err() { printf "$R\n(_>)─➤$W A phone number needed";ctrl_c;exit;}

key="6a0b5639dc35f09d5bf80c409c23d9d9"
num="$1"
url="http://apilayer.net/api/validate?access_key=$key&number=$num&country_code=&format=1"

[[ ! $num ]] && Err
printf "$Y\n  Scanning phonenumber :$W $num$G\n  ________________________________________________________\n"
printTable '_' "$(curl -s $url|tail -n 11|tr -d "\}|\"|,"|tr "_" " "|tr ":" "_")"
printf "  ________________________________________________________$W\n\n"
tput cnorm
