#!/data/data/com.termux/files/usr/bin/bash
#This script will install i-Haklab v.3.0 2021 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3.
IFS=$'\n\t'
trap ctrl_c 2
ctrl_c() { printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}
printf "Running...";sleep 0.5
[[ -d $HOME/.local/share/i-Haklab ]] && rm -rf $HOME/.local/share/i-Haklab
[[ -d ~/java ]] && rm -rf ~/java
git clone https://github.com/ivam3/i-Haklab.git $HOME/.local/share/i-Haklab
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
chk-Cuser
clear;banner;sleep 0.5
if [ -d ~/.local ]; then
	rm -rf ~/.local
fi
if [ -d ~/.config/fish ]; then
	rm -rf ~/.config/fish
fi
if command -v fish >/dev/null;then yes|apt remove fish && apt autoremove; fi

printf "$Y\n(_>)─➤$W Head to app configuration and provides storage permissions to termux.$Y\n ╰─➤$W when finished$G press enter\n$W"
read enter

#::::::::::Installation of dependencies::::::::::::#
printf "$G(_>)─➤$W Upgrading and installing Termux packages.\n"
yes|pkg update && pkg upgrade
apt list|awk -F "/" '{print $1}' > $TMPDIR/alltools.tmp
pkg list-installed|awk -F "/" '{print $1}' > $TMPDIR/installed.tmp
for repo in $(cat $iHAKLAB/.set/to-install/listOfpkg);do
	GOTIT=$(grep -oE $repo $TMPDIR/installed.tmp)
	PKG=$(grep -o $repo $TMPDIR/alltools.tmp)
	if [ ! -z "$PKG" ] && [ -z "$GOTIT" ];then
		printf "$G(_>)─➤$W Installing the repository $repo.\n"
		yes|pkg install $repo
	elif [ ! -z "$PKG" ] && [ ! -z "$GOTIT" ]; then
		continue
	else
		printf "$R(_>)─➤$W The repository $repo is not candidate.\n"
		sleep 1
	fi
done
rm -f $TMPDIR/alltools.tmp $TMPDIR/installed.tmp
printf "$G\n(_>)─➤$W Installing Abhacker repositories."
if [ ! -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ];then
	TMPabh=$(mktemp)
	wget -q --tries=20 "${iHDB}/fix-tools/instAbhackerRepo" -O $TMPabh
        chmod +x $TMPabh
fi

#::: UPDATING LOCATE DATA BASE :::#
printf "$G\n(_>)─➤$W Updating data base."
exec updatedb

printf "$G\n(_>)─➤$W Installing required python modules.\n"
for v in python python2 ; do
	$v -m pip --no-color --quiet --no-cache-dir install --upgrade pip 2>/dev/null
done
for module in trufflehog wheel speedtest-cli scapy wfuzz h8mail objection frida;do
	python -m pip --no-color --quiet --no-cache-dir install $module 
done

#::::::::::Definition of variable TOOLS::::::::::::#
printf "$G\n(_>)─➤ Getting access to external storage...$W"
printf "$Y\n(_>)─➤$W Access..";
sleep 0.5
if [ -w $TOOLS ];then
	printf "$G. DONE||$W\n"
else
	printf "$R. FAIL!!$W\n"
fi
yes|termux-setup-storage

#::::::::::Installation of Ohmyfish::::::::::::#
printf "$G\n(_>)─➤ Installing interactive shell.$W\n"
[[ -d ~/.local/share/omf ]] && rm -rf ~/.local/share/omf
[[ -d ~/.config/omf ]] && rm -rf ~/.config/omf/
git config --global core.autocrlf
printf "$Y\n(_>)─➤ Now you will see a PS1 as '⋊> ~/i-Haklab on master ⨯'\n ╰─➤ when it happen hold on for one minute and then type exit to continue$W\n"
curl -Ls $iHDB/to-install/get.oh-my.fish|fish
cat <<- CONF >> $PREFIX/etc/fish/config.fish
if status --is-login
bash /data/data/com.termux/files/home/.local/etc/i-Haklab/wall-banner
end

function on_exit --on-event fish_exit
echo 'Have a nice hacking day!!'
sleep 1
end

set fish_theme bira
set -g theme_nerd_fonts yes
set DISPLAY localhost:0
set PATH $HOME/.local/bin:$PATH
set HOME /data/data/com.termux/files/home
set GOPATH /data/data/com.termux/files/home/go
set GOROOT /data/data/com.termux/files/usr/lib/go
set JAVA_HOME /data/data/com.termux/files/usr/opt/openjdk
set iHAKLAB /data/data/com.termux/files/home/.local/share/i-Haklab
set LD_LIBRARY_PATH $HOME/.local/lib:/data/data/com.termux/files/usr/lib
set TOOLS $TOOLS
alias LOCALHOST="ifconfig 2>/dev/null|grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'|grep -v 255|grep -v 127|tail -n 1"
alias serverapache="apachectl"
alias postgresql="pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql"
alias traductor="gawk -f (curl -Ls git.io/translate | psub) -- -shell"
CONF
TMP_fish=$(mktemp)
cat <<- CONF > $TMP_fish
#!/bin/env fish
omf install bobthefish
CONF
fish $TMP_fish >/dev/null 2>&1
cat <<- CONF > $HOME/.bashrc
export PATH=$HOME/.local/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
chsh -s fish
CONF

#::::::::::Insatalling i-Haklab's login::::::::::::#
[[ -e $HOME/.local/etc/i-Haklab/login-termux ]] && rm -f $HOME/etc/i-Haklab/login-termux
[[ -e $PREFIX/etc/bashito ]] && rm -f $PREFIX/etc/bashito
[[ -e $PREFIX/etc/motd ]] && rm -f $PREFIX/etc/motd
[[ -e $PREFIX/etc/motd.dpkg-old ]] && rm -f $PREFIX/etc/motd.dpkg-old
for i in Quiz Ivam3 Cinderella;do
        [[ -e $HOME/.local/etc/i-Haklab/.$i ]] || touch $HOME/.local/etc/i-Haklab/.$i
done
[[ -d $HOME/.local/etc/i-Haklab ]] || mkdir -p $HOME/.local/etc/i-Haklab
wget -q $iHDB/to-install/login-termux -O $HOME/.local/etc/i-Haklab/login-termux
wget -q $iHDB/libexec/banner/i-Haklab -O $HOME/.local/etc/i-Haklab/login-banner
cat <<- CONF > $HOME/.local/etc/i-Haklab/wall-banner
#!/usr/bin/bash
#Banner for i-Haklab created by @Ivam3 on Jan/2019
IFS=$'\n\t'
bash $HOME/.local/etc/i-Haklab/login-banner
#        i-Haklab by @Ivam3
CONF
chmod 711 -R $HOME/.local/etc
chmod +w $HOME/.local/etc/i-Haklab/.Ivam3
printf "SXZhbTNieUNpbmRlcmVsbGEK" > $HOME/.local/etc/i-Haklab/.Ivam3
chmod -w $HOME/.local/etc/i-Haklab/.Ivam3
chmod +w $HOME/.local/etc/i-Haklab/.Quiz
printf "VGhlIGFjY2VzcyBrZXkgaXMgSXZhbTNieUNpbmRlcmVsbGEK" > $HOME/.local/etc/i-Haklab/.Quiz
chmod -w $HOME/.local/etc/i-Haklab/.Quiz
chmod +w $HOME/.local/etc/i-Haklab/.Cinderella
printf "SXZhbTNieUNpbmRlcmVsbGEK" > $HOME/.local/etc/i-Haklab/.Cinderella
chmod -w $HOME/.local/etc/i-Haklab/.Cinderella

#::::::::::Insatalling i-Haklab tools::::::::::::#
printf "$G\n(_>)─➤$W Installing principal external tools."
chmod 750 $iHAKLAB/.set/bin/*
cp $iHAKLAB/.set/bin/* $HOME/.local/bin

if ! command -v msfconsole >/dev/null;then
        printf "$G\n(_>)─➤$W Installing metasploit-framework."
        bash $TMPabh --install metasploit ruby=2.7.2 >/dev/null 2>&1
        wget -q $JAVADB/.embed/apk.rb -O $MSFDIR/lib/msf/core/payload/apk.rb
        wget -q $iHDB/.set/bin/IbyC-fixer -O $HOME/.local/bin/IbyC-fixer
        chmod +x $HOME/.local/bin/IbyC-fixer
        #:::: FIXING BIG DECIMAL ISSUES ::::#
        RUBYv=$(ls $PREFIX/lib/ruby |grep -m 1 '[0-9].[0-9].[0-9]')
        LINUXANDROID=$(find $PREFIX/lib/ruby/$RUBYv -iname "bigdecimal.so"|awk -F "/" '{print $10}')
        yes|apt install -yq patchelf >/dev/null 2>&1
        if [[ -e "$PREFIX/lib/ruby/$RUBYv/$LINUXANDROID/bigdecimal.so" ]];then
                if [[ -n "$(patchelf --print-needed "$PREFIX/lib/ruby/$RUBYv/$LINUXANDROID/bigdecimal/util.so"|grep bigdecimal.so)" ]];then
                        exit 0
                fi
        patchelf --add-needed \
                "$PREFIX/lib/ruby/$RUBYv/$LINUXANDROID/bigdecimal.so" \
                "$PREFIX/lib/ruby/$RUBYv/$LINUXANDROID/bigdecimal/util.so"
        fi
        printf "#!/usr/bin/sh
        SCRIPT_NAME=\$(basename \"\$0\")
        METASPLOIT_PATH=\"\${PREFIX}/opt/metasploit-framework\"
        #Fix ruby bigdecimal extensions linking error.
        export LD_PRELOAD=\"$LINUXANDROID:\$LD_PRELOAD\"
        case \"\$SCRIPT_NAME\" in
                msfconsole|msfvenom)
                        exec ruby \"\$METASPLOIT_PATH/\$SCRIPT_NAME\" \"\$@\"
                        ;;
                *)
                        echo \"[!] Unknown Metasploit command '\$SCRIPT_NAME'.\"
                        exit 1
                        ;;
        esac" > $PREFIX/bin/msfconsole
fi

printf "$G\n(_>)─➤$W Installing ngrok.io ngrok-ssh and ngrok-server."
[[ $(command -v ngrok) ]] && mv $(command -v ngrok) $(command -v ngrok).io
bash $TMPabh --install ngrok-server >/dev/null 2>&1
rm $TMPabh

printf "$G\n(_>)─➤$W Installing VIM predictable text."
[[ -d ~/.vim ]] && rm -rf ~/.vim
wget -q --tries=20 ${iHDB}/to-install/iHaklabvim.zip -O $TMPDIR/iHaklabvim.zip
unzip -q $TMPDIR/iHaklabvim.zip -d $TMPDIR
rm -f $TMPDIR/iHaklabvim.zip
mv $TMPDIR/iHaklabvim/vim ~/.vim
mv $TMPDIR/iHaklabvim/vim/.vimrc ~/
rm -f $TMPDIR/iHaklabvim
vim +PlugUpdate +x +x

printf "$G\n(_>)─➤$W Setting i-Haklab style."
[[ -d ~/.termux ]] || mkdir -p ~/.termux
for i in $(ls $iHDB/to-install/.termux/);do
	wget -q --tries=20 $iHDB/to-install/$i -O ~/.termux/$i
done
ln -s $PREFIX/bin/fish ~/.termux/shell

#:::: Set VNC server ::::#
printf "$G\n(_>)─➤$W Setting vncserver."
wget -q --tries=20 $iHDB/functions/unset.fish -O  ~/.config/fish/functions/unset.fis
for TOOL in DoS-A-Tool ExiF embed evilurl localtunnel-server desktop-xfce;do
	bash $iHAKLAB/.set/share/install $TOOL
done
exec vncserver :1
[[ -d ~/.vnc ]] || mkdir ~/.vnc
cat <<- CONF > ~/.vnc/xstartup
#!/data/data/com.termux/files/usr/bin/sh
## This file is executed during VNC server
## startup.

# Launch terminal emulator Aterm.
# Requires package 'aterm'.
aterm -geometry 160x48+20+20 -ls &

# Launch Tab Window Manager.
# Requires package 'xorg-twm'.
startxfce4
CONF
vncserver -kill :1 >/dev/null 2>/dev/null &

#::::::::::Searching for root permissions::::::::::::#
if chk-root;then
	wget -q --tries=20 $iHDB/bin/sudo -O $PREFIX/bin/sudo
        if [[ -e ~/.suroot/.bashrc ]];then
                [[ -O ~/.suroot/.bashrc ]] || sudo chown $USER:$USER -R ~/.suroot/
        else
		[[ -d ~/.suroot ]] || mkdir ~/.suroot
        fi
        cat <<- CONF > ~/.suroot/.bashrc
PS1=\"\[\e[33m\][!] \[\e[31m\]Press\[\e[32m\] Ctrl d\[\e[31m\] to log out\[\e[32m\] ➤ \[\e[m\]\""
export TERM=xterm-256color
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
export PATH=/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/xbin:/system/bin
HOME=/data/data/com.termux/files/home
fish
#          i-Haklab by @Ivam3
CONF
fi

bash $iHAKLAB/.set/share/review #LOGFILE
printf "$G\n\n
(_>)─➤$W i-Haklab installed !!!$Y\n
(_>)─➤$W Main commands$Y
 ╰────────➤ run:$W i-Haklab -h :───────────:to automate process$Y
 ╰────────➤ run:$W run <name of tool> :────:to execute installed tool$Y
 ╰────────➤ run:$W omf theme :─────────────:to change a theme$Y
 ╰────────➤ run:$W lock :──────────────────:to block screen$Y
 ╰────────➤ run:$W IbyC-fixer :────────────:to fix termux's issues$Y
 ╰────────➤ run:$W LOCALHOST :─────────────:to show local ip$Y
 ╰────────➤ run:$W serverphp :─────────────:to start php server$Y
 ╰────────➤ run:$W traductor :─────────────:to init a translate shell$Y
 ╰────────➤ run:$W serverapache :──────────:to start apache server$Y
 ╰────────➤ run:$W torvpn :────────────────:to use a proxy connection$Y
 ╰────────➤ run:$W postgresql start :──────:to start postgresql data base$Y
 ╰────────➤ run:$W run Xwayland :──────────:to init graphical enviroment on Termux:Wayland app$Y
 ╰────────➤ run:$W vncserver :─────────────:to init graphical enviroment on vnc app$Y
 ╰────────➤ run:$W sudo <some commands> :──:to run commands as super user whithout rooted device$Y
 ╰────────➤ run:$W i-Haklab about i-Haklab :for all usage guide$G
(_>)─➤$W To fix issues going to$B t.me/Ivam3_Bot$G
(_>)─➤$W press$G enter$W to reestart Termux\n"
[[ -d ~/i-Haklab ]] && rm -rf ~/i-Haklab
read enter;exec reset
#		i-Haklab by @Ivam3
