#!/data/data/com.termux/files/usr/bin/bash
#Created on July/2021
IFS=$'\n\t'
trap ctrl_c 2
source $PREFIX/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
toRemove="$1"
ctrl_c(){ printf "$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n";exit;}

if [ ! -d $TOOLS/$toRemove ] && [ ! -e $PREFIX/bin/$toRemove ] && [ ! -d $PREFIX/opt/$toRemove ] && [ ! -e ~/go/bin/$toRemove ];then
	printf "$R(_>)─➤$W $toRemove isn't installed";exit
fi

Err() { printf "$R\n(_>)─➤$W Remove failed";ctrl_c;exit;}
PIPup() {
	for PYv in python2 python;do
		$PYv -m pip install --no-color --quiet --upgrade pip
	done
}
rmMainDir() {
	if chk-root;then
		user=sudo
	fi
	for path in $TOOLS $PREFIX/bin $PREFIX/opt ~/go/bin;do
		if [[ -d $path/$toRemove ]] || [[ -e $path/$toRemove ]];then
			$user rm -rf $path/$toRemove
		fi
	done
}
rmPYmodules() { python$PYv -m pip uninstall --quiet --no-color -r $TMPDIR/deps2drop;}
alert() { printf "$Y\n(_>)─➤$W The main $toRemove directory has been removed$Y\n(_>)─➤$W About dependencies: these could be necessary for another tool and these are :\n"
	cat -n $TMPDIR/deps2drop|sort
	printf "(_>)─➤$W To drop them press$G ENTER$W or$R ctrl+c$W to keep them\n"
	read enter
	PIPup
	rmPYmodules
	rm -f $TMPDIR/deps2drop
}
if [[ $SHLL = fish ]]; then
	INITFILE="$PREFIX/etc/fish/config.fish"
else
	INITFILE="$PREFIX/etc/bash.bashrc"
fi

running
case "$toRemove" in
	kalilinux)
		yes|apt install curl && curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Uninstall/Kali/UNI-kali.sh|bash
		;;
	#::ON BIN TOOLS::#
	binwalk|beef|cewl|evilurl|ghost|hakku|hatcloud|exploitdb|lockphish|nexphisher|saycheese|sayhello|wbruter|ExiF|binchecker|IbyC-fixer|blackbox|converter|serverphp|hydra|JohnTheRipper|ngrok|shc|slowhttptest|snow|whatweb|wpscan|DoS-A-Tool|acccheck|rhawk|nikto)
		if [[ $toRemove = beef ]]; then
			rm -rf $PREFIX/opt/GeoIP
		fi
		if [[ $toRemove = hydra ]];then
			yes|apt remove make automake
		fi
		if [[ $toRemove = JohnTheRipper ]]; then
			rm -f $PREFIX/bin/john
		fi
		if [[ $toRemove = shc ]];then
			rm -f $PREFIX/bin/un$toRemove
		fi
		if [[ $toremove = ngrok ]];then
			rm -rf ~/.ngrok2
			rm -f $PREFIX/bin/ngrok
			rm -f $PREFIX/bin/ngrok.io
		fi
		rmMainDir
		;;
	#:::PYTHON3:::#
	h8mail|objection)
		printf "$toRemove" > $TMPDIR/deps2drop
		alert
		;;
	fuzzdb)
		rmMainDir
		printf "wfuzz" > $TMPDIR/deps2drop
		alert
		;;
	getnpusers)
		rmMainDir
		printf "urllib3\nrequests\nmock\nidna\nbiopython\nrust\nimpacket" > $TMPDIR/deps2drop;alert
		;;
	hunner)
		rmMainDir
		printf "httplib2" > $TMPDIR/deps2drop
		alert
		;;
	ipgeolocation)
		rmMainDir
		printf "termcolor\ncolorama" > $TMPDIR/deps2drop
		alert
		;;
	osintgram)
		rmMainDir
		printf "requests==2.24.0\nrequests-toolbelt==0.9.1\ngeopy\nprettytable==0.7.2\ninstagram-private-api==1.6.0\ngnureadline" > $MPDIR/deps2drop
		alert
		;;
	phomber|vulnx)
		cat $TOOLS/$toRemove/requirements.txt > $TMPDIR/deps2drop
		rmMainDir
		alert
		;;
	phoneinfoga)
		yes|apt remove geckodriver
		rmMainDir
		if $(which geckodriver);then
			rm -f $PREFIX/bin/geckodriver
		fi
		printf "phonenumbers\nselenium\nbs4\ngoogle_api\nconfig\nhtml5lib\ngeckodriver-autoinstaller" > $TMPDIR/deps2drop
		alert
		;;
	quack)
		rmMainDir
		printf "install\nsetuptools\nphonenumbers\nrequests\nscapy\nwget\nargparse" > $TMPDIR/deps2drop
		alert
		;;
	recon-ng)
		yes|apt remove libxml2 libxml2-static libxml2-utils libxslt libxslt-static
		rmMainDir
		printf "dicttoxml\ndnspython\njsonrpclib\nlxml\nmechanize\nslowaes\nXlsxWriter\nolefile\nPyPDF2\nflask\nunicodecsv" > $TMPDIR/deps2drop
		alert
		;;
	routersploit)
		rmMainDir
		printf "future\nrequests\npysnmp\npycrypto\ncryptography\nparamiko\nbcrypt\npynacl" > $TMPDIR/deps2drop
		alert
		;;
	seeker)
		rmMainDir
		printf "requests" > $TMPDIR/deps2drop
		alert
		;;
	shellsploit)
		rmMainDir
		printf "capstone\nreadline\npefile\ncolorama\npylzma" > $TMPDIR/deps2drop
		alert
		;;
	sherlock)
		rmMainDir
		printf "beautifulsoup\nbs\ncertifi\ncolorama\nlxml\nPySocks\nrequests\nrequests-futures\nsoupsieve\nstem\ntorrequest" >> $TMPDIR/deps2drop
		alert
		;;
	sqlmap)
		if [[ -d $TOOLS/$toRemove ]];then
			rmMainDir
		else
			printf "sqlmap" > $TMPDIR/deps2drop
			alert
		fi
		;;
	theharvester)
		yes|apt remove libxml2 libxml2-static libxml2-utils libxslt libxslt-static
		cat $TOOLS/$toRemove/requirements.txt > $TMPDIR/deps2drop
		rmMainDir
		alert
		;;
	#::PYTHON2::#
	a2sv)
		Pyv="2"
		rmMainDir
		printf "argparse\nnetaddr" > $TMPDIR/deps2drop
		alert
		;;
	adminpanel|androbugs|cc-genpro|websploit)
		PYv="2"
		rmMainDir
		;;
	d-tect)
		PYv="2"
		rmMainDir
		printf "colorama\nbeautifulsoup" > $TMPDIR/deps2drop
		alert
		;;
	cloudbunny)
		PYv="2"
		rmMainDir
		printf "certificates" > $TMPDIR/deps2drop
		alert
		;;
	credmap)
		PYv="2"
		rmMainDir
		printf "urllib2" > $TMPDIR/deps2drop
		alert
		;;
	cryptovenom)
		PYv="2"
		rmMainDir
		printf "base58\nscrypt\npyblake2\npycrypto\ncrypto\nbcrypt\nrc2\ntwofish\ngeesefly\nskein pycipher\nnumpy\nCrypto\npasslib\nbase91\nmom\ngmpy2\nmore_itertools\nargon2_cffi" > $TMPDIR/deps2drop
		alert
		;;
	fbi|recondog)
		PYv="2"
		rmMainDir
		printf "requests" > $TMPDIR/deps2drop
		alert
		;;
	hasher)
		PYv="2"
		rmMainDir
		printf "progressbar\npasslib" > $TMPDIR/deps2drop
		alert
		;;
	kerbrute)
		PYv="2"
		rmMainDir
		printf "impacket" > $TMPDIR/deps2drop
		alert
		;;
	phonesploit)
		PYv="2"
		rmMainDir
		printf "colorama" > $TMPDIR/deps2drop
		alert
		;;
	pybelt)
		PYv="2"
		rmMainDir
		cat $TOOLS/$toRemove/deps2drop > $TMPDIR/deps2drop
		alert
		;;
	sqliv)
		yes|apt remove libxml2 libxml2-static libxml2-utils libxslt libxslt-static
		PYv="2"
		rmMainDir
		printf "terminaltables\ntermcolor\nnyawc" > $TMPDIR/deps2drop
		alert
		;;
	#::BASH::#
	login)
		if $(grep "login-termux" $INITFILE);then
			sed 's|/data/data/com.termux/files/usr/var/log/login-termux|/data/data/com.termux/files/usr/libexec/banner/wall-banner|g' -i $INITFILE
		else
			printf "$R\n(_>)─➤ Login is already inactive"
		fi
		;;
	userrecon)
		rmMainDir
		;;
	#::BIN::#
	adbfastboot)
		for BIN in adb adb.bin fastboot fastboot-armeabi;do
			if [[ -e $PREFIX/bin/$BIN ]];then
				rm -f $PREFIX/bin/$BIN
			fi
		done
		if [[ -d ~/adbfiles ]];then
			rm -rf ~/adbfiles
		fi
		;;
	code-server)
		yes|apt remove build-essential python git nodejs yarn
		yes|apt autoremove
		[[ -d ~/.config/code-server ]] && rm -rf ~/.config/code-server
		;;
	desktop-xfce4)
		yes|pkg remove xfce4 xfce4-taskmanager dosbox xfce4-terminal python-tkinter htop neofetch loqui vim-gtk the-powder-toy galculator xorg-xhost mpv-x ristretto xfce4-whiskermenu-plugin xfce4-clipman-plugin xarchiver tigervnc geany geany-plugins gtk3 gtk2 mtpaint leafpad hexchat netsurf recordmydesktop feh audacious;yes|pkg remove xfce4-* kvantum zenity mate-terminal mate-settings-daemon dbus-glib dconf termux-api wireshark-gtk
		for i in .vnc .icons .themes .config Desktop Downloads Templates Public Documents Pictures Video Music backgrounds;do
			if [[ ~/$toRemove ]]; then
				rm -rf ~/$i
			fi
		done
		for v in music stopdesktop startdesktop; do
			if [[ $PREFIX/bin/$v ]];then
				rm -rf $PREFIX/bin/$v
			fi
		done
		;;
	java)
		rmMainDir
		yes|apt remove aapt apksigner apksigner-old;yes|apt autoremove
		for i in java apktool signapk keytool;do
			rm -f $PREFIX/bin/$i
		done
		rm -rf $PREFIX/share/jdk8 $PREFIX/share/glib $PREFIX/var/spool
		;;
	localtunnel-server)
		npm uninstall localtunnel
		rm -rf $PREFIX/lib/node_modules/localtunnel
		;;
	serverapache)
		yes|apt remove php apache2 php-pgsql php-fpm php-apache mariadb phpmyadmin
		yes|apt autoremove
		rm -rf $PREFIX/etc/apache2 $PREFIX/etc/phpmyadmin
		if grep "$toRemove" $INITFILE;then
			sed 's|alias serverapache="apachectl"||g' -i $INITFILE
		fi
		;;
	torvpn)
		yes|apt remove tor torsocks proxychains-ng
		yes|apt autoremove
		rm -rf $PREFIX/etc/tor $PREFIX/etc/proxychains.conf
		for i in myip mypip swip ; do
			rm -f $PREFIX/bin/$i
		done
		;;
	youtubedr|youtube-dl|converter)
		if [[ $toRemove = youtube-dl ]];then
			PYv=""
			rmMainDir
			printf "$toRemove" > $TMPDIR/deps2drop
			alert
			rm -rf ~/.config/youtube-dl ~/bin ~/.netrc  $PREFIX/bin/termux-url-opener
		elif [[ $toRemove = youtubedr ]];then
			yes|apt remove $toRemove
		elif [[ $toRemove = converter ]];then
			rmMainDir
			rm -rf ~/.milux
		fi
		;;#::RUBY::#
	embed)
		yes|apt remove axel apksigner aapt
		rmMainDir
		;;
	metasploit)
		rmMainDir
		yes|apt remove patchelf metasploit;yes apt autoremove
		rm -rf $PREFIX/var/lib/postgresql $PREFIX/var/lib/postgresql
		;;
	#::GO::
	amass)
                goa=$(find ~/go/pkg/mod/github.com -type d -iname "!$toRemove"|head -n 1)
                rm -rf $gob $PREFIX/lib/go/src/$toRemove
		;;
	aquatone)
		rm -rf ~/go/pkg/mod/github.com/$toRemove ~/$toRemove
		gem remove --quiet --silent $toRemove $PREFIX/bin/$toRemove
		;;
	gobuster)
                gob=$(find ~/go/pkg/mod/github.com -iname $toRemove)
                rm -rf $gob $PREFIX/lib/go/src/$toRemove
		;;
	gophish)
                gop1=$(find ~/go/pkg/mod/github.com -type d -iname $toRemove|head -n 1)
                rm -rf $gop1
                ;;
	tangalanga)
                got=$(find ~/go/pkg/mod/github.com -type d -iname "$toRemove*")
		rm -rf $got
		;;
	virustotal)
		yes|apt remove $toRemove-cli
		for i in rm -rf ~/go/src/github.com/VirusTotal ~/go/bin/vt $PREFIX/bin/vt $PREFIX/etc/bash_completion.d/vt;do
			if [[ $i ]]; then
				rm -rf $i
			fi
		done
		;;
	#::ROOT::#
	aircrack-ng)
		yes|apt remove aircrack-ng ethtool macchanger
		;;
	bettercap)
		gem uninstall bettercap
		;;
	dnsenum)
		chk-sudo
		rmMainDir
		for repo in WWW::Mechanize Net::IP Net::DNS Net::Netmask XML::Writer String::Random ; do
			cpan uninstall $repo
		done
		if [[ -d $PREFIX/share/$toRemove ]];then
			sudo rm -f $PREFIX/share/$toRemove
		fi
		if [ -d ~/.$toRemove ];then
			rm -rf ~/.$toRemove
		fi
		;;
	webhackshl)
		rmMainDir
		printf "fierce" > $TMPDIR/deps2drop
		alert
		;;
	xerosploit)
		PYv="2"
		rmMainDir
		printf "tabulate\nterminaltables" > $TMPDIR/deps2drop
		alert
		;;
	sudo)
		chk-sudo
		sudo rm -rf ~/.suroot $PREFIX/bin/$toRemove
		;;
	*)
		printf "$R(_>)─➤$W Unable to locate $toRemove on i-Haklab\n"
                sleep 0.5
                printf "$G(_>)─➤$W Trying with Advance Packect Tool (APT)...\n"
                if [[ $(pkg list-all|grep -oE "$toRemove") ]];then
                        yes|apt remove $toRemove
                else
                        printf "$R(_>)─➤$W Tool $toRemove doesn't exist\n"
                        exit
                fi

		;;
esac
k-boom
#             i-Haklab by @Ivam3
