#!/bin/bash
#This file is part of i-Haklab command

if [ -d /data/data/com.termux/files/home/i-Haklab ]
then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

source $iHAKLAB/.set/libexec/colors
#source $iHAKLAB/.set/var/variables
#source $iHAKLAB/.set/functions/functions

STDERR() { printf "$Y\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n";}

if [ $1 = "upload" ]; then
	while [ $3 ]; do
		passwd="--password $3"
		break
	done
	if [ -e $2 ] || [ -d $2 ]; then
		file=$(mktemp)
		ffsend u $2 $passwd -y -q > $file.link
		link=$(cat $file.link)
		if [ ! -z $link ]; then
			printf "$G\n[+]-➤ Link to share :$W $link\n"
			rm $file.link
		else
			printf "$R\n\t      《ERR LINK》\n"
			STDERR
		fi
		rm $file;exit
	else
		printf "$R\t\t 《FILE DOESN'T EXISTS》\n"
		STDERR
		exit
	fi

elif [ $1 = "download" ]; then
	file=$(mktemp)
	ffsend exists $2 -I -y -q > $file.exists
	exists=$(cat $file.exists|head -n 1|awk -F " " '{print $2}')
	rm $file.exists
	if [ "$exists" = "true" ]; then
		ffsend d $2 -q
		printf "$G\t\t 《DOWNLOAD COMPLETED》\n"
	else
		printf "$R\t\t 《FILE DOESN'T EXISTS》\n"
		STDERR
	fi
	rm $file;exit
else
	STDERR
fi
