#!/usr/bin/bash
#This file is part of i-Haklab command
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
[[ $1 ]] || STDERR
if [ $1 = "upload" ]; then
	while [ $3 ]; do
		passwd="--password $3"
		break
	done
	if [ -e $2 ] || [ -d $2 ]; then
		file=$(mktemp)
		printf "$Y\t\t  《 UPLOADING ... 》\r";
		ffsend u $2 $passwd -y -q > $file.link
		link=$(cat $file.link)
		printf "$Y\t\t  《UPLOAD COMPLETED》\n"
		if [ ! -z $link ]; then
			printf "$G\n(_>)_Link_to_share─➤$W $link\n"
			rm $file.link
		else
			printf "$R\n\t      《ERR LINK》\n"
			STDERR
		fi
		rm $file;exit
	else
		printf "$R\t\t 《FILE DOESN'T EXISTS》\n"
		STDERR
		exit
	fi

elif [ $1 = "download" ]; then
	file=$(mktemp)
	ffsend exists $2 -I -y -q > $file.exists
	exists=$(cat $file.exists|head -n 1|awk -F " " '{print $2}')
	rm $file.exists
	if [ "$exists" = "true" ]; then
		printf "$Y\t\t 《 DOWNLOADING ... 》\n"
		ffsend d $2 -q
		banner
		printf "$G\r\t\t 《DOWNLOAD COMPLETED》\n"
	else
		printf "$R\t\t 《FILE DOESN'T EXISTS》\n"
		STDERR
	fi
	rm $file;exit
else
	STDERR
fi
