#!/bin/bash
#This file is part of i-Haklab command

if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab                                   else
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
fi

source $iHAKLAB/.set/libexec/colors
source $iHAKLAB/.set/var/variables
source $iHAKLAB/.set/functions/functions
chk-Cuser
chk-iHaklab

if [ ! -e $PREFIX/opt/metasploit-framework/documentation/api/apikey ]; then
	touch $PREFIX/opt/metasploit-framework/documentation/api/apikey
fi
APIKEYFILE=$PREFIX/opt/metasploit-framework/documentation/api/apikey
if [ ! $(cat $APIKEYFILE) ]; then
	printf "$Y[?]->$W Type your shodan APIKEY "
	while read -p ">> " ANSW && [ -z $ANSW ]; do
		printf "$R[w]-> Go to www.shodan.io to get your APIKEY$W\n"
                exit
        done
        echo $ANSW > $APIKEYFILE
fi

APIKEY=$(cat $APIKEYFILE)
if [ -e $iHAKLAB/.set/shodan/query ]; then
	printf "$Y[?]->$W Choose a type of search :\n"
	cat $iHAKLAB/.set/shodan/query | sort
        echo
	while read -p ">> " QUERY && [ -z $QUERY ]; do
		printf "$R"
        done
else
	printf "$R[w]-> ERROR :$W Not such query file\n"
fi

echo "use auxiliary/gather/shodan_search" > ~/java/handler/shodan-cam.rc
echo "set SHODAN_APIKEY $APIKEY" >> ~/java/handler/shodan-cam.rc
echo "set QUERY \"$QUERY\"" >> ~/java/handler/shodan-cam.rc
echo "run" >> ~/java/handler/shodan-cam.rc

printf "$Y[!]-> If some target need user/passwd you can use those :$W\n"
cat $iHAKLAB/.set/shodan/usrpasswd.txt
printf "\n\tpress$G ENTER$W to continue\n"
read enter
msfconsole -q -r ~/java/handler/shodan-cam.rc

