#!/usr/bin/bash
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
PS3="(_>)_number:─➤ "
STDERR(){ printf "$R(_➤)$W missing argument, type $(basename $0) -h for help";exit;}
if [[ $(basename $1) = games ]];then
	TMP_PATH=$PREFIX/bin
	printf "$Y(_➤)$W choose a game from the list below\n\n"
	select GAME in $(pkg list-all|grep gam|grep -iv game-repo|awk -F "/" '{print $1}') Exit;do
		if [[ $GAME = Exit ]];then
			exit
		elif [[ $GAME = cavez-of-phear ]];then
			command -v phear >/dev/null || yes|apt install $GAME
			exec $TMP_PATH/phear
		elif [[ $GAME = open-adventure ]];then
			command -v advent >/dev/null || yes|apt install $GAME
			exec $TMP_PATH/advent
		elif [[ $GAME = pacman4console ]];then
			command -v pacman >/dev/null || yes|apt install $GAME
			exec $TMP_PATH/pacman
		elif [[ $GANE = tty-solitaire ]];then
			command -v ttysolitaire >/dev/null || yes|apt install $GAME
			exec $TMP_PATH/ttysolitaire
		elif [[ $GAME = vitetris ]]; then
			command -v tetris >/dev/null || yes|apt install $GAME
			exec $TMP_PATH/tetris
		else
			command -v $GAME >/dev/null || yes|apt install $GAME
			exec $TMP_PATH/$GAME ${@:1}
		fi
		k-boom
	done
elif [[ $(basename $1) = tutorials ]];then
	STDERR() { printf "$R\n(_➤)$W Tutorial is not available on $PLATFORM\n";}
	select ANSW in $(cat $iHAKLAB/.set/libexec/Tutorials/List|awk '{print $4}') Exit;do
		[[ $ANSW = Exit ]] && exit
		printf "$G\n(_➤)$W Choose an options :$W\n"
		select WAY in Watch Download Exit;do
			case $WAY in
				Watch)
					printf "$G\n(_➤)$W Choose the platform :$W\n"
					select PLATFORM in YouTube Telegram Exit;do
						case $PLATFORM in
							YouTube)
								TUTO=$(cat $iHAKLAB/.set/libexec/Tutorials/List | grep $ANSW | awk '{print $2}')
								if [ $TUTO = "false" ] || [ -z $TUTO ];then
									STDERR;exit
								else
									termux-open-url $TUTO
								fi
								;;
							Telegram)
								TUTO=$(cat $iHAKLAB/.set/libexec/Tutorials/List | grep $ANSW | awk '{print $1}')
								if [ $TUTO = "false" ] || [ -z $TUTO ];then
									STDERR;exit
								else
									termux-open-url https://t.me/Ivam3byCinderella/$TUTO
								fi
								;;
							Exit|*)
								exit
								;;
						esac
					done
					;;
				Download)
					TUTO=$(cat $iHAKLAB/.set/libexec/Tutorials/List | grep $ANSW | awk '{print $2}')
					if [ $TUTO = 'false' ] || [ -z $TUTO ];then
						printf "$R\n(_➤)$W Tutorial is not available to be download\n";exit
					else
						youtubedr download $TUTO
					fi
					;;
				Exit|*)
					exit
					;;
			esac
		done
	done
elif [[ $(basename $1) = books ]];then
	select book in $(cat $iHAKLAB/.set/libexec/Books/List|awk '{print $1}') Exit;do
		link=$(cat -n $iHAKLAB/.set/libexec/Books/List|head -n $REPLY|tail -n 1|awk '{print $NF}')
		[[ -d $iHAKLAB/books ]] || mkdir -p $iHAKLAB/books
		if [[ $REPLY -le $(cat -n $iHAKLAB/.set/libexec/Books/List|tail -n 1|awk '{print $1}') ]];then
			chk-mega;megadl --path=$iHAKLAB/books/ https://mega.nz/$link;break
		elif [[ $book = Exit ]];then
			break
		else
			STDERR
		fi
	done
elif [[ $(basename $1) = QG ]];then
	select QG in $(ls $iHAKLAB/QuickGuides) Exit;do
		if [[ ! -z $QG ]] && [[ -e $iHAKLAB/QuickGuides/$QG ]];then
			bash $iHAKLAB/QuickGuides/$QG
		elif [[ $QG = Exit ]];then
			exit
		else
			STDERR
		fi
	done
elif [[ $(basename $1) = alltools ]];then
	cat -n $iHAKLAB/.set/libexec/Tools/listoftools
elif [[ $(basename $1) = instatools ]]; then
	file=$(mktemp)
	pkg list-installed|awk -F "/" '{print $1}' > $file
	for i in $(cat $HOME/.local/share/i-Haklab/.set/libexec/tools/listoftools);do
		if [[ -d $TOOLS/$i ]] || [[ -d $PREFIX/opt/$i ]] || [[ $(command -v $i) ]] || [[ -d $PREFIX/opt/$i-framework ]] || [[ -e ~/go/bin/$1 ]];then
			echo $i >> $file
		elif [[ $i = JohnTheRipper ]] && [[ -d $PREFIX/opt/john ]];then
			echo $i >> $file
		fi
	done
	printf "$G\n(_➤)$W Tools in PATH...\n"
	cat -n $file
	rm -f $file
else
	STDERR
fi
