#!/data/data/com.termux/files/usr/bin/bash
#i-Haklab v.3.1 2022 by Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3.
#Created on Jan/2019 
#Modify: 2022-04-25
####################
IFS=$'\n\t'
trap ctrl_c 2
yes|apt install curl &>/dev/null
bash <(curl -fsSL "https://raw.githubusercontent.com/ivam3/i-Haklab/master/setup.sh")
#      i-Haklab by @Ivam3
