#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done
if [ -d $iHAKLAB/../cryptovenom ]; then
        printf "$R[w]->$W Cryptovenom exist, uninstall it if you wanna reinstall\n"
        exit
fi
echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL CRYPTOVENOM. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
method1() {
	for module in base58 scrypt pyblake2 pycrypto crypto bcrypt rc2 twofish geesefly skein pycipher numpy Crypto passlib base91 mom gmpy2 more_itertools argon2_cffi ; do
	python2 -m pip install $module
done
}
method2() {
	printf "LDFLAGS=\"-L/system/lib/ -lm -lcompiler_rt\""
	for module in base58 scrypt pyblake2 pycrypto crypto bcrypt rc2 twofish geesefly skein pycipher numpy Crypto passlib base91 mom gmpy2 more_itertools argon2_cffi ; do
		python2 -m pip install $module --global-option="build_ext" --global-option="--disable-jpeg"
	done
}
method3() {
	export SODIUM_INSTALL=system
	for module in base58 scrypt pyblake2 pycrypto crypto bcrypt rc2 twofish geesefly skein pycipher numpy Crypto passlib base91 mom gmpy2 more_itertools argon2_cffi ; do
		python2 -m pip install --no-binary :all: $module
	done
}
git clone https://github.com/lockedbyte/cryptovenom $iHAKLAB/../cryptovenom
chmod 711 -R $iHAKLAB/../cryptovenom

printf "$Y[!]->$W There are 3 methods to install the repositories : choose one$Y\n[01]->$W BASIC$Y\n[02]->$W LDFLAGS$Y\n[03]->$W SODIUM\n\n"

while read -p "[*]:-> " ANSW && [ -z $ANSW ]; do
	continue
done
if [ $ANSW = '1' ] || [ $ANSW = '01' ]; then
	method1
elif [ $ANSW = '2' ] || [ $ANSW = '02' ]; then
	method2
elif [ $ANSW = '3' ] || [ $ANSW = '03' ]; then
	method3
else
	printf "$R[w]->$W method $ANSW doesn't exist\n"
	exit
fi
#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
