#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source $iHAKLAB/.set/var/variables

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/tools/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/usr/share/tools/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL SPECIAL COMMANDS. . . .$i"
        printf "\n\n"
        sleep 1
done

#INSTALLATION
if [ -d /data/data/com.termux/files/home/.config/fish/functions ]; then
	rm /data/data/com.termux/files/home/.config/fish/functions/*
else
	mkdir -p /data/data/com.termux/files/home/.config/fish/functions
fi
FNCDIR=/data/data/com.termux/files/home/.config/fish/functions
FNClist=$(ls $iHAKLAB/.set/functions)
for FNC in ${FNClist[*]}; do
	wget https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/functions/$FNC -O $FNCDIR/$FNC
	chmod +x $FNCDIR/*
done

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
