#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2
source $HOME/.local/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
chk-Cuser
chk-iHaklab

ctrl_c() { printf "$Y\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n";}
Set_Ak() {
	printf "$Y[!]$M Let's setting your access keys$W\n\n"
	printf "\n$Y [?]$W"
	while read -p "Type your Access Key >> " Ak1 && [ -z $Ak1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Y [?]$W"
	while read -p "Confirm your Access Key >> " Ak2 && [ -z $Ak2 ]; do
		printf "$R O-ops!!$W \n"
	done
	Define_Ak
	}
#
Define_Ak() {
	if [ $Ak1 = $Ak2 ]; then
		Ak=$Ak1
		printf "$Ak" > $TMPDIR/tmp-Ak
		chmod +w $HOME/.local/etc/i-Haklab/.Ivam3
		base64 $TMPDIR/tmp-Ak > $HOME/.local/etc/i-Haklab/.Ivam3
		chmod -w $HOME/.local/etc/i-Haklab/.Ivam3
		rm $TMPDIR/tmp-Ak
		Set_Q
	else
		printf "\n$R [W] Yours Access keys are diferents$W |$G please try again$W
		\n"
		sleep 2
		Set_Ak
	fi
}
#
Set_Q() {
	printf "$Y[!]$M Let's setting your security question$W\n\n"
	printf "\n$Y [?]$W Type your security question \n"
	while read -p " >> " Quiz1 && [ -z $Quiz1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Quiz1" > $TMPDIR/tmp-Quiz1
	Quiz1=$(base64 $TMPDIR/tmp-Quiz1)
	printf "$Y [!]$W Confirm your security question \n"
	while read -p " >> " Quiz2 && [ -z $Quiz2 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Quiz2" > $TMPDIR/tmp-Quiz2
        Quiz2=$(base64 $TMPDIR/tmp-Quiz2)
	Define_Quiz
        }
#
Define_Quiz() {
	if [ $Quiz1 = $Quiz2 ]; then
		Quiz=$Quiz1
		chmod +w $HOME/.local/etc/i-Haklab/.Quiz
		printf "$Quiz" > $HOME/.local/etc/i-Haklab/.Quiz
    chmod -w $HOME/.local/etc/i-Haklab/.Quiz
    rm -rf $TMPDIR/*
		Set_Answer
	else
		printf "\n$R [W] Your security questions are diferents$W |$G please try again$W\n\n"
    sleep 2
    Set_Q
	fi
}
#
Set_Answer() {
	printf "$Y [!]$M Let's setting your security answer$W\n\n"
	printf "\n$Y [?]$W Type your security answer \n"
	while read -p " >> " Anw1 && [ -z $Anw1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Anw1" > $TMPDIR/tmp-Anw1
	Anw1=$(base64 $TMPDIR/tmp-Anw1)
	printf "$Y [?]$W Confirm your security answer \n"
	while read -p " >> " Anw2 && [ -z $Anw2 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Anw2" > $TMPDIR/tmp-Anw2
  Anw2=$(base64 $TMPDIR/tmp-Anw2)
	Define_Answer
        }
#
Define_Answer() {
	if [ $Anw1 = $Anw2 ]; then
		Anw=$Anw1
    chmod +w $HOME/.local/etc/i-Haklab/.Cinderella
    printf "$Anw" > $HOME/.local/etc/i-Haklab/.Cinderella
    chmod -w $HOME/.local/etc/i-Haklab/.Cinderella
    rm -rf $TMPDIR/*
	else
		printf "\n$R [W] Your security answers are diferents$W |$G please try again$W\n\n"
    sleep 2
    Set_Answer
  fi
}
################
#LET'S TO START#
################
[[ -e $HOME/.local/etc/i-Haklab/login-termux ]] && rm -f $HOME/.local/etc/i-Haklab/login-termux
[[ -e $PREFIX/etc/bashito ]] && rm -f $PREFIX/etc/bashito
[[ -e $PREFIX/etc/motd ]] && rm -f $PREFIX/etc/motd
for i in Quiz Ivam3 Cinderella;do
	[[ -e $HOME/.local/etc/i-Haklab/.$i ]] || touch $HOME/.local/etc/i-Haklab/.$i
done
[[ -d $HOME/.local/etc/i-Haklab ]] || mkdir -p $HOME/.local/etc/i-Haklab
wget -q $iHDB/to-install/login-termux -O $HOME/.local/etc/i-Haklab/login-termux
wget -q $iHDB/libexec/banner/i-Haklab -O $HOME/.local/etc/i-Haklab/login-banner
cat <<- CONF > $HOME/.local/etc/i-Haklab/wall-banner
#!/usr/bin/bash
#Banner for i-Haklab created by @Ivam3 on Jan/2019
IFS=$'\n\t'
source $iHAKLAB/.set/var/variables
bash $HOME/.local/etc/i-Haklab/login-banner
#        i-Haklab by @Ivam3
CONF
chmod 711 -R $HOME/.local/etc/i-Haklab
Ak=SXZhbTNieUNpbmRlcmVsbGEK
chmod +w $HOME/.local/etc/i-Haklab/.Ivam3
printf "$Ak" > $HOME/.local/etc/i-Haklab/.Ivam3
chmod -w $HOME/.local/etc/i-Haklab/.Ivam3
Quiz=VGhlIGFjY2VzcyBrZXkgaXMgSXZhbTNieUNpbmRlcmVsbGEK
chmod +w $HOME/.local/etc/i-Haklab/.Quiz
printf "$Quiz" > $HOME/.local/etc/i-Haklab/.Quiz
chmod -w $HOME/.local/etc/i-Haklab/.Quiz
Anw=SXZhbTNieUNpbmRlcmVsbGEK
chmod +w $HOME/.local/etc/i-Haklab/.Cinderella
printf "$Anw" > $HOME/.local/etc/i-Haklab/.Cinderella
chmod -w $HOME/.local/etc/i-Haklab/.Cinderella

#ENDING SCRIPT
printf "$G\n (_>)-> :::::::::::::::::: DONE !! ::::::::::::::::::: <-(<_)$W\nFor more information about i-Haklab run i-Haklab about i-Haklab$Y\n\t   To fix issues going to$B t.me/Ivam3_Bot$W"
#       i-Haklab by @Ivam3
