#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
function Set_Ak {
printf "$Y[!]$M Let's setting your access keys$W\n\n"
printf "\n$Y [?]$W"
	while read -p "Type your Access Key >> " Ak1 && [ -z $Ak1 ]; do
		printf "$R O-ops!!$W \n"
	done
printf "$Y [?]$W"
	while read -p "Confirm your Access Key >> " Ak2 && [ -z $Ak2 ]; do
		printf "$R O-ops!!$W \n"
	done
	Define_Ak
	}
#
function Define_Ak {
	if [ $Ak1 = $Ak2 ]; then
		Ak=$Ak1
		printf "$Ak" > $PREFIX/libexec/termux/tmp-Ak
		chmod +w $PREFIX/libexec/termux/.Ivam3
		base64 $PREFIX/libexec/termux/tmp-Ak > $PREFIX/libexec/termux/.Ivam3
		chmod -w $PREFIX/libexec/termux/.Ivam3
		rm $PREFIX/libexec/termux/tmp-Ak
		Set_Q
	else
		printf "\n$R [W] Yours Access keys are diferents$W |$G please try again$W
		\n"
		sleep 2
		Set_Ak
	fi
}
#
function Set_Q {
printf "$Y[!]$M Let's setting your security question$W\n\n"
printf "\n$Y [?]$W Type your security question \n"
	while read -p " >> " Quiz1 && [ -z $Quiz1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Quiz1" > $PREFIX/libexec/termux/tmp-Quiz1
	Quiz1=$(base64 $PREFIX/libexec/termux/tmp-Quiz1)
printf "$Y [!]$W Confirm your security question \n"
	while read -p " >> " Quiz2 && [ -z $Quiz2 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Quiz2" > $PREFIX/libexec/termux/tmp-Quiz2
        Quiz2=$(base64 $PREFIX/libexec/termux/tmp-Quiz2)
	Define_Quiz
        }
#
function Define_Quiz {
        if [ $Quiz1 = $Quiz2 ]; then
		Quiz=$Quiz1
		chmod +w $PREFIX/libexec/termux/.Quiz
                printf "$Quiz" > $PREFIX/libexec/termux/.Quiz
                chmod -w $PREFIX/libexec/termux/.Quiz
                rm $PREFIX/libexec/termux/tmp-Quiz1
		rm $PREFIX/libexec/termux/tmp-Quiz2
		Set_Answer
        else
		printf "\n$R [W] Your security questions are diferents$W |$G please try again$W
                \n"
                sleep 2
                Set_Q
        fi
}
#
function Set_Answer {
printf "$Y [!]$M Let's setting your security answer$W\n\n"
printf "\n$Y [?]$W Type your security answer \n"
	while read -p " >> " Anw1 && [ -z $Anw1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Anw1" > $PREFIX/libexec/termux/tmp-Anw1
        Anw1=$(base64 $PREFIX/libexec/termux/tmp-Anw1)
printf "$Y [?]$W Confirm your security answer \n"
	while read -p " >> " Anw2 && [ -z $Anw2 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Anw2" > $PREFIX/libexec/termux/tmp-Anw2
        Anw2=$(base64 $PREFIX/libexec/termux/tmp-Anw2)
	Define_Answer
        }
#
function Define_Answer {
        if [ $Anw1 = $Anw2 ]; then
                Anw=$Anw1
                chmod +w $PREFIX/libexec/termux/.Cinderella
                printf "$Anw" > $PREFIX/libexec/termux/.Cinderella
                chmod -w $PREFIX/libexec/termux/.Cinderella
                rm $PREFIX/libexec/termux/tmp-Anw1
		rm $PREFIX/libexec/termux/tmp-Anw2
        else
		printf "\n$R [W] Your security answers are diferents$W |$G please try again$W
                \n"
                sleep 2
                Set_Answer
        fi
}
#
#			LET'S TO START
#
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi
while [ ! $(id -u) -ne 0 ]; do
        printf "$R\n[W]:-> You need to be a common user$W\n"
        exit
done
until [ -d $iHAKLAB ]; do
        printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
        while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
                continue
        done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
        git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else
        printf "$G[!]-> Have a nice hacking day!!\n"
        exit
fi
done
echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO SET LOGIN. . . .$i"
        printf "\n\n"
        sleep 1
done
if [ -e $PREFIX/var/log/login-termux.O ]; then
	mv $PREFIX/var/log/login-termux.O $PREFIX/var/log/login-termux.O2
fi
if [ -e $PREFIX/var/log/login-termux ]; then
	mv $PREFIX/var/log/login-termux $PREFIX/var/log/login-termux.O
fi
if [ -e $PREFIX/etc/bashito ]; then
	mv $PREFIX/etc/bashito $PREFIX/etc/bashito2
fi
if [ -e $PREFIX/etc/motd2 ]; then
	mv $PREFIX/etc/motd2 $PREFIX/etc/motd
fi
apt update && apt upgrade -y
apt install ruby
gem install lolcat
cat $PREFIX/etc/bash.bashrc > $PREFIX/etc/bashito
if [ -e $PREFIX/etc/motd ]; then
	mv $PREFIX/etc/motd $PREFIX/etc/motd2
fi
echo "command_not_found_handle() {" > $PREFIX/etc/bash.bashrc
echo "        /data/data/com.termux/files/usr/libexec/termux/command-not-found \"\$1\"" >> $PREFIX/etc/bash.bashrc
echo "}" >> $PREFIX/etc/bash.bashrc
echo "source /data/data/com.termux/files/usr/var/log/login-termux" >> $PREFIX/etc/bash.bashrc
echo "PS1=\"\[\e[33m\][!] \[\e[31m\]Type\[\e[32m\] exit\[\e[31m\] to log out\[\e[32m\] ➤ \[\e[m\]\"" >> $PREFIX/etc/bash.bashrc
echo "#				@Ivam3" >> $PREFIX/etc/bash.bashrc
if [ ! -e $PREFIX/libexec/termux/.Quiz ]; then
	touch $PREFIX/libexec/termux/.Quiz
fi
if [ ! -e $PREFIX/libexec/termux/.Ivam3 ]; then
	touch $PREFIX/libexec/termux/.Ivam3
fi
if [ ! -e $PREFIX/libexec/termux/.Cinderella ]; then
	touch $PREFIX/libexec/termux/.Cinderella
fi
if [ ! -d $PREFIX/libexec/banner ]; then
	mkdir -p $PREFIX/libexec/banner
fi
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/login-files/i-haklab_login -o $PREFIX/var/log/login-termux
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/banner/i-Haklab -o $PREFIX/libexec/banner/login-banner
echo "#!/data/data/com.termux/files/usr/bin/bash" > $PREFIX/libexec/banner/wall-banner
echo "# Banner for i-Haklab created by @Ivam3 on Jan/2019" >> $PREFIX/libexec/banner/wall-banner
echo "IFS=$'\n\t'" >> $PREFIX/libexec/banner/wall-banner
echo "source /data/data/com.termux/files/usr/libexec/colors" >> $PREFIX/libexec/banner/wall-banner
echo "bash /data/data/com.termux/files/usr/libexec/banner/login-banner" >> $PREFIX/libexec/banner/wall-banner
echo "fortune | lolcat" >> $PREFIX/libexec/banner/wall-banner
echo "echo" >> $PREFIX/libexec/banner/wall-banner
echo "fish" >> $PREFIX/libexec/banner/wall-banner
echo "#         	@Ivam3" >> $PREFIX/libexec/banner/wall-banner
chmod 711 $PREFIX/var/log/login-termux
chmod 711 -R $PREFIX/libexec/termux
chmod 711 -R $PREFIX/libexec/banner
#printf "$G[?]-> Do you wanna set loggin access to i-Haklab ?\n$Y[!]-> You can set it later executing$W $ i-Haklab install i-Haklab_login\n"
#while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
#	continue
#done
#if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	Set_Ak
#fi
Ak=SXZhbTNieUNpbmRlcmVsbGEK
chmod +w $PREFIX/libexec/termux/.Ivam3
printf "$Ak" > $PREFIX/libexec/termux/.Ivam3
chmod -w $PREFIX/libexec/termux/.Ivam3
Quiz=VGhlIGFjY2VzcyBrZXkgaXMgSXZhbTNieUNpbmRlcmVsbGEK
chmod +w $PREFIX/libexec/termux/.Quiz
printf "$Quiz" > $PREFIX/libexec/termux/.Quiz
chmod -w $PREFIX/libexec/termux/.Quiz
Anw=SXZhbTNieUNpbmRlcmVsbGEK
chmod +w $PREFIX/libexec/termux/.Cinderella
printf "$Anw" > $PREFIX/libexec/termux/.Cinderella
chmod -w $PREFIX/libexec/termux/.Cinderella

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#				IbyC
