#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2
source $PREFIX/share/i-Haklab/.set/var/variables
source $iHAKLAB/.set/functions/functions
chk-Cuser
chk-iHaklab

ctrl_c() { printf "$Y\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n";}
Set_Ak() {
printf "$Y[!]$M Let's setting your access keys$W\n\n"
printf "\n$Y [?]$W"
	while read -p "Type your Access Key >> " Ak1 && [ -z $Ak1 ]; do
		printf "$R O-ops!!$W \n"
	done
printf "$Y [?]$W"
	while read -p "Confirm your Access Key >> " Ak2 && [ -z $Ak2 ]; do
		printf "$R O-ops!!$W \n"
	done
	Define_Ak
	}
#
Define_Ak() {
	if [ $Ak1 = $Ak2 ]; then
		Ak=$Ak1
		printf "$Ak" > $PREFIX/libexec/termux/tmp-Ak
		chmod +w $PREFIX/libexec/termux/.Ivam3
		base64 $PREFIX/libexec/termux/tmp-Ak > $PREFIX/libexec/termux/.Ivam3
		chmod -w $PREFIX/libexec/termux/.Ivam3
		rm $PREFIX/libexec/termux/tmp-Ak
		Set_Q
	else
		printf "\n$R [W] Yours Access keys are diferents$W |$G please try again$W
		\n"
		sleep 2
		Set_Ak
	fi
}
#
Set_Q() {
printf "$Y[!]$M Let's setting your security question$W\n\n"
printf "\n$Y [?]$W Type your security question \n"
	while read -p " >> " Quiz1 && [ -z $Quiz1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Quiz1" > $PREFIX/libexec/termux/tmp-Quiz1
	Quiz1=$(base64 $PREFIX/libexec/termux/tmp-Quiz1)
printf "$Y [!]$W Confirm your security question \n"
	while read -p " >> " Quiz2 && [ -z $Quiz2 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Quiz2" > $PREFIX/libexec/termux/tmp-Quiz2
        Quiz2=$(base64 $PREFIX/libexec/termux/tmp-Quiz2)
	Define_Quiz
        }
#
Define_Quiz() {
        if [ $Quiz1 = $Quiz2 ]; then
		Quiz=$Quiz1
		chmod +w $PREFIX/libexec/termux/.Quiz
                printf "$Quiz" > $PREFIX/libexec/termux/.Quiz
                chmod -w $PREFIX/libexec/termux/.Quiz
                rm $PREFIX/libexec/termux/tmp-Quiz1
		rm $PREFIX/libexec/termux/tmp-Quiz2
		Set_Answer
        else
		printf "\n$R [W] Your security questions are diferents$W |$G please try again$W
                \n"
                sleep 2
                Set_Q
        fi
}
#
Set_Answer() {
printf "$Y [!]$M Let's setting your security answer$W\n\n"
printf "\n$Y [?]$W Type your security answer \n"
	while read -p " >> " Anw1 && [ -z $Anw1 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Anw1" > $PREFIX/libexec/termux/tmp-Anw1
        Anw1=$(base64 $PREFIX/libexec/termux/tmp-Anw1)
printf "$Y [?]$W Confirm your security answer \n"
	while read -p " >> " Anw2 && [ -z $Anw2 ]; do
		printf "$R O-ops!!$W \n"
	done
	printf "$Anw2" > $PREFIX/libexec/termux/tmp-Anw2
        Anw2=$(base64 $PREFIX/libexec/termux/tmp-Anw2)
	Define_Answer
        }
#
Define_Answer() {
        if [ $Anw1 = $Anw2 ]; then
                Anw=$Anw1
                chmod +w $PREFIX/libexec/termux/.Cinderella
                printf "$Anw" > $PREFIX/libexec/termux/.Cinderella
                chmod -w $PREFIX/libexec/termux/.Cinderella
                rm $PREFIX/libexec/termux/tmp-Anw1
		rm $PREFIX/libexec/termux/tmp-Anw2
        else
		printf "\n$R [W] Your security answers are diferents$W |$G please try again$W
                \n"
                sleep 2
                Set_Answer
        fi
}
################
#LET'S TO START#
################
[[ -e $PREFIX/var/log/login-termux ]] && rm -f $PREFIX/var/log/login-termux
[[ -e $PREFIX/etc/bashito ]] && rm -f $PREFIX/etc/bashito
[[ -e $PREFIX/etc/motd ]] && rm -f $PREFIX/etc/motd
for i in Quiz Ivam3 Cinderella;do
	[[ -e $PREFIX/libexec/termux/.$i ]] || touch $PREFIX/libexec/termux/.Quiz
done
[[ -d $PREFIX/libexec/banner ]] || mkdir -p $PREFIX/libexec/banner
wget -q $iHDB/login-files/i-haklab_login -O $PREFIX/var/log/login-termux
wget -q $iHDB/libexec/banner/i-Haklab -O $PREFIX/libexec/banner/login-banner
cat <<- CONF > $PREFIX/libexec/banner/wall-banner
#!/usr/bin/bash
#Banner for i-Haklab created by @Ivam3 on Jan/2019
IFS=$'\n\t'
source $iHAKLAB/.set/var/variables
bash /data/data/com.termux/files/usr/libexec/banner/login-banner
#        i-Haklab by @Ivam3
CONF
chmod 711 $PREFIX/var/log/login-termux
chmod 711 -R $PREFIX/libexec/termux
chmod 711 -R $PREFIX/libexec/banner
Ak=SXZhbTNieUNpbmRlcmVsbGEK
chmod +w $PREFIX/libexec/termux/.Ivam3
printf "$Ak" > $PREFIX/libexec/termux/.Ivam3
chmod -w $PREFIX/libexec/termux/.Ivam3
Quiz=VGhlIGFjY2VzcyBrZXkgaXMgSXZhbTNieUNpbmRlcmVsbGEK
chmod +w $PREFIX/libexec/termux/.Quiz
printf "$Quiz" > $PREFIX/libexec/termux/.Quiz
chmod -w $PREFIX/libexec/termux/.Quiz
Anw=SXZhbTNieUNpbmRlcmVsbGEK
chmod +w $PREFIX/libexec/termux/.Cinderella
printf "$Anw" > $PREFIX/libexec/termux/.Cinderella
chmod -w $PREFIX/libexec/termux/.Cinderella

#ENDING SCRIPT
printf "$G\n(_>)-> :::::::::::::::::: DONE !! ::::::::::::::::::: <-(<_)$W\nFor more information about $1 run i-Haklab show $1$Y\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#       i-Haklab by @Ivam3
