#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

ctrl_c(){ printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL John The Ripper. . . .$i"
        printf "\n\n"
        sleep 1
done

#INSTALLATION
JTRv="1.8.0"
JTRtar="https://download.openwall.net/pub/projects/john/contrib/android/john-$JTRv-android-1.tar.gz"

for del in $PREFIX/bin/john $iHAKLAB/../JohnTheRipper $PREFIX/opt/john $TMPDIR/john-$JTRv-android;do
	if [ -e $del ] || [ -d $del ];then
		rm -rf $del
	fi
done

yes|pkg update && pkg upgrade && pkg install wget
wget -q $JTRtar -O $TMPDIR/john-$JTRv-android-1.tar.gz
cd $TMPDIR;tar -xvzf john-$JTRv-android-1.tar.gz
rm -rf john-$JTRv-android-1.tar.gz
mkdir -p $PREFIX/opt/john
JTR="$PREFIX/opt/john"
mv $TMPDIR/john-$JTRv-android/user/* $JTR
ln -s $JTR/john.conf $JTR/john.ini
case $(uname -m) in
#	declare -a arch=(arm64-v8a  armeabi  armeabi-v7a  mips  mips64  x86  x86_64)
    aarch64)
        mv $TMPDIR/john-$JTRv-android/libs/arm64-v8a/* $JTR
        ;;
    arm)
        mv $TMPDIR/john-$JTRv-android/libs/armeabi/* $JTR
        ;;
    armhf)
        mv $TMPDIR/john-$JTRv-android/libs/armeabi-v7a/* $JTR
        ;;
    i686)
        mv $TMPDIR/john-$JTRv-android/libs/x86/* $JTR
        ;;
    x86_64)
        mv $TMPDIR/john-$JTRv-android/libs/x86_64/* $JTR
        ;;
esac
rm -rf $TMPDIR/john-$JTRv-android
chmod +x $JTR/*
echo "#!/data/data/com.termux/files/usr/bin/bash" > $PREFIX/bin/john
echo "#This script find and execute johntheripper tool" >> $PREFIX/bin/john
echo "#" >> $PREFIX/bin/john
echo "R='\033[1;31m'"  >> $PREFIX/bin/john
echo "W='\033[0m'" >> $PREFIX/bin/john
echo " " >> $PREFIX/bin/john
echo "if [ -d $PREFIX/opt/john ];then" >> $PREFIX/bin/john
echo "        cd $PREFIX/opt/john" >> $PREFIX/bin/john
echo "        ./john \$@" >> $PREFIX/bin/john
echo "else" >> $PREFIX/bin/john
echo "        printf \"\$R[ERROR]─➤ JohnTheRipper is not installed\$W\"" >> $PREFIX/bin/john
echo "fi" >> $PREFIX/bin/john
echo "#            @Ivam3" >> $PREFIX/bin/john
chmod +x $PREFIX/bin/john

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
