#!/data/data/com.termux/files/usr/bin/bash
#Coded by Ivam3 on Dec/2018
#
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/home/.local/share/i-Haklab/.set/var/variables
Cinderella=$(base64 -d $HOME/.local/etc/i-Haklab/.Ivam3)
Seque=$(base64 -d $HOME/.local/etc/i-Haklab/.Quiz)
Secan=$(base64 -d $HOME/.local/etc/i-Haklab/.Cinderella)
ctrl_c() { printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}

change_ak(){
	clear
	source $HOME/.local/etc/i-Haklab/login-banner;sleep 1
	printf "$C"
	until read -n 2 -p "                 < Configuration Menu >

            1) Get one new Access Key.
            2) Change your Security question.
            3) Change your Security answer.
            4) Uninstall i-Haklab.
            0) Exit
            >> " Chak && [ $Chak -lt 5 ]; do
    	echo $(clear)
			source $HOME/.local/etc/i-Haklab/login-banner
			printf "$C\n"
		done
		sleep 1
		case_Chak
	}

case_Chak(){
	case $Chak in
		1)
			echo $(clear)
			source $HOME/.local/etc/i-Haklab/login-banner
			printf "$C                  Confirm your access"
			echo "
			"
			while read -s -p "            $Seque >> " Quiz && [ -z $Quiz ]; do
				printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$C \n"
			done
			if [ $Quiz = $Secan ];then
				printf "$C"
				while read -s -p "
            New access key >>  " Newak1 && [ -z $Newak1 ];do
						printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$C"
				done
				printf "$C"
				while read -s -p "
            Type it once again to confirm >>  " Newak2 && [ -z $Newak2 ]; do
						printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$C"
				done
				if [ $Newak1 = $Newak2 ];then
					Newak=$Newak1
					echo;set_ak
				else
					printf "$R
          O-ops!!  IT DOESN'T MATCH Try again$W \n"
					sleep 1
					echo;case_Chak
				fi
			else
				printf "$R\n                    Access denied$W \n"
				sleep 1;change_ak
			fi
			;;
		2)
			printf "$G\n"
			while read -s -p "            Confirm your Access Key >>  " Ivam3 && [ -z $Ivam3 ];do
				printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$G \n"
				sleep 1
			done	
			if [ $Ivam3 = $Cinderella ]; then
				printf "$G"
				while read -p "
            Write your New security question >>  " NewQ && [ -z $NewQ ]; do
					printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$G \n"
				done
				set_quiz
			else
				printf "$R\n                     Access denied$W \n"
				sleep 1
				echo $(clear)
				change_ak
			fi
			;;
		3)
			printf "$G\n"
			while read -s -p "            Confirm your Access Key >>  " Ivam3 && [ -z $Ivam3 ];do
				printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$G \n"
  		done
			if [ $Ivam3 = $Cinderella ];then
				printf "$G"
        while read -s -p "
            Write your New security Answer >>  " NewA && [ -z $NewA ];do
						printf "$Y
          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$G"
        done
				set_answ
			else
				printf "$R\n                     Access denied \n"
        sleep 1
        echo $(clear)
        change_ak
      fi
			;;
		4)
			printf "$B"
			while read -s -p "                    >> ACCESS KEY <<
				" Ivam3 && [ -z $Ivam3 ];do
				printf "$R
                     Access denied$B\n"
	    done
			if [ $Ivam3 = $Cinderella ]; then
				source $HOME/.local/etc/i-Haklab/login-banner
				printf "$Y
        [!!]:->$R i-Haklab will be uninstall$Y<-:[!!]
                It could take a while ...\n"
				sleep 3
				for erase in Music downloads Desktop Pictures bin storage Documents Public Video java go adbfiles .bashrc .beef .local/ .milux .msf4 .ngrok2 .tor .w3m .npm .recon-ng .suroot .ssh .gem .weechat .wfuzz;do
					[[ -d $HOME/$erase ]] && rm -rf $HOME/$erase > /dev/null 2>/dev/null
				done
				[[ -d $TOOLS ]] && rm -rf $TOOLS > /dev/null 2>/dev/null
				rm -rf $PREFIX > /dev/null 2>/dev/null
				printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\nThank you for use i-Haklab, see you at the next hack$W\n"
				sleep 3
				clear
				exec reset
			else
				printf "$R
                     Access denied$B\n"
				sleep 1
				main
			fi
			;;
		0)
			main
			;;
	esac
}

set_ak() {
	printf "$Newak" > $HOME/.local/etc/i-Haklab/.tmp-ak
	chmod +w $HOME/.local/etc/i-Haklab/.Ivam3
	base64 $HOME/.local/etc/i-Haklab/.tmp-ak > $HOME/.local/etc/i-Haklab/.Ivam3
	chmod -w $HOME/.local/etc/i-Haklab/.Ivam3
	rm $HOME/.local/etc/i-Haklab/.tmp-ak
	check-Ak
}

set_quiz() {
	printf "$NewQ" > $HOME/.local/etc/i-Haklab/.tmp-quiz
	chmod +w $HOME/.local/etc/i-Haklab/.Quiz
	base64 $HOME/.local/etc/i-Haklab/.tmp-quiz > $HOME/.local/etc/i-Haklab/.Quiz
	chmod -w $HOME/.local/etc/i-Haklab/.Quiz
	rm $HOME/.local/etc/i-Haklab/.tmp-quiz
	printf "$Y            Your Security Question was changed$W"
	sleep 3
	echo $(clear)
	source $HOME/.local/etc/i-Haklab/login-termux
}

set_answ() {
	printf "$NewA" > $HOME/.local/etc/i-Haklab/.tmp-answ
	chmod +w $HOME/.local/etc/i-Haklab/.Cinderella
	base64 $HOME/.local/etc/i-Haklab/.tmp-answ > $HOME/.local/etc/i-HAklab/.Cinderella
	chmod -w $HOME/.local/etc/i-Haklab/.Cinderella
	rm $HOME/.local/etc/i-Haklab/.tmp-answ
	printf "\n\n$G            Your Security Answer was changed$W"
	sleep 3
	echo $(clear)
	source $HOME/.local/etc/i-Haklab/login-termux
}

check-Ak() {
	echo
	if [ $Newak = $Cinderella ];then
		printf "\n\n$G             Your Access Key was changed $W"
		sleep 5
		echo $(clear)
		source $HOME/.local/etc/i-Haklab/login-termux
	else
		printf "$R
    O-ops!!   Something was wrong"
   		echo $(clear)
		source $HOME/.local/etc/i-Haklab/login-termux
	fi
}

# LOGIN
main() {
	for opt in 1 2 3 4; do
		let try=opt++
		echo $(clear)
		source $HOME/.local/etc/i-Haklab/login-banner
		printf "$B"
		while read -s -p "                  (_>) ACCESS KEY (<_)
	    >>or type 'IbyC' for settings<<
			" Ivam3 && [ -z $Ivam3 ];do
			printf "$R
                     Access denied$B\n"
		done
		if [ $Ivam3 = $Cinderella ]; then
			echo $(clear)
			source $HOME/.local/etc/i-Haklab/wall-banner
			break
		elif [ $Ivam3 = "IbyC" ]; then
			sleep 2
			change_ak
		else
			printf "$R
		     Access denied$Y\n\t\t      (try $try - 3)\n"
			sleep 1
			echo
		fi
	done

	if [ $try -gt 3 ]; then
		printf "$Y                 O-ops!! Too many tries$W"
		sleep 3
		echo $(clear)
		source $HOME/.local/etc/i-Haklab/login-banner
		printf "$Y"
		printf "        [!] Let's try with the security question$G\n\n"
		
		while read -s -p "             $Seque " Quiz && [ -z $Quiz ]; do
			printf "\n\n$Y          [!]:->$R t.me/Ivam3byCinderella$Y <-:[!]$W \n"
		done

		if [ $Quiz = $Secan ]; then
			printf "$W"
			echo $(clear)
			source $HOME/.local/etc/i-Haklab/wall-banner
		else
			printf "$R\n\t\t      Access denied$W \n"
			sleep 1
			main
		fi
	fi
}
main
#				IbyC
