#!/data/data/com.termux/files/usr/bin/bash
#Created on Jan/2019
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
version="5.0.8"
TMP_DIR=$PREFIX/opt/metasploit-framework
APK=$TMP_DIR/lib/msf/core/payload/apk.rb
function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL METASPLOIT FRAMEWORK. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
Instamsf() {
	if [ -d ~/metasploit-framework ]; then
		rm -rf ~/metasploit-framework
	fi
	if [ -d $TMP_DIR ]; then
		rm -rf $TMP_DIR
	fi
dpkg --configure -a
apt update --fix-missing -y && pkg upgrade -y
apt install -y util-linux autoconf util-linux bison clang coreutils axel curl findutils git apr apr-util libffi-dev libgmp-dev libpcap-dev postgresql-dev readline-dev libsqlite-dev openssl-dev libtool libxml2-dev libxslt-dev ncurses-dev pkg-config wget make ruby-dev libgrpc-dev termux-tools ncurses-utils ncurses unzip zip tar postgresql termux-elf-cleaner -y
pkg install unstable-repo -y
pkg install --reinstall ruby -y
pkg install metasploit -y
ln -sf $PREFIX/include/libxml2/libxml $PREFIX/include/
#GARBAGE
if [ -d $TMP_DIR/installer.sh ]; then
        rm -rf ~$TMP_DIR/installer.sh
fi
if [ -e $TEMP_DIR/msfupdate ]; then
        rm $TMP_DIR/msfupdate
fi
#MSFUPDATE
git clone https://github.com/ivam3/ivam3.github.io.git $PREFIX/tmp/Ivam3
mv $PREFIX/tmp/Ivam3/master/mediafire/metasploit/msfupdate $PREFIX/bin/msfupdate
chmod 777 $PREFIX/bin/msfupdate
cp $PREFIX/bin/msfupdate $TMP_DIR/
#RuGiR
mv $PREFIX/tmp/Ivam3/master/mediafire/metasploit/RuGiR $TMP_DIR/RuGiR
echo "#!/bin/bash" > $PREFIX/bin/RuGiR
echo "#This file will help you to run RuGiR on the rigth way" >> $PREFIX/bin/RuGiR
echo "#(Ru)by (G)ems (i)ssues (R)esolved was created by @Ivam3" >> $PREFIX/bin/RuGiR
echo "cd $HOME/metasploit-framework" >> $PREFIX/bin/RuGiR
echo "./RuGiR" >> $PREFIX/bin/RuGiR
echo "#                 @IVAM3" >> $PREFIX/bin/RuGiR
chmod 777 $TMP_DIR/RuGiR
chmod 777 $PREFIX/bin/RuGiR
rm -rf $PREFIX/tmp/Ivam3
#FIX ARGUMENT -X
mv $APK $APK.O
wget https://raw.githubusercontent.com/ivam3/java/master/.embed/apk.rb -O $APK
}
if [ -d ~/metasploit-framework ] || [ -d $TMP_DIR ]; then
	printf "$R[?]->$W Metasploit already exist$R |$W Do you want re-install it?\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
	if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
		instamsf
	else
		printf "$G\n[!]-> Keeping Metasploit...\n\n"
		sleep 1
	fi
else
	Instamsf
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
