#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors
arch=$(uname -a | grep -o 'arm' | head -n1)
arch2=$(uname -a | grep -o 'Android' | head -n1)

ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL NGROK. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
Advice() {
	printf "$Y\n[!]-> NGROK tunnels are only available after you sign up.\n      Sign up at: https://ngrok.com/signup\n\n      If you have already signed up, make sure your authtoken is installed.\n      Your authtoken is available\n      on your dashboard: https://dashboard.ngrok.com\n$W"
}
Install() {
	command -v wget 
	if [ $arch == 'arm' ] || [ $arch2 == 'Android' ] ; then
		wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1
		if [ -e ngrok-stable-linux-arm.zip ]; then
			unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
			chmod +x ngrok
			rm -rf ngrok-stable-linux-arm.zip
		else
			printf "$R[w]-> ERROR :$W Can't download ngrok\n"
			exit
		fi
	else
		wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1
		if [ -e ngrok-stable-linux-386.zip ]; then
			unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
			chmod +x ngrok
			rm -rf ngrok-stable-linux-386.zip
		else
			printf "$R[w]-> ERROR :$W Can't download ngrok\n"
			exit
		fi
	fi
	ENDING-SCRIPT
        }
function ENDING-SCRIPT {
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
}
if [ -e $PREFIX/bin/ngrok ]; then
        printf "$Y\n\n[!]:-> Ngrok file already exists | Do you wanna re-install it ?"
        while read -p -n 2 "$G\n[y/Y|N/n]:->$W " yesorno [ -z $yesorno ]; do
                printf "$R\n[W] O-ops!!$W\n"
        done
        if [ $yesorno = 'y' -o $yesorno = 'Y' ]; then
                rm $PREFIX/bin/ngrok
                Install
		Advice
        else
                ENDING-SCRIPT
        fi
else
        Install
	Advice
fi
#                                               @Ivam3
