#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL PHONEINFOGA. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
arch=$(uname -a | grep -o 'arm' | head -n1)
arch2=$(uname -a | grep -o 'Android' | head -n1)
if [ $arch == 'arm' ] || [ $arch2 == 'Android' ] ; then
	bits=32
else
	bits=64
fi
Basic() {
        for module in phonenumbers selenium bs4 google_api config html5lib ; do
		python -m pip install $module
	done
}
LDFLAGS() {
        export LDFLAGS="-L/system/lib/ -lm -lcompiler_rt"
        for module in phonenumbers selenium bs4 google_api config html5lib ; do
                python -m pip install $module --global-option="build_ext" --global-option="--disable-jpeg"
        done
}
SODIUM() {
        export SODIUM_INSTALL=system
        for module in phonenumbers selenium bs4 google_api config html5lib ; do
                python -m pip install --no-binary :all: $module
        done
}

command -v termux-info > /dev/null 2>&1 || pkg install termux-api termux-tools -y > /dev/null 2>&1

SOversion=$(termux-info | grep -oE '([5-9]{1}\.)([0-9]{1}\.)([0-9]{1})' | awk -F "." '{print $1}')

pkg update && pkg upgrade -y

if [ $SOversion => '7' ]; then
	pkg install unstable-repo
fi

for repo in git python python2 geckodriver ; do
	pkg install $repo -y
done
command -v geckodriver > /dev/null 2>&1 || cd $iHAKLAB/.set/to-install;tar -xvf geckodriver-v0.24.0-linux$bits.tar.gz.zip;mv geckodriver $PREFIX/bin/;chmod +x $PREFIX/bin/geckodriver; /dev/null 2>&1
for version in python python2 ; do
        $version -m pip install --upgrade pip
done

git clone https://github.com/sundowndev/PhoneInfoga.git $iHAKLAB/../PhoneInfoga
pushd $iHAKLAB/../PhoneInfoga
wget https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/fix-tools/phoneinfoga.py -O $iHAKLAB/../PhoneInfoga/phoneinfoga.py

printf "$Y[!]->$W There are 3 methods to install the repositories : choose one$Y\n[01]->$W BASIC$Y\n[02]->$W LDFLAGS$Y\n[03]->$W SODIUM\n\n"

while read -p "[*]:-> " ANSW && [ -z $ANSW ]; do
        continue
done
if [ $ANSW = '1' ] || [ $ANSW = '01' ]; then
        Basic
elif [ $ANSW = '2' ] || [ $ANSW = '02' ]; then
        LDFLAGS
elif [ $ANSW = '3' ] || [ $ANSW = '03' ]; then
        SODIUM
else
        printf "$R[w]->$W method $ANSW doesn't exist\n"
        exit
fi
cp config.example.py config.py
popd

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#                                               @Ivam3
