#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL QUACK. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
if [ -d $iHAKLAB/../quack ]; then
	rm -rf $iHAKLAB/../quack
fi
Basic() {
        for module in phonenumbers requests scapy wget argparse ; do
                for py in python python2 ; do
			$py -m pip install $module
		done
        done
}
LDFLAGS() {
        export LDFLAGS="-L/system/lib/ -lm -lcompiler_rt"
        for module in phonenumbers requests scapy wget argparse⏎; do
                for py in python python2 ; do
			$py -m pip install $module --global-option="build_ext" --global-option="--disable-jpeg"
		done
        done
}
SODIUM() {
        export SODIUM_INSTALL=system
        for module in phonenumbers requests scapy wget argparse ; do
                for py in python python2 ; do
			$py -m pip install --no-binary :all: $module
		done
        done
}
pkg update && pkg upgrade -y
pkg install -y git python python2
#git clone https://github.com/entynetproject/quack.git $iHAKLAB/../quack
wget https://github.com/ivam3/i-Haklab/raw/master/.set/to-install/quack.zip
unzip quack.zip -d $iHAKLAB/../
rm quack.zip
chmod 711 -R $iHAKLAB/../quack
for file in bin install.sh uninstall.sh ; do
	if [ -e $iHAKLAB/../quack/$file ] || [ -d $iHAKLAB/../quack/$file ]; then
		rm -rf $iHAKLAB/../quack/$file
	fi
done
printf "$Y\n[!]->$W There are 3 methods to install the repositories : choose one$Y\n[01]->$W BASIC$Y\n[02]->$W LDFLAGS$Y\n[03]->$W SODIUM\n\n"

while read -p "[*]:-> " ANSW && [ -z $ANSW ]; do
        continue
done
if [ $ANSW = '1' ] || [ $ANSW = '01' ]; then
        Basic
elif [ $ANSW = '2' ] || [ $ANSW = '02' ]; then
        LDFLAGS
elif [ $ANSW = '3' ] || [ $ANSW = '03' ]; then
        SODIUM
else
        printf "$R[w]->$W method $ANSW doesn't exist\n"
        exit
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#                                               @Ivam3
