#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

ctrl_c(){
	printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
	if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]
	then
		git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
		cd ~/i-Haklab;bash setup
	else 
		printf "$G[!]-> Have a nice hacking day!!\n"
		exit
	fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
	printf "$(clear) $C STARTING TO INSTALL SQLMAP. . . .$i"
        printf "\n\n"
        sleep 1
done

#::::::::INSTALLATION:::::::::#
Termux(){
	for i in unstable-repo sqlmap; do
		PKG=$(pkg list-all|grep -o $i)
		if [ ! -z "$PKG" ]
		then
			printf "$G\n[+]─➤$W Installing the repository $i $W\n"
			yes|pkg install $i >/dev/null 2>&1
		else
			printf "$R\n[w]─➤$W The repository $i is not candidate$W\n"
			sleep 1
		fi
	done
}

Python(){
	yes|pkg install python python2 git
	for i in python python2 ; do
		$i -m pip --no-color install --upgrade pip -q
		$i -m pip --no-color install sqlmap -q
	done
}
Github(){
	if [ -d $iHAKLAB/../sqlmap ]; then
		rm -rf $iHAKLAB/../sqlmap
	fi
	git clone https://github.com/sqlmapproject/sqlmap $iHAKLAB/../sqlmap
	chmod 711 -R $iHAKLAB/../sqlmap
}

printf "$C#::::::::::::::::::::::::::::::::::::#$Y\n[!?]->$W Choose a type of installation$G\n[01]->$W Termux repositories$G\n[02]->$W Github$G\n[03]->$W Python-pip modules\n"
while read -p "[R]-> " ANSW && [ -z $ANSW ]; do
	continue
done
yes|pkg update && pkg upgrade
case $ANSW in
	01|1)
		Termux
		;;
	02|2)
		Github
		;;
	03|3)
		Python
		;;
	*)
		ctrl_c
		exit
		;;
esac

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
