#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

ctrl_c(){ printf "$Y\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n";}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL STEGSNOW. . . .$i"
        printf "\n\n"
        sleep 1
done

#INSTALLATION
if [ -e $PREFIX/bin/snow ];then
	rm $PREFIX/bin/snow
fi

yes|pkg update && pkg upgrade && pkg install wget make automake
wget http://http.kali.org/pool/main/s/stegsnow/stegsnow_20130616.orig.tar.gz -O $TMPDIR/stegsnow_20130616.orig.tar.gz
if [ -e $TMPDIR/stegsnow_20130616.orig.tar.gz ]; then
	cd $TMPDIR;tar -xvzf $TMPDIR/stegsnow_20130616.orig.tar.gz
	if [ -d $TMPDIR/snow-20130616 ]; then
		cd $TMPDIR/snow-20130616/
		make
		if [ -e $TMPDIR/snow-20130616/snow ]; then
			mv $TMPDIR/snow-20130616/snow $PREFIX/bin
			rm -rf $TMPDIR/snow-20130616/
			rm -rf $TMPDIR/stegsnow_20130616.orig.tar.gz
			chmod +x $PREFIX/bin/snow
		else
			printf "$R\n\t      《ERR BUILD》\n"
			ctrl_c
			exit
		fi
	else
		printf "$R\n\t      《ERR TAR》\n"
		ctrl_c
		exit
	fi
else
	printf "$R\n\t      《ERR WGET》\n"
	ctrl_c
	exit
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
