#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL THEHARVESTER. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
if [ -d $iHAKLAB/../theHarvester ]; then
        rm -rf $iHAKLAB/../theHarvester
fi
Basic() {
        python -m pip install -r requirements.txt
}
LDFLAGS() {
        export LDFLAGS="-L/system/lib/ -lm -lcompiler_rt"
        python -m pip install --global-option="build_ext" --global-option="--disable-jpeg" -r requirements.txt
}
SODIUM() {
        export SODIUM_INSTALL=system
        python -m pip install --no-binary :all: -r requirements.txt
}
pkg update && pkg upgrade -y
pkg install git python python2 libxml2 libxml2-static libxml2-utils libxslt libxslt-static -y
for version in python python2 ; do
        $version -m pip install --upgrade pip
done
git clone https://github.com/laramies/theHarvester.git $iHAKLAB/../theHarvester
pushd $iHAKLAB/../theHarvester
printf "$Y[!]->$W There are 3 methods to install the repositories : choose one$Y\n[01]->$W BASIC$Y\n[02]->$W LDFLAGS$Y\n[03]->$W SODIUM\n\n"

while read -p "[*]:-> " ANSW && [ -z $ANSW ]; do
        continue
done
if [ $ANSW = '1' ] || [ $ANSW = '01' ]; then
        Basic
elif [ $ANSW = '2' ] || [ $ANSW = '02' ]; then
        LDFLAGS
elif [ $ANSW = '3' ] || [ $ANSW = '03' ]; then
        SODIUM
else
        printf "$R[w]->$W method $ANSW doesn't exist\n"
        exit
fi
sed -i 's%/etc/theHarvester%/data/data/com.termux/files/usr/etc/theHarvester%g' setup.py
python setup.py install
popd

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
