#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL WEBHACKSHL. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
Basic() {
        for module in fierce ; do
		python -m pip install $module
	done
}
LDFLAGS() {
        printf "LDFLAGS=\"-L/system/lib/ -lm -lcompiler_rt\""
        for module in fierce ; do
                python -m pip install $module --global-option="build_ext" --global-option="--disable-jpeg"
        done
}
SODIUM() {
        export SODIUM_INSTALL=system
        for module in fierce ; do
                python -m pip install --no-binary :all: $module
        done
}
apt update && apt upgrade -y
apt install git curl python2 python tor ruby nmap -y
for version in python python2 ; do
        $version -m pip install --upgrade pip
done
git clone https://github.com/sechacklabs/webhackshl.git $iHAKLAB/../webhackshl
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/checker.py -o $iHAKLAB/../webhackshl/modules/checker.py
printf "$Y[!]->$W There are 3 methods to install the repositories : choose one$Y\n[01]->$W BASIC$Y\n[02]->$W LDFLAGS$Y\n[03]->$W SODIUM\n\n"

while read -p "[*]:-> " ANSW && [ -z $ANSW ]; do
        continue
done
if [ $ANSW = '1' ] || [ $ANSW = '01' ]; then
        Basic
elif [ $ANSW = '2' ] || [ $ANSW = '02' ]; then
        LDFLAGS
elif [ $ANSW = '3' ] || [ $ANSW = '03' ]; then
        SODIUM
else
        printf "$R[w]->$W method $ANSW doesn't exist\n"
        exit
fi

#
#SQLMAP
command -v sqlmap || bash $iHAKLAB/.set/to-install/sqlmap
#
#NIKTO
if [ ! -d $iHAKLAB/../nikto ]; then
	bash $iHAKLAB/.set/to-install/nikto
fi
if [ ! -d ~/.nikto/program ]; then
	mkdir -p ~/.nikto/program
fi
cp $iHAKLAB/../nikto/program/nikto.pl ~/.nikto/program/
#
#WHATWEB
if [ ! -d $iHAKLAB/../whatweb ]; then
	bash $iHAKLAB/.set/to-install/whatweb
fi
if [ ! -d ~/.whatweb ]; then
	mkdir -p ~/.whatweb
fi
cp $iHAKLAB/../whatweb/whatweb ~/.whatweb/
#
#WPSCAN
if [ ! -d $iHAKLAB/../wpscan ]; then
	bash $iHAKLAB/.set/to-install/wpscan
fi
#
#DNSENUM
command -v dnsenum > /dev/null || bash $iHAKLAB/.set/to-install/dnsenum
if [ ! -d ~/.dnsenum ]; then
	mkdir -p ~/.dnsenum
fi
cp $PREFIX/bin/dnsenum ~/.dnsenum/dnsenum.pl

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#                                               @Ivam3
