#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL WEBHACKSHL. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
apt update && apt upgrade -y
apt install git curl python2 python2-dev python python-dev tor ruby nmap -y
git clone https://github.com/sechacklabs/webhackshl.git $iHAKLAB/../webhackshl
python -m pip install fierce
command -v dnsenum > /dev/null || bash $iHAKLAB/.set/to-install/dnsenum
if [ ! -d ~/.dnsenum ]; then
	mkdir -p ~/.dnsenum
fi
cp $PREFIX/bin/dnsenum ~/.dnsenum/dnsenum.pl
command -v sqlmap || bash $iHAKLAB/.set/to-install/sqlmap
if [ ! -d $iHAKLAB/../nikto ]; then
	bash $iHAKLAB/.set/to-install/nikto
fi
if [ ! -d ~/.nikto/program ]; then
	mkdir -p ~/.nikto/program
fi
cp $iHAKLAB/../nikto/program/nikto.pl ~/.nikto/program/
if [ ! -d $iHAKLAB/../whatweb ]; then
	bash $iHAKLAB/.set/to-install/whatweb
fi
if [ ! -d ~/.whatweb ]; then
	mkdir -p ~/.whatweb
fi
cp $iHAKLAB/../whatweb/whatweb ~/.whatweb/
if [ ! -d $iHAKLAB/../wpscan ]; then
	bash $iHAKLAB/.set/to-install/wpscan
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#                                               @Ivam3
