#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "       [yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup-lite
else 
	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C STARTING TO INSTALL XEROSPLOIT. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
TMPPATH=$PREFIX/opt/xerosploit
RUROOT=$(bash $iHAKLAB/.set/to-install/check-root)
if [ "$RUROOT" = "root" ]; then
	if [ -d $TMPPATH/xerosploit ]; then
		rm -rf $TMPPATH/xerosploit
	fi
	yes|pkg update && pkg upgrade && pkg install git nmap hping3 build-essential python python2 ruby git libpcap
	git clone https://github.com/LionSec/xerosploit.git $TMPPATH/xerosploit
	for i in python2 python ; do
		$i -m pip install tabulate terminaltables
	done
	chmod +x -R $TMPPATH/tools
	cd $TMPPATH/tools/bettercap/
	gem build bettercap.*
	gem install xettercap-*
	for del in xettercap-* $TMPPATH/run.sh $TMPPATH/xerosploit.py;do
		rm -rf $del
	done
	curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/fix-tools/xerosploit.py -o $TMPPATH/xerosploit.py
else
	printf "$R\n[W]:-> You need to be root to get Xerosploit$W\n"
        sleep 1
	exit
fi

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n   To fix issues going to$B t.me/Ivam3_Bot$W"
#                                               @Ivam3
