#!/data/data/com.termux/files/usr/bin/bash
#Created on Dec/2018
IFS=$'\n\t'
trap ctrl_c 2
source /data/data/com.termux/files/usr/libexec/colors

function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n\n"
}
if [ ! -d ~/storage ]; then
        termux-setup-storage
fi
if [ -L ~/storage/external-1 ]; then
	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
else
        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -d $iHAKLAB ]; do
	printf "$R\n[W]:-> i-Haklab needed$W |$Y Do you wanna install it?$W\n"
	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
		continue
	done
if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
        cd ~/i-Haklab;bash setup
else 
	printf "$G[!]-> Have a nice hacking day!!\n"
	exit
fi
done

echo $(clear)
for i in  ------------------@ IVAM3-------------@ IVAM3-by----------@ IVAM3-by-CINDERELLA; do
        printf "$(clear) $C INSTALLING YOUTUBE-DL-DOWNLOADER BY MILUX. . . .$i"
        printf "\n\n"
        sleep 1
done
#INSTALLATION
GabiTeplea() {
dpkg --configure -a
yes | pkg update && pkg upgrade
if [ -d $PREFIX/lib/python3.7/site-packages/youtube_dl ]; then
	yes | pip uninstall youtube_dl
fi
printf "$G[!]-> INSTALLING YOUTUBE-DL BY GABI TIPLEA$W\n"
sleep 1
yes | pkg install util-linux wget curl python python2
yes | python -m pip install youtube-dl
if [ -d $HOME/youtube-dl ]; then
	rm -rf $HOME/youtube-dl
fi
mkdir -p $HOME/.config/youtube-dl
ln -s $PREFIX/bin $HOME/bin
curl https://raw.githubusercontent.com/ivam3/youtube-dl/master/.data/.netrc -o $HOME/.netrc
chmod 711 $HOME/.netrc
curl https://raw.githubusercontent.com/ivam3/youtube-dl/master/.data/LhDxGbtY -o $PREFIX/bin/termux-url-opener
dos2unix $PREFIX/bin/termux-url-opener
chmod 711 $PREFIX/bin/termux-url-opener
}


############## BY_MILUX ####################
FILE="https://raw.githubusercontent.com/miluxmil/milux/master"
yes | pkg update && pkg upgrade && pkg install wget
if [ ! -d ~/.milux ]
then
        mkdir ~/.milux
fi
if [ -L ~/bin ]
then
        ln -s $PREFIX/bin ~/bin
fi

for i in termux-url-opener update; do
        wget $FILE/$i -O $PREFIX/bin/update -q
        chmod +x $PREFIX/bin/$i
done
source ~/bin/update
_FIX
touch $HOME/.milux/date

#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
