#!/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2
source $HOME/.local/etc/i-Haklab/variables
source $iHETC/functions
chk-pkg proot-distro proot-distro

running time 2

[[ -d $PREFIX/var/lib/proot-distro/installed-rootfs/alpine/ ]] || {
  prrot-distro install alpine
}
banner
proot-distro login alpine --user $USER
