#!/usr/bin/bash
trap ctrl_c 2
ctrl_c(){ rm $TMPDIR/pkg2up.txt;exit;}

echo "Searching for new updates ..."
apt update >/dev/null 2>/dev/null
[[ -e $TMPDIR/pkg2up.txt ]] || { apt list --upgradable 2>/dev/null|awk '{print $1}'|grep -iv "Listing..." > $TMPDIR/pkg2up.txt;}

declare -a depends=($(cat $TMPDIR/pkg2up.txt|awk '{print $1}'|cut -f1 -d'/'|tr '\n' ' '))
declare -a packages=($(cat $TMPDIR/pkg2up.txt|awk '{print $1}'|cut -f2 -d'/'|tr '\n' ' '))
declare -A pkg2keep=

if [[ "${#depends[*]}" -gt "0" ]]; then
  echo "Installing :"
  for (( i=0; i<${#depends[*]}; i++ )); do
    pkg2up[${depends[$i]}]="${packages[$i]}"
    echo -en "Dependency ${depends[$i]} in package ${packages[$i]} "
    while read -p "[y/n]: " yesornot && [ -z $yesornot ]; do
      continue
    done
    if [[ "$yesornot" == "y" ]] || [[ "$yesornot" == "Y" ]]; then
      yes|apt install ${depends[$i]}
    else
      [[ "${depends[$i]}" == "webkit2gtk-4.1:" ]] && { unset ${depends[$i]} && depends+=([webkit2gtk]="x11");}
      pkg2keep+=(["${depends[$i]}"]="${packages[$i]}")
    fi
  done
else
  echo "All packages are up to date."
fi
echo "Dependencies keeped : ${#pkg2keep[*]}"
[[ "${#pkg2keep[*]}" -gt "0" ]] || [[ -z "${#pkg2keep[*]}" ]] && {
  for i in ${!pkg2keep[*]}; do
    echo "$i - ${pkg2keep[$i]}"
  done
}
ctrl_c
