#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2
source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions

chk-pkg ssh openssh
banner

[[ -e ${HOME}/.ssh/id_rsa.pub ]] && {
	printf $G"(_➤)$W Running Ngrok server by SSH connection.";
	ssh -R 443:localhost:$argv -oHostKeyAlgorithms=+ssh-rsa \
		-oPubkeyAcceptedKeyTypes=+ssh-rsa tunnel.us.ngrok.com;} || {
		chk-ssh;
			printf $R"ERROR:$W Ngrok is not set$R |$W run i-Haklab tutorials for a guide\n";
}
