#!/data/data/com.termux/files/usr/bin/bash
args=$1

source ${HOME}/.local/etc/i-Haklab/functions
chk-pkg termux-toast termux-api
chk-pkg termux-fingerprint termux-api
chk-pkg openssl openssl-tool

[[ $args = set ]] && { pass Set;}
[[ $args = pass ]] && { pass New;}
[[ $args = get ]] && {
	trap ctrl_c 2;
	ctrl_c(){ pass Get;};
	pass Get;}
[[ $args = fingerprint ]] && {
	trap ctrl_c 2;
	ctrl_c(){ pass Fingerprint;};
	pass Fingerprint;}

