#!/data/data/com.termux/files/usr/bin/bash
source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions

chk-pkg termux-toast termux-api
chk-pkg termux-fingerprint termux-api
chk-pkg openssl openssl-tool

[[ $# -eq 0 ]] && { STDERR;}

args=$1

[[ $args = get ]] && {
	trap ctrl_c 2;
	ctrl_c(){ pass Get;};
	pass Get;
}
[[ $args = fingerprint ]] && {
	trap ctrl_c 2;
	ctrl_c(){ pass Fingerprint;};
	pass Fingerprint;
}

if [[ $args = set ]]
then
	pass Set
elif [[ $args = new ]]
then
	pass New
else
	STDERR
fi

