#!/data/data/com.termux/files/usr/bin/bash
#Created on July/2021
IFS=$'\n\t'
trap ctrl_c 2
source $HOME/.local/etc/i-Haklab/variables
source $iHETC/functions

[[ -z $APIKEY_phonescan ]] && { echo -en "${R}E:${W} An API Key is required, set it running 'i-Haklab setapikey'";exit 1;}
banner
if [[ $1 ]] && [ "$1" -eq "$1" ] 2>/dev/null
then
	num="$1"
	url="http://apilayer.net/api/validate?access_key=$APIKEY_phonescan&number=$num&country_code=&format=1"
	[[ $(expr length $num) -ne 12 ]] && Err
	printf "$Y\n  Scanning phonenumber :$W $num$G\n  ________________________________________________________\n"
	printTable '_' "$(curl -s $url|tail -n 11|tr -d "\}|\"|,"|tr "_" " "|tr ":" "_")"
	printf "  ________________________________________________________$W\n\n"
	tput cnorm;exit
else
	STDERR
fi
