#!/data/data/com.termux/files/usr/bin/bash

IFS=$'\n\t'
set -e # Exit immediately if a command exits with a non-zero status
trap ctrl_c 2 

source ${HOME}/.local/etc/i-Haklab/functions 
source ${HOME}/.local/etc/i-Haklab/variables

chk-pkg qemu-system-x86_64 qemu-system-x86-64-headless
chk-pkg qemu-img qemu-utils

rootDir=${TOOLS}/vm_extracted
mkdir -p $rootDir
tmpdir=$(mktemp -d)

ctrl_c() {
    rm -rf $tmpdir 2>/dev/null
    k-boom
    exit 1
}

findfile() {
    local ext=$1
    find $tmpdir -type f -name "$ext" | head -n 1
}

setVM() {
    local imgFile=$1

    while read -p "Ports to forward (e.g., 2222:22,8080:80) or press Enter to use defaults: " ports; do
        if [[ -z $ports ]]; then
            break
        elif [[ $ports =~ ^([0-9]+:[0-9]+)(,[0-9]+:[0-9]+)*$ ]]; then
            portForwardArgs=""
            IFS=',' read -ra portMappings <<< "$ports"
            for mapping in "${portMappings[@]}"; do
                host_port=${mapping%%:*}
                guest_port=${mapping##*:}
                portForwardArgs+=",hostfwd=tcp::${host_port}-:${guest_port}"
            done
            break
        else
            echo "[!] Invalid format. Please use the format host_port:guest_port[,host_port:guest_port,...]"
        fi
    done

    [[ ! -z $portForwardArgs ]] && {
        echo "[+] Starting the VM with custom port forwarding ..."
    }
    initVM "$imgFile" $portForwardArgs
}

initVM() {
    local imgFile=$1
    local defaultPortForward=",hostfwd=tcp::2222-:22,hostfwd=tcp::8080-:80,hostfwd=tcp::2323-:23"
    portForwardArgs="${2:-$defaultPortForward}"

    echo -en "[+] Starting the VM ...\n[+] "
    qemu-system-x86_64 -m 2048 -smp 2 \
        -cpu qemu64,+avx,+avx2 -vga virtio -full-screen \
        -drive file=$imgFile,format=qcow2 \
        -netdev user,id=n1$portForwardArgs \
        -display default,show-cursor=on \
        -device e1000,netdev=n1 \
        -boot c
    exit 0
}


# EXTRACT THE TAR FILES
creatImgFile() {
    local zipfile=$1 
    echo "[+] Extracting files from ${zipfile##*/} ..."
    unzip -qq -o $zipfile -d $tmpdir
    ovaFile=$(findfile "*.ova")

    [[ ! -z $ovaFile ]] && {
        echo "[+] Extracting files from ${ovaFile##*/} ..."
        tar -xf $ovaFile -C $tmpdir 
        vmdkFile=$(findfile "*.vmdk") 

        [[ ! -z $vmdkFile ]] && {
            echo "[+] Converting file ${vmdkFile##*/} ..."
            qemu-img convert -f vmdk -O qcow2 $vmdkFile ${vmdkFile%.*}.qcow2
            qcow2File=$(findfile "*.qcow2")
            
            [[ ! -z $qcow2File ]] && { 
                mv $qcow2File $rootDir/${qcow2File##*/}
                echo "[+] Image file saved as: ${qcow2File##*/}"
                rm -rf $tmpdir 
                imgFile=$rootDir/${qcow2File##*/}
                setVM $imgFile
            }
        } || { 
            echo -e "[!] No VMDK file found inside the OVA archive."
            rm -rf $tmpdir
            exit 3
        }
    } || {
        echo -e "[!] No OVA file found inside the ZIP archive."
        rm -rf $tmpdir
        exit 2
    }
}

# MAIN
[[ $1 ]] && [[ -e $1 ]] && [[ $1 == *.zip ]] && {
    creatImgFile $1
} || { 
    echo "[!] Tip: bring a ZIP file to create a new one '$0 <zipfile>'"
    echo "[+] Available extracted VM images:"
    select img in $(ls $rootDir) Exit; do
        case $img in
            Exit)
                ctrl_c
                ;; 
            *)
                [[ -e $rootDir/$img ]] && {
                    imgFile=$rootDir/$img
                    break
                } || {
                    echo -e "[!] Invalid selection."
                }
                ;;
        esac
    done
    setVM $imgFile
}
