#!/data/data/com.termux/files/usr/bin/bash

IFS=$'\n\t'
set -e # Exit immediately if a command exits with a non-zero status
trap ctrl_c 2 

source ${HOME}/.local/etc/i-Haklab/functions 
source ${HOME}/.local/etc/i-Haklab/variables

chk-pkg qemu-system-x86_64 qemu-system-x86-64-headless
chk-pkg qemu-img qemu-utils

rootDir=${TOOLS}/vm_extracted
mkdir -p $rootDir
tmpdir=$(mktemp -d)

ctrl_c() {
    rm -rf $tmpdir 2>/dev/null
    k-boom
    exit 1
}

findfile() {
    local ext=$1
    find $tmpdir -type f -name "$ext" | head -n 1
}

setVM() {
    local imgFile=$1
    echo -en "$G[+]$W Ports to forward or press ${G}Enter$W to use defaults\n"
    while read -p " ╰──(e.g., 2222:22,8080:80): " ports; do
        if [[ -z $ports ]]; then
            break
        elif [[ $ports =~ ^([0-9]+:[0-9]+)(,[0-9]+:[0-9]+)*$ ]]; then
            local portForwardArgs=""
            IFS=',' read -ra portMappings <<< "$ports"
            for mapping in "${portMappings[@]}"; do
                host_port=${mapping%%:*}
                guest_port=${mapping##*:}
                portForwardArgs+=",hostfwd=tcp::${host_port}-:${guest_port}"
            done
            break
        else
            echo -e "$R[E] Invalid format.$W Please use the format: ${Y}host_port:guest_port,host_port:guest_port,$W..."
        fi
    done

    [[ ! -z $portForwardArgs ]] && {
        echo -en "$G[+]$W Starting the VM with custom port forwarding ...\n"
    }
    initVM "$imgFile" "$portForwardArgs"
}

initVM() {
    local imgFile="$1"
    local customPortForward="$2"
    local defaultPortForward=",hostfwd=tcp::2222-:22,hostfwd=tcp::8080-:80,hostfwd=tcp::2323-:23"
    local portForwardArgs="${customPortForward:-$defaultPortForward}"
    local ports="${portForwardArgs#,}"
    local rules=""

    IFS=',' read -ra rules <<< "$ports"

    for rule in "${rules[@]}"; do
        host_port=$(echo "$rule" | sed -n 's|.*::\([0-9]*\)-:.*|\1|p')
        guest_port=$(echo "$rule" | sed -n 's|.*-:\([0-9]*\).*|\1|p')
        
        echo -en "$Y[i]$W Forwarding port $G$host_port$W to guest port $Y$guest_port$W\n"
    done
    echo -en "$G[+]$W Starting the VM ...\n"
    echo -en "$G[+]$W "
    qemu-system-x86_64 -m 2048 -smp 2 \
        -drive file=$imgFile,format=qcow2 \
        -netdev user,id=net0,restrict=off$portForwardArgs \
        -device e1000,netdev=net0 \
        -boot c
    exit 0
}


# EXTRACT THE TAR FILES
creatImgFile() {
    local zipfile=$1 
    echo -en "$G[+]$W Extracting files from $G${zipfile##*/}$W ...\n"
    unzip -qq -o $zipfile -d $tmpdir
    ovaFile=$(findfile "*.ova")

    [[ ! -z $ovaFile ]] && {
        echo -en "$G[+]$W Extracting files from $G${ovaFile##*/}$W ...\n"
        tar -xf $ovaFile -C $tmpdir 
        vmdkFile=$(findfile "*.vmdk") 

        [[ ! -z $vmdkFile ]] && {
            echo -en "$G[+]$W Converting file $G${vmdkFile##*/}$W ...\n"
            qemu-img convert -f vmdk -O qcow2 $vmdkFile ${vmdkFile%.*}.qcow2
            qcow2File=$(findfile "*.qcow2")
            
            [[ ! -z $qcow2File ]] && { 
                mv $qcow2File $rootDir/${qcow2File##*/}
                echo -en "$G[+]$W Image file saved as: $G${qcow2File##*/}$W\n"
                rm -rf $tmpdir 
                imgFile=$rootDir/${qcow2File##*/}
                setVM $imgFile
            }
        } || { 
            echo -en "$R[E]$W No VMDK file found inside the OVA archive.\n"
            rm -rf $tmpdir
            exit 3
        }
    } || {
        echo -en "$R[E]$W No OVA file found inside the ZIP archive.\n"
        rm -rf $tmpdir
        exit 2
    }
}

# MAIN
banner
[[ $1 ]] && [[ -e $1 ]] && [[ $1 == *.zip ]] && {
    creatImgFile $1
} || { 
    echo -en "$Y[!] Tip:$W bring a ZIP file to create a new one '${Y}i-Haklab $0 <zipfile>$W'\n"
    echo -en "$G[+]$W Available extracted VM images:\n"
    select img in $(ls $rootDir | grep ".qcow2") Exit; do
        case $img in
            Exit)
                ctrl_c
                ;; 
            *)
                [[ -e $rootDir/$img ]] && {
                    imgFile=$rootDir/$img
                    break
                } || {
                    echo -en "$R[E]$W Invalid selection.\n"
                }
                ;;
        esac
    done
    setVM $imgFile
}
