#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2
source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions

ask(){
  echo -en "${Y}[!]${W} An API key exists. Overwrite it? "
  while read -p "[y/n]: " yesornot && [ -z $yesornot ]; do
    continue
  done
  [[ "$yesornot" == "n" ]] || [[ "$yesornot" == "N" ]] && { echo -en "$Y[!]$W Aborting ...";sleep 1;exit;}
}

getApiKey(){
  echo -en "$G[+]$W API Key for $platform\n"
  while read -p " ╰──➤ " apikey && [ -z $apikey ];do
    continue
  done
}

setApiKey(){
  varkey=$(grep "APIKEY_$platform" $iHETC/variables)
  sed -i "s|$varkey|export APIKEY_$platform=\"$apikey\"|" $iHETC/variables
  echo -en "${G}DONE!!$W New API key added sucessfully"
}


banner
echo -en "$Y[!]$W Get a PhoneScan API key on:$B https://numverify.com/dashboard$W\n"
echo -en "$Y[!]$W Get an OpenAI API key on:$B https://platform.openai.com/account/api-keys\n"
echo -en "$Y[!]$W Get an MistralAI API key on:$B https://console.mistral.ai\n"
echo -en "$Y[!]$W Get an Gemini API key on:$B https://aistudio.google.com\n"
echo -en "$Y[!]$W Get an DeepSeek API key on:$B https://api-docs.deepseek.com/\n"
echo -en "$Y[!]$W Get an Claude API key on:$B https://console.anthropic.com/\n"
echo -en "$Y[!]$W Get an Groq API key on:$B https://console.groq.com/keys\n"
echo -en "$Y[!]$W Get an OpenRouter API key on:$B https://openrouter.ai/settings/keys\n"
echo -en "$Y[!]$W Get an Together AI API key on:$B https://api.together.ai/settings/api-keys\n"
echo -en "$Y[!]$W Get an Kimi AI API key on:$B https://platform.moonshot.cn/console/api-keys\n"
echo -en "$Y[!]$W Get a TestSprite API key on:$B https://www.testsprite.com/dashboard/settings/apikey\n"
echo "[?] Choose the api key to set:"
select platform in chatGPT claude deepseek gemini mistralAI groq openrouter togetherai kimi neural phonescan testsprite cancel;do
  case $platform in
      chatGPT|claude|deepseek|gemini|mistralAI|groq|openrouter|togetherai|kimi|neural|phonescan|testsprite)
      [[ -z "$(eval "echo \$APIKEY_$platform")" ]] || { ask;}
      getApiKey
      setApiKey
      break
      ;;
    cancel)
      exit 0
      ;;
  esac
done
