#!/data/data/com.termux/files/usr/bin/bash
#This file is part of i-Haklab command
IFS=$'\n\t'
trap ctrl_c 2
source $HOME/.local/etc/i-Haklab/variables
source $iHETC/functions

internal(){
	chk-pkg ffsend ffsend
	usage(){
		printf $Y"USAGE:$W i-Haklab share <options>\n\n   OPTIONS\tDESCRIPTION\n-h\t\tShow this menu\n-u <file/dir>\tFile or directory to share\n-d <link>\tCloud's link to download file or directory\n-p <password>\tSet a pasword to share o download [optional]\n";exit 0
	}

	command -v ffsend >dev/null || yes|apt install ffsend

	banner
	[[ $# -eq 0 ]] && { usage;}
	while getopts f:u:d:h opts; do
		echo uno
		case $opts in
			h) usage
				;;
			d) link=$OPTARG
				until ping -q -c1 -W 1 $link >/dev/null 2>/dev/null
				do
					printf "$R(_➤)$W ERROR 404 : Not found$W\n"
					exit
				done
				;;
			u) toshare=$OPTARG
				[[ -e $toshare ]] || [[ -d $toshare ]] || {
					printf "$R\t\t 《FILE DOESN'T EXISTS》\n"
								exit;} 
				;;
			p) pass=$OPTARG
				passwd="--password $pass"
				;;
			*) echo tres;usage
				;;
		esac

		file=$(mktemp)
		if [[ -n $toshare ]]
		then
			printf "$Y\t\t  《 UPLOADING ... 》\r";
			ffsend u $toshare $passwd -y -q > $file.link
			link=$(cat $file.link)
			printf "$Y\t\t  《UPLOAD COMPLETED》\n"
			if [ ! -z $link ]; then
				printf "$G\n(_>)_Link_to_share─➤$W $link\n"
				rm $file.link
			else
				printf "$R\n\t      《ERR LINK》\n"
				exit
			fi
		else
			file=$(mktemp)
			ffsend exists $link -I -y -q > $file.exists
			exists=$(cat $file.exists|head -n 1|awk -F " " '{print $2}')
			rm $file.exists
			if [ "$exists" = "true" ]; then
				printf "$Y\t\t 《 DOWNLOADING ... 》\n"
				ffsend d $link -q
				printf "$G\r\t\t 《DOWNLOAD COMPLETED》\n"
			else
				printf "$R\t\t 《FILE DOESN'T EXISTS》\n"
				exit
			fi
		fi
		rm $file
	done
}

chk-pkg php php
chk-pkg lt localtunnel
getPORT
[[ -d ${HOME}/.local/var/service/www/veno-file-manager ]] && {
	banner;
	php -S $LOOPBACK:$LPORT -t ${HOME}/.local/var/service/www/veno-file-manager/vfm 2>>$LOGFILE &
	sleep 3;
	echo -en $B"(➤_)$W Web server$B 2Share$W activated over:\n$B  ╰──➤$W LAN your url is: http://$LOOPBACK:$LPORT$B\n  ╰──➤$W TUN "
	lt -h "http://localtunnel.me" -p $LPORT -s i-haklab-2share --open --print-requests;
} || STDERR

