#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2
source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions
PS3="(_>)_number:─➤ "

#UPDATE TUTORIALS LIST
chk-pkg curl curl
curl -sSL "$iHDB/.local/etc/i-Haklab/listoftutorials" -o $iHETC/listoftutorials 2>>"$LOGFILE"

banner
if [[ $# -eq 0 ]]
then
	STDERR
elif [[ $1 = tutorials ]]
then
  ERR() { printf "$R\n(_➤)$W Tutorial is not available on $PLATFORM\n";}
  select ANSW in $(cat $iHETC/listoftutorials|awk '{print $4}') Exit;do
		[[ $ANSW = Exit ]] && exit
		printf "$G\n(_➤)$W Choose an options :$W\n"
		select WAY in Watch Download Exit;do
			case $WAY in
				Watch)
					printf "$G\n(_➤)$W Choose the platform :$W\n"
					select PLATFORM in YouTube Telegram Exit;do
						case $PLATFORM in
							YouTube)
								TUTO=$(cat $iHETC/listoftutorials|grep $ANSW|awk '{print $2}'|head -n 1)
								if [ $TUTO = "false" ] || [ -z $TUTO ];then
									ERR;exit
								else
									termux-open-url $TUTO
								fi
								;;
							Telegram)
								TUTO=$(cat $iHETC/listoftutorials|grep $ANSW|awk '{print $1}'|head -n 1)
								if [ $TUTO = "false" ] || [ -z $TUTO ];then
									ERR;exit
								else
									termux-open-url https://t.me/Ivam3byCinderella/$TUTO
								fi
								;;
							Exit|*)
								exit
								;;
						esac
					done
					;;
				Download)
					chk-pkg youtubedr youtubedr
					TUTO=$(cat $iHETC/listoftutorials|grep $ANSW|awk '{print $2}'|head -n 1)
					if [[ $TUTO = 'false' ]] || [[ -z $TUTO ]];then
						printf "$R\n(_➤)$W Tutorial is not available to be download\n";exit
					else
						youtubedr download $TUTO
					fi
					;;
				Exit|*)
					exit
					;;
			esac
		done
	done
elif [[ $1 = books ]]
then
	chk-pkg megadl megatools
	select book in $(cat $iHETC/listofbooks|awk '{print $1}') Exit;do
		link=$(cat -n $iHETC/listofbooks|head -n $REPLY|tail -n 1|awk '{print $NF}')
		if [[ $REPLY -le $(cat -n $iHETC/listofbooks|tail -n 1|awk '{print $1}') ]]
		then
			megadl --path=${HOME}/storage/shared/Download/ https://mega.nz/$link;break
		elif [[ $book = Exit ]]
		then
			break
		else
			STDERR
		fi
	done
# elif [[ $1 = QG ]]
# then
# 	select QG in $(ls $iHLIBEXEC/../QG_*|awk -F "/" '{print $NF}') Exit;do
# 		if [[ ! -z $QG ]] && [[ -e $iHLIBEXEC/../$QG ]]
# 		then
#             [[ $QG = "QG_bWAPP.pdf" ]] && {
#                 termux-open $iHLIBEXEC/../$QG
#             } || {
#                 bash $iHLIBEXEC/../$QG
#             }
# 		elif [[ $QG = Exit ]]
# 		then
# 			exit
# 		else
# 			STDERR
# 		fi
# 	done
elif [[ $1 = alltools ]]
then
    chk-pkg column util-linux
    curl -sSL --fail "$iHDB/.local/etc/i-Haklab/Tools/listoftools" \
        -o $iHETC/Tools/listoftools 2>>"$LOGFILE" || \
        [[ -f "$iHETC/Tools/listoftools" ]] || touch "$iHETC/Tools/listoftools"
    curl -sSL --fail "$iHDB/.local/etc/i-Haklab/Tools/categories" \
        -o $iHETC/Tools/categories 2>>"$LOGFILE" || \
        [[ -f "$iHETC/Tools/categories" ]] || touch "$iHETC/Tools/categories"
    echo -en $Y$underline"TIP: You can install all of them with:$W apt install <tool>\n\n"
    cols=$(tput cols)
    awk -F: -v OFS='\t' -v catfile="$iHETC/Tools/categories" -v cols="$cols" '
    BEGIN {
        while ((getline < catfile) > 0) {
            map[$1] = $2
        }
        if (cols < 20) cols = 20
    }
    {
        c = map[$1] ? map[$1] : "Uncategorized"
        tools[c] = tools[c] ? tools[c] OFS $1 : $1
        if (!seen[c]++) { order[++n] = c }
    }
    END {
        for (i=1; i<=n; i++) {
            c = order[i]
            num = split(tools[c], tlist, "\t")

            ml = 0
            for (j=1; j<=num; j++) if (length(tlist[j]) > ml) ml = length(tlist[j])

            inner = cols - 2
            cw = ml + 2
            nc = int(inner / cw)
            if (nc < 1) nc = 1
            if (nc > num) nc = num
            if (cw > inner) cw = inner

            rem = inner - nc * cw
            base = int(rem / nc)
            extra = rem % nc
            for (j=1; j<=nc; j++) colw[j] = cw + base + (j <= extra ? 1 : 0)

            printf "\033[34m╔═══ \033[31m%s\033[34m ", c
            for (j=1; j<=cols-7-length(c); j++) printf "═"
            printf "╗\033[0m\n"

            nr = int((num + nc - 1) / nc)
            if (nr < 1) nr = 1

            for (r=1; r<=nr; r++) {
                printf "\033[34m║\033[0m"
                for (col=1; col<=nc; col++) {
                    idx = (col-1)*nr + r
                    if (idx <= num) {
                        printf " %-*s", colw[col]-1, tlist[idx]
                    } else {
                        printf " %-*s", colw[col]-1, ""
                    }
                }
                printf " \033[34m║\033[0m\n"
            }

            printf "\033[34m╚"
            for (j=1; j<=cols-2; j++) printf "═"
            printf "╝\033[0m\n"
        }
        printf "\n\033[32mTOTAL:\033[0m %d\n", NR
    }' $iHETC/Tools/listoftools
elif [[ $1 = instatools ]]
then
	chk-pkg column util-linux
	echo -en $Y$underline"TIP: You can remove all of them with:$W apt remove <tool>\n\n"
	pkg list-installed 2>>"$LOGFILE"|awk -F "/" '{print $1}' > $TMPDIR/instatools.tmp
	column $TMPDIR/instatools.tmp
	echo -en "$G\nTOTAL:$W $(wc $TMPDIR/instatools.tmp|awk '{print $1}')"
	rm -rf $TMPDIR/instatools.tmp
else
	STDERR
fi
