#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2
source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions

chk-pkg python python
command -v speedtest-cli >/dev/null || {
	python -m pip install --no-color --quiet --no-cache-dir speedtest-cli;
	ps=$(echo $!)
}

[[ -z $ps ]] && {
	running time 1;
} || {
	running ps $ps;
}
banner
speedtest-cli
