#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2

source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions

chk-pkg Xwayland xwayland
chk-pkg pulseaudio pulseaudio
command -v termux-x11 >/dev/null || { echo -en "${R}E:$W You need to install the Termux-Wayland(apk) deb file's.";exit;}

export XDG_RUNTIME_DIR=${TMPDIR}
pulseaudio --start --exit-idle-time=-1 2>/dev/null
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
am start -n com.termux.x11/com.termux.x11.MainActivity;sleep 3
#Xwayland
termux-x11 :0 >/dev/null &
sleep 3
env DISPLAY=:0 xfce4-session
