#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
trap ctrl_c 2

source ${HOME}/.local/etc/i-Haklab/variables
source $iHETC/functions

chk-pkg xfce4-session xfce4
chk-pkg dbus-launch dbus
chk-pkg Xwayland xwayland
chk-pkg pulseaudio pulseaudio

! command -v termux-x11 >/dev/null && {
    yes|apt install termux-x11-nightly
    git clone https://github.com/termux/termux-x11 ${PREFIX}/share/termux-x11 && cd $_
    git submodule update --init --recursive
} || ! command -v Xwayland >/dev/null && { 
    yes|apt install xwayland
} && { 
    echo -en "\e[31mE:\e[0m You need to install the Termux-Wayland(apk) deb file's."
    exit
}

export DISPLAY=:0
export XDG_RUNTIME_DIR=${TMPDIR}
export XKB_CONFIG_ROOT=${PREFIX}/share/xkeyboard-config-2/

pulseaudio --start --exit-idle-time=-1 2>/dev/null
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
am start -n com.termux.x11/com.termux.x11.MainActivity;sleep 3

[[ ! -z "$1" ]] && [[ "$1" == "Xwayland" ]] && { Xbin="$1";} || { Xbin="termux-x11";tip="Xwayland";}
$(command -v $Xbin) :0 >/dev/null &
sleep 5;xfce4-session --display=:0 || echo -en "${R}E: Display unreachable $W|$Y Try it with: ${G}i-Haklab Xwayland $tip$W"

killall main pulseaudio 2>/dev/null
####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
